# Integrates the nine new exercises of the 1-50 redo (2026-09-29) into the
# app: setup steps into setup.py, trainer content (gen.py) and the content
# map into SampleData.swift (the library rows and model map went in with the
# models), library-row changes an entry asks for (`library=`), and the
# families' fault ghosts into FaultPoses.swift. Always starts from the
# pristine copies saved on the first run (<scratch>/pristine), so it can be
# re-run after any family edit.
#   python3 integrate_1_50.py <scratch dir> [--skip <family>]
import json, os, re, shutil, sys, glob
HERE = os.path.dirname(os.path.abspath(__file__)); os.chdir(HERE); sys.path.insert(0, HERE)
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SD = os.path.join(REPO, "GymWorkout/Models/SampleData.swift")
FP = os.path.join(REPO, "GymWorkout/Models/FaultPoses.swift")
SU = os.path.join(HERE, "setup.py")
PR = os.path.join(sys.argv[1], "pristine"); os.makedirs(PR, exist_ok=True)
for f in (SD, FP, SU):
    keep = os.path.join(PR, os.path.basename(f))
    if not os.path.exists(keep): shutil.copy(f, keep)
    shutil.copy(keep, f)

import spec_1_50 as S
from common_1_50 import SETUP as NEW
SKIP = [sys.argv[i + 1] for i, a in enumerate(sys.argv) if a == "--skip"]
for fam in SKIP:
    S.SPEC[:] = [e for e in S.SPEC if e["name"] not in S.FAMILIES[fam]]
    S.ORDER[:] = [n for n in S.ORDER if n not in S.FAMILIES[fam]]
missing = [n for n in S.ORDER if n not in {e["name"] for e in S.SPEC}]
assert not missing, missing
problems = S.validate() + S.validate_library()
assert not problems, problems

# 1. setup.py
s = open(SU).read().rstrip()
assert s.endswith("}")
block = ["    # Exercises 1-50 redone (2026-09-29)"]
for n in S.ORDER:
    block.append(f'    "{n}": [')
    block += [f'        "{t}",' for t in NEW[n]]
    block.append("    ],")
open(SU, "w").write(s[:-1].rstrip() + "\n" + "\n".join(block) + "\n}\n")

# 2. gen
import setup  # noqa: E402  (the file just written)
sys.modules["spec"] = S
import gen  # noqa: E402
swift = "\n\n".join(gen.emit(e) for e in S.SPEC)
json.dump({"ex150": swift}, open("generated_1_50.json", "w"))
layout_lines = []
for e in S.SPEC:
    layout_lines.append(e["name"])
    for (cue, label, joint), (x, y, side, jx, jy) in gen.layout(e["name"], e["annotations"], e.get("overrides"), e.get("slots")):
        layout_lines.append(f"   {label:30s} {side:8s} x={x:.3f} y={y:.2f}  joint {joint:22s} at ({jx:.2f},{jy:.2f})")
open(os.path.join(sys.argv[1], "layout_1_50.txt"), "w").write("\n".join(layout_lines) + "\n")

# 3. SampleData.swift: library-row changes, content map, content block.
t = open(SD).read()
for e in S.SPEC:
    if "library" not in e: continue
    m, q, d = e["library"]
    pat = re.compile(r'(        Exercise\(name: "' + re.escape(e["name"]) + r'", category: \.\w+,\n'
                     r'                 primaryMuscle: )"[^"]*", equipment: "[^"]*",\n                 difficulty: \.\w+\)')
    assert len(pat.findall(t)) == 1, e["name"]
    t = pat.sub(lambda mm: f'{mm.group(1)}"{m}", equipment: "{q}",\n                 difficulty: .{d})', t)
old = '''        "Smith Machine Calf Raise": smithMachineCalfRaiseContent
    ]'''
assert t.count(old) == 1
t = t.replace(old, '''        "Smith Machine Calf Raise": smithMachineCalfRaiseContent,
        // Exercises 1-50 redone (2026-09-29)
''' + ",\n".join(f'        "{e["name"]}": {e["var"]}Content' for e in S.SPEC) + "\n    ]")
header = '''
    // MARK: - Exercises 1-50 redone (2026-09-29)
    //
    // The nine new exercises among the HIKSEMI drive's "1-100 🟢" re-exports:
    // Pendlay Row, five biceps curls, Reverse Curl, Wrist Curl and Close-Grip
    // Bench Press. Generated by `Tools/trainer-content/gen.py` from
    // `spec_1_50.py`; each family file's header lists what its models show
    // and its sources, and `notes_1_50_*.md` maps the copy's claims to them.

'''
assert t.rstrip().endswith("}")
t = t.rstrip()[:-1].rstrip() + "\n" + header + swift + "\n}\n"
open(SD, "w").write(t)

# 4. FaultPoses.swift
f = open(FP).read(); pieces, table = [], []
for path in sorted(glob.glob(os.path.join(REPO, "Tools/fault-review/faults_1_50_*.swift.txt"))):
    if any(path.endswith(f"_{fam}.swift.txt") for fam in SKIP): continue
    x = open(path).read(); a, b = x.index("// MARK: PIECES"), x.index("// MARK: TABLE")
    pieces.append(x[a + 15:b].strip("\n")); table.append(x[b + 14:].strip("\n"))
pm, tm = "    // MARK: Exercises 1-50 redo pieces (2026-09-29)\n", "        // MARK: Exercises 1-50 redo (2026-09-29)\n"
assert f.count(pm) == 1 and f.count(tm) == 1
f = f.replace(pm, pm + "\n".join(pieces) + "\n").replace(tm, tm + "\n".join(table) + "\n")
open(FP, "w").write(f)
print(f"integrated {len(S.SPEC)} exercises, {len(pieces)} fault families; layout in {sys.argv[1]}/layout_1_50.txt")
