# Integrates the 27 new exercises of the "351-400" folder (2026-09-30) into
# the app: setup steps into setup.py, trainer content (gen.py) and the
# content-map entries into SampleData.swift (the library rows and model map
# went in with the models), and the families' fault ghosts into
# FaultPoses.swift. Everything it writes sits between its own
# begin/end markers, which a re-run replaces, so it can run again after any
# family edit.
#   python3 integrate_400.py <scratch dir> [--skip <family>]
import json, os, re, sys, glob
HERE = os.path.dirname(os.path.abspath(__file__)); os.chdir(HERE); sys.path.insert(0, HERE)
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SD = os.path.join(REPO, "GymWorkout/Models/SampleData.swift")
FP = os.path.join(REPO, "GymWorkout/Models/FaultPoses.swift")
SU = os.path.join(HERE, "setup.py")
TAG = "351-400 (2026-09-30)"

def put(text, begin, end, body, anchor_before):
    """Replace what sits between begin and end, or insert the block before
    `anchor_before` the first time."""
    if begin in text:
        a = text.index(begin) + len(begin); b = text.index(end, a)
        return text[:a] + body + text[b:]
    assert text.count(anchor_before) == 1, anchor_before[:60]
    return text.replace(anchor_before, begin + body + end + anchor_before)

import spec_400 as S
from common_1_50 import SETUP as NEW
SKIP = [sys.argv[k + 1] for k, a in enumerate(sys.argv) if a == "--skip"]
for fam in SKIP:
    S.SPEC[:] = [e for e in S.SPEC if e["name"] not in S.FAMILIES[fam]]
    S.ORDER[:] = [n for n in S.ORDER if n not in S.FAMILIES[fam]]
missing = [n for n in S.ORDER if n not in {e["name"] for e in S.SPEC}]
assert not missing, missing
problems = S.validate(S.ORDER) + S.validate_library(S.ORDER)
assert not problems, problems

# 1. setup.py
s = open(SU).read()
body = "".join(f'    "{n}": [\n' + "".join(f'        "{t}",\n' for t in NEW[n]) + "    ],\n" for n in S.ORDER)
s = put(s, f"    # BEGIN {TAG}\n", f"    # END {TAG}\n", body, s[s.rstrip().rindex("}"):])
open(SU, "w").write(s)

# 2. gen
import importlib, setup  # noqa: E402
importlib.reload(setup)
sys.modules["spec"] = S
import gen  # noqa: E402
swift = "\n\n".join(gen.emit(e) for e in S.SPEC)
json.dump({"ex400": swift}, open("generated_400.json", "w"))
lines = []
for e in S.SPEC:
    lines.append(e["name"])
    for (cue, label, joint), (x, y, side, jx, jy) in gen.layout(e["name"], e["annotations"], e.get("overrides"), e.get("slots")):
        lines.append(f"   {label:30s} {side:8s} x={x:.3f} y={y:.2f}  joint {joint:22s} at ({jx:.2f},{jy:.2f})")
open(os.path.join(sys.argv[1], "layout_400.txt"), "w").write("\n".join(lines) + "\n")

# 3. SampleData.swift: content map entry and content block.
t = open(SD).read()
last = '        "Close-Grip Bench Press": closeGripBenchPressContent,\n    ]'
entries = "".join(f'        "{e["name"]}": {e["var"]}Content,\n' for e in S.SPEC)
if f"        // BEGIN {TAG}\n" not in t:
    assert t.count(last) == 1
    t = t.replace(last, last[:-5] + f"        // BEGIN {TAG}\n        // END {TAG}\n    ]")
t = put(t, f"        // BEGIN {TAG}\n", f"        // END {TAG}\n", entries, "")
header = f'''
    // MARK: - {TAG}
    //
    // The 27 new hamstring, glute and hip exercises of the HIKSEMI drive's
    // "351-400" folder. Generated by `Tools/trainer-content/gen.py` from
    // `spec_400.py`; each family file's header lists what its models show and
    // its sources, and `notes_400_*.md` maps the copy's claims to them.

'''
if f"    // BEGIN {TAG} content\n" not in t:
    assert t.rstrip().endswith("}")
    t = t.rstrip()[:-1].rstrip() + "\n" + f"    // BEGIN {TAG} content\n    // END {TAG} content\n" + "}\n"
t = put(t, f"    // BEGIN {TAG} content\n", f"    // END {TAG} content\n", header + swift + "\n", "")
open(SD, "w").write(t)

# 4. FaultPoses.swift
f = open(FP).read(); pieces, table = [], []
for path in sorted(glob.glob(os.path.join(REPO, "Tools/fault-review/faults_400_*.swift.txt"))):
    if any(path.endswith(f"_{fam}.swift.txt") for fam in SKIP): continue
    x = open(path).read(); a, b = x.index("// MARK: PIECES"), x.index("// MARK: TABLE")
    pieces.append(x[a + 15:b].strip("\n")); table.append(x[b + 14:].strip("\n"))
f = put(f, f"    // BEGIN {TAG} pieces\n", f"    // END {TAG} pieces\n",
        ("\n".join(pieces) + "\n") if pieces else "", "    // MARK: Exercises 1-50 redo pieces (2026-09-29)\n")
f = put(f, f"        // BEGIN {TAG}\n", f"        // END {TAG}\n",
        ("\n".join(table) + "\n") if table else "", "        // MARK: Exercises 1-50 redo (2026-09-29)\n")
open(FP, "w").write(f)
print(f"integrated {len(S.SPEC)} exercise(s), {len(pieces)} fault family(ies); layout in {sys.argv[1]}/layout_400.txt")
