# Setup steps for every trainer exercise, keyed by library name. Written to
# match what each shipped model actually shows (bench angle, seated/standing,
# grip, attachment), so keep them in sync when a model is re-exported.
# gen.py emits these as `ExerciseContent.setup`.

SETUP = {
    # Chest
    "Barbell Bench Press": [
        "Lie on the flat bench with your eyes under the bar.",
        "Grip the bar slightly wider than shoulder-width.",
        "Plant your feet and pull your shoulder blades together.",
        "Unrack to straight arms, bar over your shoulders.",
    ],
    "Incline Barbell Bench Press": [
        "Set the bench to about 30° and lie back, eyes under the bar.",
        "Grip the bar slightly wider than shoulder-width.",
        "Plant your feet and pull your shoulder blades back and down.",
        "Unrack to straight arms, bar over your collarbones.",
    ],
    "Decline Barbell Bench Press": [
        "Hook your legs under the foot rollers of the decline bench.",
        "Lie back with your eyes under the bar.",
        "Grip the bar slightly wider than shoulder-width.",
        "Unrack to straight arms, bar over your shoulders.",
    ],
    "Dumbbell Bench Press": [
        "Sit on the end of a flat bench, dumbbells on your thighs.",
        "Lie back and bring the dumbbells beside your chest.",
        "Plant your feet and pull your shoulder blades together.",
        "Press to straight arms, palms facing forward.",
    ],
    "Incline Dumbbell Press": [
        "Set the bench to about 30° and sit with the dumbbells on your thighs.",
        "Lie back and bring the dumbbells beside your upper chest.",
        "Plant your feet and pull your shoulder blades together.",
        "Press to straight arms, palms facing forward.",
    ],
    "Dumbbell Fly": [
        "Lie on a flat bench with your feet flat on the floor.",
        "Press the dumbbells over your chest, palms facing each other.",
        "Unlock the elbows slightly and keep that bend throughout.",
    ],
    "Incline Dumbbell Fly": [
        "Set the bench to about 30° and lie back.",
        "Press the dumbbells over your upper chest, palms facing each other.",
        "Unlock the elbows slightly and keep that bend throughout.",
    ],
    "Chest Press Machine": [
        "Set the seat so the handles line up with your mid-chest.",
        "Sit with your back flat against the pad, feet on the floor.",
        "Grip the handles with your elbows below shoulder height, about 45° from your torso.",
    ],
    "Pec Deck Fly": [
        "Set the seat so the handles sit at chest height.",
        "Sit tall with your back against the pad.",
        "Take the handles out wide with a slight bend in the elbows.",
    ],
    "Cable Fly": [
        "Set both pulleys at about shoulder height.",
        "Take a handle in each hand and step forward between the stacks.",
        "Stand in a split stance, leaning slightly forward, elbows soft.",
    ],
    "Low-to-High Cable Fly": [
        "Set both pulleys at their lowest position.",
        "Take a handle in each hand and step forward to the centre.",
        "Start with the hands low beside your hips, elbows soft.",
    ],
    # Back
    "Deadlift": [
        "Stand with feet hip-width, the bar over mid-foot.",
        "Hinge down and grip the bar just outside your knees.",
        "Drop your hips until your shins touch the bar.",
        "Chest up, back flat, pull the slack out of the bar.",
    ],
    "Barbell Bent-Over Row": [
        "Hold the bar with an overhand, shoulder-width grip.",
        "Soften your knees and hinge forward to about 45°.",
        "Brace with a flat back, the bar hanging below your shoulders.",
    ],
    "Dumbbell Row": [
        "Hold a dumbbell in each hand, palms facing in.",
        "Soften your knees and hinge forward to about 45°.",
        "Brace with a flat back, the dumbbells hanging below your shoulders.",
    ],
    "One-Arm Dumbbell Row": [
        "Put one knee and the same-side hand on a flat bench.",
        "Plant the other foot out to the side on the floor.",
        "Hold the dumbbell at arm's length, back flat and level.",
    ],
    "Chest-Supported Dumbbell Row": [
        "Set an incline bench to about 30–45°.",
        "Lie chest-down on it with your feet on the floor.",
        "Let the dumbbells hang straight down, palms facing in.",
    ],
    "Pull-Up": [
        "Grip the bar overhand, slightly wider than shoulder-width.",
        "Hang with straight arms and your shoulders pulled down.",
        "Cross your ankles and brace your core.",
    ],
    "Chin-Up": [
        "Grip the bar underhand, about shoulder-width apart.",
        "Hang with straight arms and your shoulders pulled down.",
        "Cross your ankles and brace your core.",
    ],
    "Lat Pulldown": [
        "Adjust the thigh pad so your legs are locked in.",
        "Take a wide overhand grip on the bar.",
        "Sit down tall with your arms straight overhead.",
    ],
    "Close-Grip Lat Pulldown": [
        "Adjust the thigh pad so your legs are locked in.",
        "Take a close grip, hands about shoulder-width apart.",
        "Sit down tall with your arms straight overhead.",
    ],
    "Seated Cable Row": [
        "Sit on the bench with your feet braced on the foot plate.",
        "Bend your knees slightly and grab the handle.",
        "Sit tall with your arms extended and your chest up.",
    ],
    "Straight-Arm Pulldown": [
        "Set the pulley high and grip the bar with both hands.",
        "Step back and hinge slightly at the hips.",
        "Start with straight arms at shoulder height, elbows soft.",
    ],
    "T-Bar Row": [
        "Straddle the bar with feet about shoulder-width apart.",
        "Hinge to about 45° and grip the handle just below the plates.",
        "Brace with a flat back and your arms extended.",
    ],
    "Chest-Supported Row Machine": [
        "Set the seat so the handles line up with your lower chest.",
        "Sit with your chest against the pad, feet planted.",
        "Reach forward and grab the handles with straight arms.",
    ],
    "High Row Machine": [
        "Adjust the seat and thigh pad so your legs are locked in.",
        "Reach up and grab the handles with straight arms.",
        "Sit tall, chest up and shoulders down.",
    ],
    "Back Extension": [
        "Set the hip pad so its top edge sits at your hip bones.",
        "Hook your ankles snugly under the roller.",
        "Lean over the pad with your hips on it and your waist free to curl past its edge.",
        "Cross your arms over your chest, body in a straight line.",
    ],
    # Legs
    "Back Squat": [
        "Set the bar on your upper traps, hands just outside the shoulders.",
        "Step back and set your feet shoulder-width, toes slightly out.",
        "Take a deep breath and brace, chest tall.",
    ],
    "Front Squat": [
        "Rest the bar on the front of your shoulders, close to the throat.",
        "Fingertips under the bar, elbows pointing forward and high.",
        "Feet shoulder-width, toes slightly out.",
    ],
    "Goblet Squat": [
        "Hold one dumbbell upright against your chest.",
        "Tuck your elbows under the dumbbell.",
        "Feet shoulder-width, toes slightly out, chest tall.",
    ],
    "Walking Lunge": [
        "Hold a dumbbell in each hand at your sides.",
        "Stand tall with your feet hip-width apart.",
        "Clear space ahead to walk forward in long steps.",
    ],
    "Reverse Lunge": [
        "Hold a dumbbell in each hand at your sides.",
        "Stand tall with your feet hip-width apart.",
        "Brace your core before each step back.",
    ],
    "Leg Press": [
        "Sit with your back and hips flat against the pad.",
        "Place your feet shoulder-width in the middle of the platform.",
        "Press the platform up, release the safety handles and hold the side handles.",
    ],
    "Hack Squat": [
        "Stand on the platform with your back against the pad.",
        "Set your shoulders under the pads, feet shoulder-width.",
        "Hold the handles and release the safety.",
    ],
    "Leg Extension": [
        "Set the back pad so your knees line up with the machine's pivot.",
        "Set the ankle pad just above your feet.",
        "Sit tall and hold the side handles.",
    ],
    "Smith Machine Squat": [
        "Set the bar at shoulder height and step under it.",
        "Bar on your upper traps, feet slightly in front of the bar.",
        "Turn the bar to unhook it and brace your core.",
    ],
    "Sissy Squat": [
        "Lock your heels under the foot pad, shins against the front pad.",
        "Stand tall with your hips fully extended.",
        "Hold your hands in front of your chest for balance.",
    ],
    "Romanian Deadlift": [
        "Hold the bar at hip height with an overhand, shoulder-width grip.",
        "Feet hip-width, knees slightly bent.",
        "Shoulders back and back flat, bar against your thighs.",
    ],
    # Shoulders
    "Barbell Overhead Press": [
        "Hold the bar at your collarbones, hands just outside the shoulders.",
        "Stand with your feet hip-width and knees locked.",
        "Squeeze your glutes and brace your core.",
    ],
    "Dumbbell Shoulder Press": [
        "Set the bench upright and sit with your back against the pad.",
        "Kick the dumbbells up to shoulder height.",
        "Palms forward, forearms vertical, feet flat and wide.",
    ],
    "Arnold Press": [
        "Set the bench upright and sit with your back against the pad.",
        "Hold the dumbbells in front of your chin, palms facing you.",
        "Plant your feet flat and wide.",
    ],
    "Machine Shoulder Press": [
        "Set the seat so the handles are at shoulder height.",
        "Sit with your back flat against the pad, feet on the floor.",
        "Grip the handles with your elbows under your wrists.",
    ],
    "Dumbbell Lateral Raise": [
        "Stand tall with a dumbbell in each hand at your sides.",
        "Feet hip-width, knees soft.",
        "Palms facing in, a slight bend in the elbows.",
    ],
    "Cable Lateral Raise": [
        "Set the pulley at its lowest position.",
        "Stand side-on and take the handle in the far hand.",
        "Hold the frame with your free hand, handle in front of your hips.",
    ],
    "Machine Lateral Raise": [
        "Set the seat so your shoulders line up with the pivots.",
        "Sit tall with the pads against the outsides of your arms.",
        "Hold the handles lightly.",
    ],
    "Dumbbell Front Raise": [
        "Stand with a dumbbell in each hand in front of your thighs.",
        "Palms facing your body, elbows softly bent.",
        "Feet hip-width, core braced.",
    ],
    "Reverse Dumbbell Fly": [
        "Hold a dumbbell in each hand, palms facing in.",
        "Hinge forward until your torso is nearly parallel to the floor.",
        "Let the dumbbells hang under your chest, elbows soft.",
    ],
    "Reverse Pec Deck": [
        "Set the handles to the rear position, at shoulder height.",
        "Sit facing the machine with your chest against the pad.",
        "Grip the handles with straight arms.",
    ],
    "Face Pull": [
        "Set the pulley at upper-chest to face height with a rope.",
        "Hold the rope ends with your palms facing each other.",
        "Step back until your arms are straight, feet staggered.",
    ],
    "Cable Rear Delt Fly": [
        "Set both pulleys at shoulder height.",
        "Cross the cables: left handle in your right hand, right in your left.",
        "Step back to the middle with your arms straight in front.",
    ],
    # Arms
    "Barbell Curl": [
        "Hold the bar underhand, hands shoulder-width apart.",
        "Stand tall with straight arms, the bar against your thighs.",
        "Elbows by your sides, knees soft.",
    ],
    "Triceps Pushdown": [
        "Attach a straight bar to a high pulley.",
        "Grip it overhand with your hands shoulder-width apart.",
        "Elbows at your sides, lean slightly forward.",
    ],
    "Rope Pushdown": [
        "Attach a rope to a high pulley.",
        "Grip the rope ends with your palms facing each other.",
        "Elbows at your sides, lean slightly forward.",
    ],
    "Single-Arm Cable Pushdown": [
        "Attach a single handle to a high pulley.",
        "Grip it with one hand, palm down.",
        "Elbow at your side, free hand on your hip.",
    ],
    "Overhead Cable Triceps Extension": [
        "Attach a rope to a low pulley.",
        "Face away from the stack with the rope behind your head.",
        "Staggered stance, elbows pointing forward.",
    ],
    "Dumbbell Overhead Triceps Extension": [
        "Hold one dumbbell with both hands under its top plate.",
        "Press it overhead to straight arms.",
        "Feet hip-width, ribs down, core braced.",
    ],
    "Skull Crusher": [
        "Lie on a flat bench with your feet flat on the floor.",
        "Hold an EZ bar with a narrow overhand grip.",
        "Press it up, arms tilted slightly back toward your head.",
    ],
    "Bench Dip": [
        "Sit on the edge of a bench, hands beside your hips.",
        "Fingers forward, slide your hips off the bench.",
        "Legs out with heels on the floor, arms straight.",
    ],
    "Assisted Dip": [
        "Select an assistance weight on the stack.",
        "Grip the dip handles and kneel on the pad.",
        "Start with straight arms, shoulders down.",
    ],
    "Bulgarian Split Squat": [
        "Stand about a stride in front of a knee-height bench.",
        "Rest the laces of your rear foot on the bench.",
        "Hold a dumbbell in each hand at your sides.",
    ],
    "Bulgarian Split Squat (Lean)": [
        "Stand about a stride in front of a knee-height bench.",
        "Rest the laces of your rear foot on the bench.",
        "Hands on your hips, lean forward about 40° from the hips.",
    ],
    # Legs2 batch and re-exports (2026-09-24)
    "Dumbbell Romanian Deadlift": [
        "Stand hip-width with a dumbbell in each hand in front of your thighs.",
        "Unlock your knees slightly and brace your trunk.",
        "Pull your shoulders back and keep the dumbbells against your legs.",
    ],
    "Stiff-Leg Deadlift": [
        "Stand hip-width holding the barbell at arm's length, overhand grip.",
        "Keep your knees almost straight, with just a slight bend.",
        "Brace your trunk and pull your shoulders back.",
    ],
    "Lying Leg Curl": [
        "Lie face down on the bench, knees just off the end of the pad.",
        "Set the roller on your lower legs, just above the heels.",
        "Hold the handles and press your hips into the pad.",
    ],
    "Seated Leg Curl": [
        "Sit with your back against the pad, knees in line with the pivot.",
        "Rest your lower legs on the roller, just above the heels.",
        "Lock the thigh pad down above your knees and hold the handles.",
    ],
    "Single-Leg Curl": [
        "Lie face down on the bench, knees just off the end of the pad.",
        "Set the roller above the heel of the working leg.",
        "Hold the handles and keep both hips pressed into the pad.",
    ],
    "Glute Bridge": [
        "Lie on your back on a mat, knees bent.",
        "Set your heels about a hand's length from your glutes, hip-width apart.",
        "Rest your arms flat beside you, palms down.",
    ],
    "Single-Leg Glute Bridge": [
        "Lie on your back on a mat, knees bent.",
        "Plant the working foot close to your glutes.",
        "Lift the other foot off the floor and rest your arms flat beside you.",
    ],
    "Cable Glute Kickback": [
        "Attach an ankle cuff to the low pulley and strap it to your working ankle.",
        "Face the stack and hold the frame with both hands.",
        "Step back until the cable is tight and hinge forward slightly.",
    ],
    "Cable Side Kick": [
        "Attach an ankle cuff to the low pulley and strap it to the far ankle.",
        "Stand side-on to the stack, hold the rail with your near hand and rest the other on your hip.",
        "Let the working leg cross slightly in front, toes forward.",
    ],
    "Cable Hip Abduction": [
        "Attach an ankle cuff to the low pulley and strap it to the far ankle.",
        "Stand side-on to the stack, one hand on the balance post and the other on your hip.",
        "Stand tall with the hips level and the standing knee soft.",
    ],
    "Hip Abduction Machine": [
        "Set the pads so your knees start close together.",
        "Sit back against the pad with your feet on the footrests.",
        "Place the pads on the outsides of your knees and hold the handles.",
    ],
    "Hip Abduction Machine (Lean)": [
        "Set the pads so your knees start close together.",
        "Sit with your feet on the footrests and the pads outside your knees.",
        "Hold the handles and lean forward from the hips.",
    ],
    "Step-Up": [
        "Stand facing a knee-height box, a dumbbell in each hand.",
        "Place your whole working foot flat on the box.",
        "Lean slightly forward over the top foot.",
    ],
    "Push-Up": [
        "Kneel on a mat with your hands slightly wider than your shoulders.",
        "Step your feet back, toes tucked, body in one straight line.",
        "Brace your abs and squeeze your glutes.",
    ],
    "Plank": [
        "Kneel on a mat and set your elbows under your shoulders.",
        "Step your feet back, toes tucked, hip-width apart.",
        "Lift your knees and hold a straight line from head to heels.",
    ],
    # Abs batch (2026-09-24)
    "Crunch": [
        "Lie on your back on a mat, knees bent, feet flat.",
        "Rest your fingertips behind your ears, elbows wide.",
        "Press your lower back gently into the mat.",
    ],
    "Reverse Crunch": [
        "Lie on your back on a mat, arms flat beside you.",
        "Lift your legs so your knees are bent about 90° over your hips.",
        "Keep your head and shoulders resting on the mat.",
    ],
    "Decline Crunch": [
        "Set the bench to a slight decline.",
        "Hook your ankles under the foot pads and lie back.",
        "Rest your fingertips behind your ears, or cross your arms on your chest.",
    ],
    "Cable Crunch": [
        "Attach a rope to the high pulley.",
        "Kneel on a mat about an arm's length from the stack.",
        "Hold the rope ends beside your head, hips over your knees.",
    ],
    "Hanging Knee Raise": [
        "Grip the bar just outside shoulder-width.",
        "Hang with straight arms, shoulders pulled slightly down.",
        "Let your legs hang still before the first rep.",
    ],
    "Hanging Leg Raise": [
        "Grip the bar just outside shoulder-width.",
        "Hang with straight arms, shoulders pulled slightly down.",
        "Keep your legs straight and together, and stop any swing.",
    ],
    "Captain's Chair Leg Raise": [
        "Step up and rest your forearms on the arm pads.",
        "Grip the handles and press your back against the pad.",
        "Let your legs hang straight below you.",
    ],
    "Ab Wheel Rollout": [
        "Kneel on a mat, knees hip-width apart.",
        "Hold the wheel handles under your shoulders, arms straight.",
        "Brace your abs and tuck your pelvis slightly.",
    ],
    "Side Plank": [
        "Lie on your side on a mat, legs straight and stacked.",
        "Place your elbow directly under your shoulder.",
        "Rest your top hand on your hip, then lift your hips.",
    ],
    "Russian Twist": [
        "Sit on a mat with your knees bent and heels on the floor.",
        "Hold a medicine ball at chest height.",
        "Lean back about 45° with a straight spine.",
    ],
    "Cable Wood Chop": [
        "Set a handle on the high pulley and stand side-on to the stack.",
        "Take a wide stance and hold the handle with both hands.",
        "Start with straight arms reaching up toward the pulley.",
    ],
    # Gated exercises re-exported, plus the lean lunge (2026-09-24)
    "Biceps Curl": [
        "Hold a dumbbell in each hand, palms facing forward.",
        "Stand tall, feet hip-width, arms straight by your sides.",
        "Draw your shoulders back and keep your elbows by your ribs.",
    ],
    "Squat": [
        "Stand with your feet a little wider than hip-width.",
        "Turn your toes slightly out.",
        "Raise your arms straight in front to shoulder height.",
        "Brace your core and lift your chest.",
    ],
    "Lunge": [
        "Stand tall with your hands on your hips.",
        "Step one foot forward about a stride's length.",
        "Lift your back heel and square your hips to the front.",
    ],
    "Lunge (Lean)": [
        "Stand tall with your hands on your hips.",
        "Step one foot forward about a stride's length and lift your back heel.",
        "Tilt your torso about 30° forward from the hips, back flat.",
    ],
    # Chest batch 101-131 (2026-09-25)
    "Barbell Floor Press": [
        "Set the bar low in a rack and lie on the floor under it, eyes below the bar.",
        "Bend your knees and set your feet flat, hip-width apart.",
        "Grip the bar slightly wider than shoulder-width.",
        "Pull your shoulder blades into the floor and unrack to straight arms.",
    ],
    "Smith Machine Bench Press": [
        "Set a flat bench under the bar so it lowers to your lower chest.",
        "Lie back with your feet planted and your eyes just below the bar.",
        "Grip slightly wider than shoulder-width and pull your shoulder blades together.",
        "Unhook the bar by turning it back off the hooks.",
    ],
    "Smith Machine Incline Press": [
        "Set the bench to about 30° under the bar.",
        "Sit back so the bar lowers to your upper chest.",
        "Grip slightly wider than shoulder-width and plant your feet.",
        "Pull your shoulder blades back and down, then unhook the bar.",
    ],
    "Smith Machine Decline Press": [
        "Set a decline bench under the bar, about 15° head-down.",
        "Hook your legs under the ankle roller and lie back.",
        "Line up so the bar lowers to your lower chest.",
        "Grip slightly wider than shoulder-width and unhook the bar.",
    ],
    "Dumbbell Floor Press": [
        "Sit on the floor with a dumbbell on each thigh.",
        "Lie back with your knees bent and feet flat, dumbbells beside your chest.",
        "Rest your upper arms on the floor at about 45° from your body.",
        "Press to straight arms over your chest.",
    ],
    "Single-Arm Dumbbell Bench Press": [
        "Lie on a flat bench with one dumbbell beside your chest.",
        "Plant your feet wider than your hips.",
        "Rest your free arm at your side and pull both shoulder blades back.",
        "Press the dumbbell to a straight arm over your shoulder.",
    ],
    "Alternating Dumbbell Bench Press": [
        "Lie on a flat bench with a dumbbell in each hand beside your chest.",
        "Plant your feet and pull your shoulder blades together.",
        "Press one dumbbell up while the other waits at your chest.",
        "Lower it back down, then press the other side.",
    ],
    "Neutral-Grip Dumbbell Press": [
        "Lie on a flat bench with a dumbbell in each hand.",
        "Turn your palms to face each other.",
        "Plant your feet and pull your shoulder blades together.",
        "Press to straight arms over your chest, elbows close to your sides.",
    ],
    "Dumbbell Squeeze Press": [
        "Lie on a flat bench with a dumbbell in each hand.",
        "Press the dumbbells together over your chest, palms facing in.",
        "Plant your feet and pull your shoulder blades together.",
        "Keep squeezing them together as you lower and press.",
    ],
    "Incline Dumbbell Squeeze Press": [
        "Set the bench to about 30° and lie back with a dumbbell in each hand.",
        "Press the dumbbells together over your upper chest, palms facing in.",
        "Plant your feet and pull your shoulder blades back and down.",
        "Keep squeezing them together as you lower and press.",
    ],
    "Dumbbell Pullover": [
        "Lie along a flat bench with your head at the end.",
        "Hold one dumbbell over your chest, both palms under the top plate.",
        "Plant your feet and keep a slight bend in your elbows.",
    ],
    "Barbell Pullover": [
        "Lie along a flat bench with your head near the end.",
        "Hold the bar over your chest, hands about shoulder-width apart.",
        "Plant your feet and keep a slight bend in your elbows.",
    ],
    "Iso-Lateral Chest Press": [
        "Set the seat so the handles line up with your mid-chest.",
        "Sit tall with your back on the pad and your feet flat.",
        "Grip both handles; press with one arm at a time.",
    ],
    "Incline Chest Press Machine": [
        "Set the seat so the handles line up with your upper chest.",
        "Sit back against the angled pad with your feet flat.",
        "Grip the handles with your wrists straight.",
    ],
    "Decline Chest Press Machine": [
        "Set the seat so the handles line up with your lower chest.",
        "Sit tall with your back on the pad and your feet flat.",
        "Grip the handles with your wrists straight.",
    ],
    "Plate-Loaded Chest Press": [
        "Load the same plates on both sides.",
        "Set the seat so the handles line up with your mid-chest.",
        "Sit tall with your back on the pad and your feet flat.",
        "Grip the handles with your wrists straight.",
    ],
    "Wide-Grip Chest Press Machine": [
        "Set the seat so the handles line up with your mid-chest.",
        "Sit tall with your back on the pad and your feet flat.",
        "Take the outer handles, wider than your shoulders.",
    ],
    "Cable Chest Press": [
        "Set both pulleys at chest height and take a handle in each hand.",
        "Face away from the stacks and step forward until the cables are tight.",
        "Stand in a staggered stance, handles beside your chest.",
    ],
    "Single-Arm Cable Chest Press": [
        "Set one pulley at chest height and take the handle in one hand.",
        "Face away from the stack and step forward into a staggered stance.",
        "Hold the handle beside your chest, elbow about 45° from your body.",
        "Keep your free arm by your side.",
    ],
    "Incline Cable Press": [
        "Set a bench to about 30° between two low pulleys.",
        "Take a handle in each hand and lie back.",
        "Plant your feet and pull your shoulder blades back and down.",
        "Start with the handles beside your upper chest.",
    ],
    "Decline Cable Press": [
        "Set a decline bench between two low pulleys.",
        "Take a handle in each hand and hook your legs under the roller.",
        "Lie back and pull your shoulder blades together.",
        "Start with the handles beside your lower chest.",
    ],
    "High-to-Low Cable Fly": [
        "Set both pulleys high and take a handle in each hand.",
        "Step forward into a staggered stance until the cables are tight.",
        "Open your arms wide and high, elbows slightly bent.",
    ],
    "Single-Arm Cable Fly": [
        "Set one pulley at shoulder height and stand side-on to the stack.",
        "Take the handle in the near hand and step away until the cable is tight.",
        "Open that arm out toward the stack, elbow slightly bent.",
        "Rest your free hand on your hip.",
    ],
    "Incline Cable Fly": [
        "Set a bench to about 30° between two low pulleys.",
        "Take a handle in each hand and lie back.",
        "Open your arms wide, elbows slightly bent.",
    ],
    "Decline Cable Fly": [
        "Set a decline bench between two low pulleys.",
        "Take a handle in each hand and hook your legs under the roller.",
        "Lie back and open your arms wide, elbows slightly bent.",
    ],
    "Cable Crossover": [
        "Set both pulleys at shoulder height and take a handle in each hand.",
        "Step forward into a staggered stance until the cables are tight.",
        "Open your arms wide, elbows slightly bent, chest up.",
    ],
    "Single-Arm Landmine Press": [
        "Wedge one end of a bar in a landmine and load the other end.",
        "Stand facing the loaded end in a staggered stance.",
        "Hold the end of the bar at the front of your shoulder in one hand.",
        "Rest your free hand on your hip, brace your core and squeeze your glutes.",
    ],
    "Incline Push-Up": [
        "Place your hands on the edge of a bench, a bit wider than your shoulders.",
        "Walk your feet back until your body forms a straight line.",
        "Tuck your toes, feet together, and brace your core.",
    ],
    # Batch 133-160 (2026-09-25)
    "Diamond Push-Up": [
        "Kneel and place your hands under your chest, thumbs and index fingers touching.",
        "Walk your feet back until your body forms a straight line.",
        "Tuck your toes, feet together, and brace your core.",
    ],
    "Wide-Grip Push-Up": [
        "Place your hands about one and a half shoulder-widths apart, level with your chest.",
        "Walk your feet back until your body forms a straight line.",
        "Tuck your toes, feet together, and brace your core.",
    ],
    "Archer Push-Up": [
        "Place your hands about twice shoulder-width apart, fingers turned slightly out.",
        "Walk your feet back until your body forms a straight line.",
        "Brace your core; you will shift toward one hand at a time.",
    ],
    "Medicine Ball Push-Up": [
        "Set a medicine ball under your chest.",
        "Press both hands flat on top of the ball, fingers spread.",
        "Walk your feet back until your body forms a straight line, feet together.",
    ],
    "Pause Bench Press": [
        "Lie on the flat bench with your eyes under the bar.",
        "Grip the bar slightly wider than shoulder-width.",
        "Plant your feet and pull your shoulder blades together.",
        "Unrack to straight arms; each rep stops still on your chest before the press.",
    ],
    "Larsen Press": [
        "Lie on the flat bench with your eyes under the bar.",
        "Grip the bar slightly wider than shoulder-width and unrack.",
        "Straighten your legs out in line with the bench, feet off the floor.",
        "Keep your glutes and upper back flat on the bench.",
    ],
    "Reverse-Grip Bench Press": [
        "Lie on the flat bench with your eyes under the bar.",
        "Grip underhand, just over shoulder-width, thumbs around the bar.",
        "Plant your feet and pull your shoulder blades together.",
        "Unrack with a spotter's help, bar over your shoulders.",
    ],
    "Rack Pull": [
        "Set the rack pins just below knee height and rest the bar on them.",
        "Stand close with your feet hip-width, the bar against your legs.",
        "Hinge down and grip just outside your legs, back flat.",
        "Brace and pull the slack out of the bar.",
    ],
    "Block Pull": [
        "Rest the loaded bar on blocks so it sits just below your knees.",
        "Stand close with your feet hip-width, the bar against your legs.",
        "Hinge down and grip just outside your legs, back flat.",
        "Brace and pull the slack out of the bar.",
    ],
    "Sumo Deadlift": [
        "Stand with your feet about twice shoulder-width, toes turned out.",
        "Bring your shins close to the bar, which sits over your mid-foot.",
        "Grip the bar at shoulder-width, hands inside your knees.",
        "Push your knees out, chest up, and pull the slack out of the bar.",
    ],
    "Trap Bar Deadlift": [
        "Stand in the centre of the trap bar, feet hip-width.",
        "Sit your hips down and grip the side handles.",
        "Chest up, back flat, arms straight.",
        "Brace and pull the slack out of the bar.",
    ],
    "Snatch-Grip Deadlift": [
        "Stand with your feet hip-width, the bar over your mid-foot.",
        "Grip the bar wide, about twice shoulder-width.",
        "Sit your hips down until your arms are straight and your chest is up.",
        "Set your shoulders back and pull the slack out of the bar.",
    ],
    "Deficit Deadlift": [
        "Stand on a stable 3–10 cm platform, feet hip-width.",
        "Line the bar up over your mid-foot.",
        "Hinge and grip just outside your shins.",
        "Drop your hips, chest up, and pull the slack out of the bar.",
    ],
    "Barbell Yates Row": [
        "Hold the bar underhand at shoulder-width.",
        "Soften your knees and lean forward to about 35° from upright.",
        "Brace with a flat back, the bar hanging at your knees.",
    ],
    "Reverse-Grip Barbell Row": [
        "Hold the bar underhand at shoulder-width.",
        "Soften your knees and hinge forward well past 45°.",
        "Brace with a flat back, the bar hanging below your shoulders.",
    ],
    "Wide-Grip Barbell Row": [
        "Hold the bar overhand, well outside shoulder-width.",
        "Soften your knees and hinge until your torso is nearly level.",
        "Brace with a flat back, the bar hanging under your shoulders.",
    ],
    "Seal Row": [
        "Set a flat bench high enough that your arms hang without the bar touching the floor.",
        "Lie face down with your chest on the end of the bench.",
        "Grip the bar overhand at shoulder-width, arms hanging straight.",
    ],
    "Meadows Row": [
        "Wedge one end of a bar in a landmine and load the other end.",
        "Stand side-on to the loaded end in a staggered stance.",
        "Hinge forward and rest your free forearm on your front knee.",
        "Grip the sleeve overhand just behind the collar.",
    ],
    "Landmine Row": [
        "Wedge one end of a bar in a landmine and load the other end.",
        "Straddle the bar facing the plates and set a close-grip handle under it.",
        "Hinge forward with a flat back and grip the handle, arms straight.",
    ],
    "Single-Arm Landmine Row": [
        "Wedge one end of a bar in a landmine and load the other end.",
        "Stand beside the bar's end, feet hip-width, and hinge forward.",
        "Grip the bar just below the plates with one hand.",
        "Rest your free hand on your thigh.",
    ],
    "Dumbbell Bent-Over Row": [
        "Hold a dumbbell in each hand, palms facing in.",
        "Soften your knees and push your hips back until your torso is well below 45°.",
        "Brace with a flat back, the dumbbells hanging under your shoulders.",
    ],
    "Renegade Row": [
        "Set two dumbbells shoulder-width apart on the floor.",
        "Grip them and walk into a high plank, hands under your shoulders.",
        "Set your feet wider than your hips and brace your core.",
    ],
    "Kettlebell Row": [
        "Hold a kettlebell in one hand, feet hip-width.",
        "Soften your knees and hinge forward with a flat back.",
        "Rest your free hand on your thigh, the bell hanging under your shoulder.",
    ],
    "Gorilla Row": [
        "Stand wide with two kettlebells on the floor between your feet.",
        "Bend your knees and push your hips back until your torso is nearly level.",
        "Grip both handles, back flat, arms straight.",
    ],
    "Inverted Row": [
        "Set a bar at about hip height in a rack or Smith machine.",
        "Lie under it and grip overhand, a little wider than your shoulders.",
        "Straighten your body from heels to head, heels on the floor.",
    ],
    "Feet-Elevated Inverted Row": [
        "Set a bar at about hip height and a bench in front of it.",
        "Grip the bar overhand, a little wider than your shoulders.",
        "Rest your heels on the bench and straighten your body into a plank.",
    ],
    "Underhand Inverted Row": [
        "Set a bar at about hip height in a rack or Smith machine.",
        "Lie under it and grip underhand at shoulder-width.",
        "Straighten your body from heels to head, heels on the floor.",
    ],
    # Batch 161-190 (2026-09-25)
    "Wide-Grip Pull-Up": [
        "Grip the bar overhand, about one and a half shoulder-widths apart.",
        "Hang with straight arms, legs together, knees slightly bent.",
        "Brace your core and pull your shoulders down.",
    ],
    "Neutral-Grip Pull-Up": [
        "Grip the parallel handles, palms facing each other.",
        "Hang with straight arms, legs together, knees slightly bent.",
        "Brace your core and pull your shoulders down.",
    ],
    "Archer Pull-Up": [
        "Grip the bar overhand, about twice shoulder-width.",
        "Hang with straight arms, legs together.",
        "Brace your core; you will pull toward one hand at a time.",
    ],
    "Weighted Pull-Up": [
        "Put on a dip belt with a plate hanging from the chain.",
        "Grip the bar overhand, a little wider than your shoulders.",
        "Hang with straight arms, legs together, the plate still.",
    ],
    "Assisted Pull-Up": [
        "Set the counterweight: more weight gives more help.",
        "Grip the bar overhand, a little wider than your shoulders.",
        "Kneel on the pad and hang with straight arms.",
    ],
    "Neutral-Grip Chin-Up": [
        "Grip the close parallel handles, palms facing each other.",
        "Hang with straight arms, legs together, knees slightly bent.",
        "Brace your core and pull your shoulders down.",
    ],
    "Weighted Chin-Up": [
        "Put on a dip belt with a plate hanging from the chain.",
        "Grip the bar underhand at shoulder-width.",
        "Hang with straight arms, legs together, the plate still.",
    ],
    "Machine Pull-Up": [
        "Set the counterweight: more weight gives more help.",
        "Grip the bar overhand, a little wider than your shoulders.",
        "Stand on the platform and hang with straight arms.",
    ],
    "Wide-Grip Lat Pulldown": [
        "Adjust the thigh pads so your legs are locked in.",
        "Grip the bar overhand where it starts to bend.",
        "Sit down tall with your arms overhead, elbows slightly bent.",
    ],
    "Reverse-Grip Lat Pulldown": [
        "Adjust the thigh pads so your legs are locked in.",
        "Grip the bar underhand at shoulder-width.",
        "Sit down tall with your arms straight overhead.",
    ],
    "Neutral-Grip Lat Pulldown": [
        "Attach a neutral-grip bar and adjust the thigh pads.",
        "Take the handles with your palms facing each other.",
        "Sit down tall with your arms straight overhead.",
    ],
    "V-Bar Lat Pulldown": [
        "Attach a V-handle to the high pulley and adjust the thigh pads.",
        "Hold the handle with both hands, palms facing.",
        "Sit down tall with your arms straight overhead.",
    ],
    "Single-Arm Lat Pulldown": [
        "Attach a single D-handle to the high pulley.",
        "Adjust the thigh pads and take the handle in one hand.",
        "Sit tall, arm straight overhead, free hand on your thigh.",
    ],
    "Kneeling Lat Pulldown": [
        "Set a bar on the high pulley and a mat in front of the stack.",
        "Kneel upright, hips over your knees, and grip the bar at shoulder-width.",
        "Squeeze your glutes and brace, arms straight overhead.",
    ],
    "Rope Lat Pulldown": [
        "Attach a rope to the high pulley and adjust the thigh pads.",
        "Hold each end of the rope, palms facing.",
        "Sit down tall with your arms straight overhead.",
    ],
    "Machine Lat Pulldown": [
        "Set the seat and thigh pad so the handles are just within reach.",
        "Sit tall and grip both handles.",
        "Start with your arms overhead, elbows slightly bent, shoulders down.",
    ],
    "Iso-Lateral Lat Pulldown": [
        "Set the seat and thigh pad so the handles are just within reach.",
        "Sit tall and grip both handles.",
        "Pull one handle at a time, the other held overhead.",
    ],
    "Wide-Grip Seated Cable Row": [
        "Set both pulleys at waist height and clip a handle to each.",
        "Sit with your feet on the footplate, knees soft.",
        "Grip the handles overhand, wide, and sit tall with your arms straight.",
    ],
    "Close-Grip Seated Cable Row": [
        "Set both pulleys at waist height and clip a handle to each.",
        "Sit with your feet on the footplate, knees soft.",
        "Hold the handles close together, palms facing, and sit tall with your arms straight.",
    ],
    "Single-Arm Cable Row": [
        "Attach a single handle to the low pulley.",
        "Sit with your feet on the footplate, knees soft.",
        "Take the handle in one hand and sit tall, arm straight.",
    ],
    "Standing Cable Row": [
        "Set both pulleys just below hip height and take a handle in each hand.",
        "Step back into a staggered stance until the cables are tight.",
        "Stand tall with soft knees, arms straight in front.",
    ],
    "Half-Kneeling Cable Row": [
        "Set a single handle at about hip height.",
        "Kneel on one knee, the other foot forward, facing the stack.",
        "Take the handle in one hand, arm straight, glutes squeezed.",
    ],
    "High Cable Row": [
        "Set both pulleys high and sit facing them on the bench.",
        "Take a handle in each hand, palms facing in.",
        "Sit tall with your arms reaching up and forward.",
    ],
    "Low Cable Row": [
        "Set both pulleys at the floor and sit facing them.",
        "Put your feet on the footplate, knees soft.",
        "Take a handle in each hand and sit tall, arms reaching down.",
    ],
    "Machine Seated Row": [
        "Set the seat so the handles are at mid-chest height.",
        "Sit with your chest against the pad, feet flat.",
        "Reach forward and take the handles with straight arms.",
    ],
    "Iso-Lateral Row Machine": [
        "Set the seat so the handles are at mid-chest height.",
        "Sit with your chest against the pad, feet flat.",
        "Take both handles; row one side at a time.",
    ],
    "Single-Arm Machine Row": [
        "Set the seat so the handle is at mid-chest height.",
        "Sit with your chest against the pad, feet flat.",
        "Take the handle in one hand and hold the support with the other.",
    ],
    "Reverse-Grip T-Bar Row": [
        "Wedge one end of a bar in a landmine and load the other end.",
        "Straddle the bar and set an underhand handle under it.",
        "Hinge forward with a flat back and grip the handle, arms straight.",
    ],
    "Dumbbell Pullover Row": [
        "Lie along a flat bench with a dumbbell in each hand.",
        "Hold them over your chest, palms facing, arms nearly straight.",
        "Plant your feet and keep a slight bend in your elbows.",
    ],
    "Machine Pullover": [
        "Set the seat so your shoulders line up with the machine's pivot.",
        "Sit with your back on the pad and fasten the belt if there is one.",
        "Place your upper arms on the pads and rest your hands on the bar.",
    ],
    # Batch 191-240 (2026-09-26): written to each model (see spec_191_240_*.py).
    "Seated Barbell Overhead Press": [
        "Sit on a bench with your torso upright and feet flat, wider than your hips.",
        "Take the bar in front of your chin, hands a hand's width outside your shoulders.",
        "Wrists straight, forearms vertical under the bar.",
        "Brace your core and sit tall.",
    ],
    "Behind-the-Neck Press": [
        "Set the bar in a rack at shoulder height.",
        "Grip it overhand, a hand's width outside your shoulders.",
        "Duck under, take it behind your neck on your upper traps and step back.",
        "Stand with your feet hip-width, glutes tight and core braced.",
    ],
    "Push Press": [
        "Hold the bar in front of your chin, hands a hand's width outside your shoulders.",
        "Stand with your feet hip-width, knees soft, weight over mid-foot.",
        "Wrists straight, forearms under the bar.",
        "Brace your core and squeeze your glutes.",
    ],
    "Dumbbell Push Press": [
        "Stand with your feet hip-width, a dumbbell in each hand.",
        "Hold the dumbbells just above your shoulders, palms forward.",
        "Elbows under your wrists, slightly in front of your body.",
        "Brace your core, weight over mid-foot.",
    ],
    "Standing Dumbbell Press": [
        "Stand with your feet hip-width and your knees soft.",
        "Hold the dumbbells just above your shoulders, palms forward.",
        "Elbows under your wrists, slightly in front of your body.",
        "Squeeze your glutes and brace your core.",
    ],
    "Seated Dumbbell Press": [
        "Sit tall in the middle of a low-backed seat.",
        "Plant your feet flat and wider than your hips.",
        "Kick the dumbbells up to shoulder height, palms forward.",
        "Elbows under your wrists, ribs down.",
    ],
    "Neutral-Grip Dumbbell Shoulder Press": [
        "Set the bench upright or one notch back and sit with your back on the pad.",
        "Plant your feet flat on the floor.",
        "Hold the dumbbells at the front of your shoulders, palms facing each other.",
        "Keep your elbows low and in front of your body.",
    ],
    "Single-Arm Dumbbell Shoulder Press": [
        "Stand with your feet hip-width and your knees soft.",
        "Hold one dumbbell just above your shoulder, palm forward.",
        "Rest your free hand on your hip.",
        "Brace your core and squeeze your glutes.",
    ],
    "Z Press": [
        "Sit on the floor with your legs straight and apart.",
        "Set the rack's safeties just below chin height and sit under the bar.",
        "Grip the bar a hand's width outside your shoulders, wrists straight.",
        "Sit tall on your sit bones and brace your core.",
    ],
    "Landmine Shoulder Press": [
        "Wedge one end of a bar in a landmine and load the other end.",
        "Stand at the loaded end facing the landmine, the foot opposite your pressing arm forward.",
        "Hold the end of the bar in front of your shoulder in one hand.",
        "Rest your free hand on your hip and brace your core.",
    ],
    "Half-Kneeling Landmine Press": [
        "Wedge one end of a bar in a landmine and load the other end.",
        "Kneel at the loaded end facing the landmine, pressing-side knee down, other foot flat ahead.",
        "Hold the end of the bar in front of your shoulder in one hand.",
        "Rest your free hand on your hip and squeeze the glute of the down leg.",
    ],
    "Cable Shoulder Press": [
        "Set both pulleys at the bottom and attach a handle to each.",
        "Stand centred between them, a small step in front.",
        "Bring the handles up to your shoulders, palms forward.",
        "Brace your core, knees soft.",
    ],
    "Single-Arm Cable Shoulder Press": [
        "Set one pulley at the bottom and attach a handle.",
        "Stand beside it, a small step in front, feet hip-width.",
        "Bring the handle to the near shoulder, palm forward.",
        "Let your free arm hang by your side and brace.",
    ],
    "Smith Machine Shoulder Press": [
        "Set a bench under the Smith bar with the back pad just short of upright.",
        "Place it so the bar runs just in front of your face.",
        "Sit with your back on the pad and your feet flat and wide.",
        "Grip the bar just outside your shoulders, then unhook it.",
    ],
    "Viking Press": [
        "Fit a Viking press handle to a landmine bar and load it.",
        "Stand facing the landmine, feet hip-width, knees straight.",
        "Hold both handles at the front of your shoulders, palms facing each other.",
        "Brace your core and squeeze your glutes.",
    ],
    "Leaning Lateral Raise": [
        "Stand side-on to a rack upright, about an arm's length away.",
        "Hold the upright at chest height with the near hand.",
        "Tilt your torso about 15° toward the rack, feet close together.",
        "Let the dumbbell hang in the far hand, palm facing in.",
    ],
    "Incline Lateral Raise": [
        "Set an incline bench to about 30°.",
        "Lie on your side against the backrest, bottom hip on the seat.",
        "Rest your bottom hand at the top of the backrest, bottom foot on the floor.",
        "Start with the dumbbell in front of your hip, palm facing in.",
    ],
    "Chest-Supported Lateral Raise": [
        "Set an incline bench to about 35°.",
        "Kneel on the seat and rest your chest on the pad.",
        "Let the dumbbells hang straight down, palms facing in.",
        "Keep your chin just over the top of the pad.",
    ],
    "Y-Raise": [
        "Set an incline bench to about 35°.",
        "Kneel on the seat and rest your chest on the pad.",
        "Let light dumbbells hang straight down, palms facing in.",
        "Keep your chin just over the top of the pad.",
    ],
    "Cable Y-Raise": [
        "Set both pulleys of a cable crossover at the bottom.",
        "Take the right pulley's handle in your left hand and the left one in your right.",
        "Stand between the pulleys facing the machine, feet hip-width.",
        "Lean forward slightly, hands in front of your hips.",
    ],
    "Lu Raise": [
        "Stand tall, feet hip-width, a light dumbbell in each hand.",
        "Let the arms hang at your sides, palms facing in.",
        "Keep a slight bend in the elbows.",
        "Brace your core and squeeze your glutes.",
    ],
    "Plate Front Raise": [
        "Stand with your feet hip-width apart, knees soft.",
        "Hold a plate at 3 and 9 o'clock, palms facing each other.",
        "Let it hang in front of your thighs, elbows slightly bent.",
        "Brace your core and set your shoulders down.",
    ],
    "Barbell Front Raise": [
        "Stand with your feet hip-width apart, knees soft.",
        "Hold the bar overhand, hands about shoulder-width.",
        "Let it rest against your thighs, arms long.",
        "Brace your core and set your shoulders down.",
    ],
    "Cable Front Raise": [
        "Attach a straight bar to a low pulley.",
        "Stand with your back to the stack, the cable between your feet.",
        "Hold the bar overhand, hands about shoulder-width.",
        "Lean slightly forward from the hips, arms long.",
    ],
    "Alternating Dumbbell Front Raise": [
        "Stand with a dumbbell in each hand in front of your thighs.",
        "Palms facing your body, elbows softly bent.",
        "Feet hip-width, core braced.",
        "Raise one arm at a time; the other rests at your thigh.",
    ],
    "Cable External Rotation": [
        "Set a single handle at elbow height.",
        "Stand side-on to the stack and take the handle in your far hand.",
        "Elbow bent to 90° against your side, forearm across your stomach.",
        "Rest your free hand on your hip.",
    ],
    "Cable Internal Rotation": [
        "Set a single handle at elbow height.",
        "Stand side-on to the stack and take the handle in your near hand.",
        "Elbow bent to 90° against your side, forearm pointing out.",
        "Rest your free hand on your hip.",
    ],
    "Powell Raise": [
        "Lie on one side along a flat bench, knees bent and stacked.",
        "Stretch your bottom arm out under your head.",
        "Hold the dumbbell with the arm angled down in front of your chest.",
        "Keep the elbow almost straight, palm facing your feet.",
    ],
    "Rear Delt Row": [
        "Hold a dumbbell in each hand with an overhand grip.",
        "Hinge forward from the hips, knees soft, back flat.",
        "Let the dumbbells hang under your shoulders.",
        "Turn the handles so they line up with your shoulders.",
    ],
    "Machine Rear Delt Row": [
        "Set the seat so the handles line up with your shoulders.",
        "Sit with your chest on the pad, feet flat on the floor.",
        "Take the wide handles with an overhand grip.",
        "Start with your arms reaching forward, elbows soft.",
    ],
    "Barbell Upright Row": [
        "Stand with your feet hip-width apart, knees soft.",
        "Hold the bar overhand, hands about shoulder-width.",
        "Let it hang at arm's length against your thighs.",
        "Brace your core and keep your chest up.",
    ],
    "Cable Upright Row": [
        "Attach a straight bar to a low pulley.",
        "Face the stack a short step away, feet hip-width.",
        "Hold the bar overhand, hands about shoulder-width.",
        "Stand tall, arms long, bar in front of your thighs.",
    ],
    "Smith Machine Upright Row": [
        "Set the Smith bar at the top of your thighs.",
        "Stand close, the bar just in front of your thighs.",
        "Grip it overhand, hands about shoulder-width.",
        "Unrack the bar and stand tall, arms long.",
    ],
    "Dumbbell Shrug": [
        "Stand tall with your feet hip-width, knees soft.",
        "Hold a dumbbell at each side, palms facing your thighs.",
        "Let your arms hang straight and your shoulders drop.",
    ],
    "Barbell Shrug": [
        "Stand with your feet hip-width, the bar in front of your thighs.",
        "Grip it overhand at about shoulder-width, thumbs around.",
        "Stand tall, arms straight, and let your shoulders drop.",
    ],
    "Smith Machine Shrug": [
        "Set the bar on the hooks at about mid-thigh height.",
        "Stand close, feet hip-width, the bar against your thighs.",
        "Grip it overhand at about shoulder-width.",
        "Twist the bar off the hooks and stand tall, arms straight.",
    ],
    "Cable Shrug": [
        "Set both pulleys at the bottom and take a handle in each hand.",
        "Stand centred between the stacks, feet hip-width, knees soft.",
        "Let the handles hang by your thighs, palms in, arms straight.",
    ],
    "Trap Bar Shrug": [
        "Stand in the centre of the trap bar, feet hip-width.",
        "Grip the middle of the side handles, palms in.",
        "Lift the bar with a flat back and stand tall, arms straight.",
    ],
    "Behind-the-Back Barbell Shrug": [
        "Set the bar in a rack just below hip height.",
        "Stand with your back to it and grip it overhand at about shoulder-width.",
        "Lift it off and step forward, the bar against the backs of your thighs.",
        "Stand tall, arms straight, and let your shoulders drop.",
    ],
    "Alternating Dumbbell Curl": [
        "Hold a dumbbell in each hand, palms facing your thighs.",
        "Stand tall, feet hip-width, arms straight by your sides.",
        "Shoulders down and back, elbows by your ribs.",
        "Curl one arm at a time, turning the palm up as it rises.",
    ],
    "Spider Curl": [
        "Set an incline bench to about 45°.",
        "Kneel on the seat, chest on the pad, shoulders just over the top.",
        "Take the barbell underhand, hands shoulder-width apart.",
        "Let your arms hang straight down.",
    ],
    "Dumbbell Preacher Curl": [
        "Set the seat so your armpit rests at the top of the pad.",
        "Hold a dumbbell in one hand, palm up.",
        "Lay the back of that arm flat on the pad, the other arm resting beside it.",
        "Sit tall, chest to the pad, feet flat.",
    ],
    "Machine Biceps Curl": [
        "Set the seat so your elbows line up with the machine's pivot.",
        "Sit with your chest to the pad, backs of the arms flat on it.",
        "Take the handles underhand, hands shoulder-width apart.",
        "Start with the arms almost straight.",
    ],
    "Farmer's Carry": [
        "Stand between two dumbbells, feet hip-width.",
        "Squat down with a flat back and grip them in the middle, palms in.",
        "Stand tall, shoulders back, arms straight at your sides.",
        "Walk with short, steady steps for the set time.",
    ],
    "Suitcase Carry": [
        "Stand beside one dumbbell, feet hip-width.",
        "Squat down with a flat back and grip it in one hand, palm in.",
        "Stand tall with the shoulders level, free arm relaxed.",
        "Walk with short, even steps for the set time; switch hands next set.",
    ],
    "Overhead Carry": [
        "Clean a dumbbell to each shoulder and press them overhead.",
        "Lock the elbows, palms forward, upper arms beside your ears.",
        "Brace with the ribs down and the glutes tight.",
        "Walk with short, steady steps for the set time.",
    ],
    # Legs 300-350 (2026-09-26): written to each model (see spec_300_350_*.py).
    "Forward Lunge": [
        "Stand tall with your feet hip-width apart.",
        "Rest your hands on your hips.",
        "Clear room in front of you for a long step.",
        "Brace your core before each step.",
    ],
    "Barbell Lunge": [
        "Set the bar in a rack just below shoulder height.",
        "Step under it and rest it on your upper traps, hands about a hand's width outside your shoulders.",
        "Stand up, step back and set your feet hip-width apart.",
        "Clear room in front of you for a long step.",
    ],
    "Smith Machine Reverse Lunge": [
        "Set the Smith bar just below shoulder height.",
        "Step under it and rest it on your upper traps, hands about a hand's width outside your shoulders.",
        "Stand with your feet hip-width, heels about half a foot's length in front of the bar.",
        "Turn the bar to unhook it and brace your core.",
    ],
    "Curtsy Lunge": [
        "Stand tall with your feet a little wider than hip-width.",
        "Clasp your hands in front of your chest, elbows out.",
        "Soften your knees and face straight ahead.",
        "Brace your core before each step.",
    ],
    "Barbell Split Squat": [
        "Set the bar in a rack at upper-chest height and take it high across your upper traps.",
        "Grip it wider than your shoulders and step back from the rack.",
        "Step one foot a long stride forward, feet hip-width apart.",
        "Rise onto the ball of the back foot and brace, chest tall.",
    ],
    "Dumbbell Split Squat": [
        "Hold a dumbbell in each hand at your sides, palms facing in.",
        "Step one foot a long stride forward, feet hip-width apart.",
        "Rise onto the ball of the back foot.",
        "Stand tall with your shoulders over your hips.",
    ],
    "Smith Machine Split Squat": [
        "Set the Smith bar at upper-chest height and step under it.",
        "Rest it high across your upper traps, hands wider than your shoulders.",
        "Split your feet a long stride apart, the bar over the middle of your stance.",
        "Rise onto the ball of the back foot, then turn the bar to unhook it.",
    ],
    "Front-Foot-Elevated Split Squat": [
        "Place a low step, about 10 cm high, in front of you.",
        "Hold a dumbbell in each hand at your sides, palms facing in.",
        "Put your whole front foot on the step, a long stride ahead of the back foot.",
        "Rise onto the ball of the back foot, feet hip-width apart.",
    ],
    "Rear-Foot-Elevated Split Squat": [
        "Hold a dumbbell in each hand at your sides, palms facing in.",
        "Stand a long stride in front of a knee-height bench.",
        "Reach one foot back and rest its laces on the bench.",
        "Set your front foot flat, hip-width from the back foot.",
    ],
    "Barbell Bulgarian Split Squat": [
        "Put a knee-height bench in a rack, safety bars just under the bar's lowest point.",
        "Take the bar high across your upper traps, hands wider than your shoulders.",
        "Stand a long stride in front of the bench and rest the laces of your back foot on it.",
        "Set your front foot flat, feet hip-width apart, and brace.",
    ],
    "Smith Machine Bulgarian Split Squat": [
        "Set the Smith bar at upper-chest height, a knee-height bench a short step behind it.",
        "Rest the bar high across your upper traps, hands wider than your shoulders.",
        "Stand a long stride in front of the bench and rest the laces of your back foot on it.",
        "Set your front foot flat, then turn the bar to unhook it.",
    ],
    # Late additions (2026-09-27): written to each model (see spec_0927_*.py).
    "Seated Dumbbell Lateral Raise": [
        "Sit tall on the end of a flat bench, feet flat and apart.",
        "Hold a dumbbell in each hand beside your thighs.",
        "Palms facing in, arms long by your sides.",
        "Brace your core and set your shoulders down.",
    ],
    "Cable Rear Delt Row": [
        "Set the pulley at seated shoulder height with a straight bar.",
        "Sit tall facing the stack, knees slightly bent, feet flat.",
        "Take the bar overhand, hands well outside your shoulders.",
        "Start with your arms reaching forward at shoulder height.",
    ],
    "Dumbbell Upright Row": [
        "Stand with your feet hip-width apart, knees soft.",
        "Hold the dumbbells overhand in front of your thighs.",
        "Handles across, hands about shoulder-width apart.",
        "Brace your core and keep your chest up.",
    ],
    "Barbell Hip Thrust": [
        "Sit on the floor with your upper back against the long side of a low bench, secured so it cannot slide.",
        "Roll a padded barbell over your thighs until it rests in the crease of your hips.",
        "Plant your feet flat, about shoulder-width apart and close enough that your shins will be vertical at the top, toes turned out a little.",
        "Lean back so the bench edge sits near the top of your shoulder blades and hold the bar either side of the pad.",
    ],
    # Batch 241-300 (2026-09-27): written to each model (see spec_241_300_*.py).
    "Single-Arm Machine Curl": [
        "Set the seat so your working elbow lines up with the pivot.",
        "Sit with your chest to the pad, the back of the working arm on it.",
        "Take the handle underhand in one hand; rest the other arm on the pad.",
        "Start with the working arm almost straight.",
    ],
    "Cable Preacher Curl": [
        "Set a preacher bench facing a low pulley, about a metre from it.",
        "Clip a straight bar to the cable.",
        "Sit with your armpits at the top of the pad, backs of the arms flat on it.",
        "Take the bar underhand, hands shoulder-width apart, arms almost straight.",
    ],
    "Single-Arm Cable Curl": [
        "Attach a D-handle to a pulley at the bottom of the column.",
        "Take it underhand in one hand and step back until the stack lifts.",
        "Stand tall, feet hip-width, the working arm straight by your side.",
        "Rest your free hand on your hip.",
    ],
    "High Cable Curl": [
        "Set both pulleys at about shoulder height, a D-handle on each.",
        "Stand centred between them, feet hip-width apart.",
        "Take a handle in each hand, palms up.",
        "Raise the arms out to the sides, level with the shoulders.",
    ],
    "Overhead Cable Curl": [
        "Attach a lat bar to the high pulley of a pulldown station.",
        "Take the bar underhand, hands about shoulder-width apart.",
        "Sit with your thighs under the pads, feet flat.",
        "Hold the bar with the arms almost straight, just in front of your head.",
    ],
    "Cable Hammer Curl": [
        "Attach a D-handle to each pulley at the bottom of the columns.",
        "Stand centred between them, a short step back, feet hip-width.",
        "Hold the handles with the palms facing in, arms by your sides.",
        "Stand tall with soft knees and the shoulders down.",
    ],
    "Preacher Hammer Curl": [
        "Set the seat so your armpit rests at the top of the pad.",
        "Hold a dumbbell in one hand, thumb up, palm facing in.",
        "Lay the back of that arm flat on the pad and grip the pad's far edge with the other hand.",
        "Sit tall, chest to the pad, feet flat.",
    ],
    "Drag Curl": [
        "Take a barbell underhand, hands shoulder-width apart.",
        "Stand tall, feet hip-width, the bar resting against the tops of the thighs.",
        "Set the shoulders down and back, elbows by your sides.",
        "Drag the bar up the body to the lower chest as the elbows travel back.",
    ],
    "EZ Bar Drag Curl": [
        "Take an EZ bar underhand on the outer angled grips.",
        "Stand tall, feet hip-width, the bar resting against the tops of the thighs.",
        "Set the shoulders down and back, elbows by your sides.",
        "Drag the bar up the body to the lower chest as the elbows travel back.",
    ],
    "Cable Drag Curl": [
        "Set the pulley at its lowest point and attach a straight bar.",
        "Face the stack close to the pulley and take the bar underhand, hands shoulder-width.",
        "Stand tall, feet hip-width, the bar against the tops of the thighs.",
        "Drag the bar up the body to the lower chest as the elbows travel back.",
    ],
    "Reverse Preacher Curl": [
        "Set the seat so your armpits rest at the top of the pad.",
        "Take an EZ bar overhand on its angled grips, hands shoulder-width apart.",
        "Lay the backs of your arms flat on the pad.",
        "Sit tall, chest to the pad, feet flat.",
    ],
    "Barbell Preacher Curl": [
        "Set the seat so your armpits rest at the top of the pad.",
        "Take the barbell underhand, hands shoulder-width apart.",
        "Lay the backs of your arms flat on the pad.",
        "Sit tall, chest to the pad, feet flat.",
    ],
    "Dumbbell Spider Curl": [
        "Set an incline bench to about 45°.",
        "Kneel on the seat, chest on the pad, shoulders just over the top.",
        "Take a dumbbell in each hand, palms facing forward.",
        "Let your arms hang straight down.",
    ],
    "EZ Bar Spider Curl": [
        "Set an incline bench to about 45°.",
        "Kneel on the seat, chest on the pad, shoulders just over the top.",
        "Take an EZ bar underhand on the outer angled grips.",
        "Let your arms hang straight down.",
    ],
    "Alternating Hammer Curl": [
        "Hold a dumbbell in each hand, palms facing in.",
        "Stand tall, feet hip-width, arms straight by your sides.",
        "Shoulders down and back, elbows by your ribs.",
        "Curl one arm at a time, thumb up, without twisting the wrist.",
    ],
    "Dumbbell Wrist Curl": [
        "Sit on the end of a flat bench, feet flat and about shoulder-width apart.",
        "Hold a dumbbell in each hand, palms up.",
        "Lean forward and rest your forearms along your thighs.",
        "Slide your forearms forward until your wrists just clear your knees.",
    ],
    "Barbell Reverse Wrist Curl": [
        "Sit on the end of a flat bench, feet flat and about shoulder-width apart.",
        "Take a light barbell overhand, hands shoulder-width or a little narrower.",
        "Lean forward and rest your forearms along your thighs, palms down.",
        "Slide your forearms forward until your wrists just clear your knees.",
    ],
    "Dumbbell Reverse Wrist Curl": [
        "Sit on the end of a flat bench, feet flat and about shoulder-width apart.",
        "Hold a light dumbbell in each hand, palms down.",
        "Lean forward and rest your forearms along your thighs.",
        "Slide your forearms forward until your wrists just clear your knees.",
    ],
    "Cable Wrist Curl": [
        "Attach a straight bar to a low pulley and sit on the end of a bench facing it, about a stride back.",
        "Take the bar underhand, hands shoulder-width or a little narrower.",
        "Lean forward and rest your forearms along your thighs, palms up.",
        "Slide your forearms forward until your wrists just clear your knees.",
    ],
    "Cable Reverse Wrist Curl": [
        "Attach a straight bar to a low pulley and sit on the end of a bench facing it, about a stride back.",
        "Take the bar overhand, hands shoulder-width or a little narrower.",
        "Lean forward and rest your forearms along your thighs, palms down.",
        "Slide your forearms forward until your wrists just clear your knees.",
    ],
    "Behind-the-Back Wrist Curl": [
        "Set a barbell in a rack just below hip height.",
        "Stand with your back to it and grip it at shoulder-width, palms facing back.",
        "Lift it off and step forward, the bar behind your thighs.",
        "Stand tall, arms straight, shoulders down.",
    ],
    "Finger Curl": [
        "Sit on the end of a flat bench, feet flat and about shoulder-width apart.",
        "Take a light barbell underhand, hands shoulder-width or a little narrower.",
        "Rest your forearms along your thighs, wrists just past your knees.",
        "Start with the bar curled up in your palms.",
    ],
    "Plate Pinch Hold": [
        "Stand a pair of equal plates on edge beside each foot, smooth sides out.",
        "Squat and pinch each pair at the top, fingers outside, thumb inside.",
        "Stand tall with the arms long, the plates at your sides.",
        "Pinch for the set time, about 30 seconds, then squat to set them down; keep your toes clear in case they slip.",
    ],
    "Dumbbell Static Hold": [
        "Stand between two heavy dumbbells, feet hip-width apart.",
        "Squat down with a flat back and grip each handle in the middle.",
        "Stand tall, arms straight at your sides, palms facing in.",
        "Hold for the set time, about 30 seconds with a weight that is hard to hold by the end, then squat to set them down.",
    ],
    "Barbell Static Hold": [
        "Set the bar in a rack just above knee height.",
        "Grip it overhand, hands about shoulder-width, just outside the thighs.",
        "Stand up with it: knees soft, hips straight, back tall.",
        "Hold for the set time, about 30 seconds with a weight that is hard to hold by the end, then set it back in the rack.",
    ],
    "Towel Grip Hold": [
        "Hang a sturdy towel over the bar on each side, a little wider than your shoulders.",
        "Grip both ends of each towel in one hand, hands level, and let them take some weight to check they do not slide.",
        "Bend the knees to lift the feet and hang with the arms long.",
        "Hold for the set time, about 20 seconds to start, then put the feet down.",
    ],
    # 30-leg set 02-27 (2026-09-28)
    "Lateral Lunge": [
        "Stand tall with your feet about hip-width apart, toes pointing ahead.",
        "Clasp your hands in front of your chest.",
        "Brace your core and settle your weight into your heels.",
        "Keep both feet pointing ahead; each rep steps one foot wide to the side and back.",
    ],
    "Cossack Squat": [
        "Stand with your feet about twice shoulder-width apart.",
        "Turn your toes out slightly.",
        "Clasp your hands in front of your chest.",
        "Brace your core, chest up, before shifting to one side.",
    ],
    "Dumbbell Sumo Squat": [
        "Stand with your feet well wider than your shoulders, toes turned out.",
        "Hold one dumbbell upright by its top end with both hands.",
        "Let it hang at arm's length between your legs.",
        "Brace your core and lift your chest.",
    ],
    "Barbell Sumo Squat": [
        "Set the bar in a rack at upper-chest height, safety bars just below your bottom position.",
        "Take it high across your upper traps, hands wider than your shoulders.",
        "Step back and set your feet well wider than your shoulders, toes turned out.",
        "Brace your core and lift your chest.",
    ],
    "Kettlebell Goblet Squat": [
        "Hold a kettlebell by the sides of the handle, bell down, against your chest.",
        "Stand with your feet about shoulder-width apart, toes turned out slightly.",
        "Tuck your elbows in under the kettlebell.",
        "Brace your core and stand tall.",
    ],
    "Box Squat": [
        "Set a box a short step behind where you will stand after walking the bar out, at a height that puts your thighs about parallel when seated.",
        "Take the bar high across your upper traps, hands wider than your shoulders.",
        "Step back until the box is a short step behind your heels.",
        "Set your feet a little wider than your shoulders, toes turned out, and brace.",
    ],
    "Pause Squat": [
        "Set the rack's safety bars just below the depth you will pause at.",
        "Take the bar high across your upper traps, hands wider than your shoulders.",
        "Step back and set your feet about shoulder-width, toes turned slightly out.",
        "Take a big breath and brace before each rep.",
    ],
    "Safety Bar Squat": [
        "Set the safety bar in a rack at about shoulder height.",
        "Step under it so the padded yoke rests across your upper back and shoulders.",
        "Take a handle in each hand in front of you and stand up to lift it off.",
        "Step back and set your feet about shoulder-width, toes turned slightly out.",
    ],
    "Zercher Squat": [
        "Set the bar in a rack just below elbow height.",
        "Hook the bar into the crooks of your elbows and clasp your hands in front of your chest.",
        "Stand up to lift it off, step back and set your feet about shoulder-width, toes slightly out.",
        "Wrap the bar in a towel or pad if it digs into your elbows.",
    ],
    "Overhead Squat": [
        "Learn it with an empty bar or a dowel before adding weight.",
        "Set your feet about shoulder-width, toes turned slightly out.",
        "Take a grip well wider than your shoulders and press the bar overhead.",
        "Lock your elbows with the bar over your ankles, slightly behind your head, and brace.",
    ],
    "Landmine Squat": [
        "Set one end of a barbell in a landmine or a corner and load the other end.",
        "Lift the loaded end (or a handle attachment on it) and hold it with both hands in front of your chest, at chest height.",
        "Stand facing the anchor, feet about shoulder-width, toes turned slightly out.",
        "Stand tall and brace before each rep.",
    ],
    "Belt Squat": [
        "Fasten the belt around your hips and step onto the platform.",
        "Clip the cable to the front of the belt.",
        "Set your feet shoulder-width, either side of the cable, ankles in line with where it runs down.",
        "Rest your hands on the handles and stand tall to lift the weight.",
    ],
    "Pendulum Squat": [
        "Stand on the plate with your back against the pad and your shoulders under the pads.",
        "Set your feet about shoulder-width in the middle of the plate, toes out a little.",
        "Hold the handles and stand tall to lift the carriage.",
        "Release the safety stop and brace.",
    ],
    "V-Squat": [
        "Stand on the plate with your back against the pad and your shoulders under the pads.",
        "Set your feet about shoulder-width, well ahead of your hips, toes out a little.",
        "Hold the handles and stand tall to lift the carriage.",
        "Release the safety stop and brace.",
    ],
    "Vertical Leg Press": [
        "Lie on the back pad with your hips on the seat, right under the sled.",
        "Set the safety stops just below the lowest point you plan to reach.",
        "Place your feet flat on the plate, shoulder-width apart, above your hips.",
        "Press the sled up, release the sled's catch and hold the handles at your sides.",
    ],
    "45-Degree Leg Press": [
        "Set the back pad so you can reach about 90 degrees at the knee without your hips lifting.",
        "Sit with your back and hips flat against the pad.",
        "Place your feet shoulder-width apart in the middle of the platform.",
        "Press the platform up, release the safety handles and hold the side handles.",
    ],
    "Single-Leg Press": [
        "Set a load you can control on one leg.",
        "Sit with your back and hips flat against the pad.",
        "Place one foot flat in the middle of the platform, where it sits in your two-leg stance.",
        "Rest the other foot on the side foot rest or the floor.",
        "Press the platform up, release the safety handles and hold the side handles.",
    ],
    "Narrow-Stance Leg Press": [
        "Set the back pad so you can reach about 90 degrees at the knee without your hips lifting.",
        "Sit with your back and hips flat against the pad.",
        "Place your feet hip-width apart in the middle of the platform.",
        "Press the platform up, release the safety handles and hold the side handles.",
    ],
    "Wide-Stance Leg Press": [
        "Set the back pad so you can reach about 90 degrees at the knee without your hips lifting.",
        "Sit with your back and hips flat against the pad.",
        "Place your feet wider than your shoulders in the middle of the platform, toes turned out a little.",
        "Press the platform up, release the safety handles and hold the side handles.",
    ],
    "Heel-Elevated Squat": [
        "Set two heel wedges, or a slant board, in front of a squat rack.",
        "Take the bar high across your upper traps, hands wider than your shoulders, and step back.",
        "Stand with your heels on the high end of the wedges, feet about shoulder-width, toes slightly out.",
        "Brace, chest tall, before the first rep.",
    ],
    "Cyclist Squat": [
        "Set a heel wedge or slant board in front of a squat rack.",
        "Take the bar high across your upper traps, hands wider than your shoulders, and step back.",
        "Stand with your heels on the high end of the wedge, feet hip-width or closer, toes nearly straight.",
        "Brace, chest tall, before the first rep.",
    ],
    "Pistol Squat": [
        "Stand on one foot, the whole foot flat, toes pointing forward.",
        "Lift the other leg straight out in front, heel just off the floor.",
        "Reach both arms straight out in front, just below shoulder height.",
        "Brace your trunk before you start down.",
    ],
    "Assisted Pistol Squat": [
        "Face a fixed bar or handle at about chest height.",
        "Hold it with both hands and stand on one foot a little less than arm's length from it, elbows bent.",
        "Lift the other leg straight out in front, heel just off the floor.",
        "Brace your trunk before you start down.",
    ],
    "Standing Calf Raise": [
        "Set the shoulder pads so they sit on your shoulders with your heels down.",
        "Step onto the block with the balls of your feet on its edge, heels off.",
        "Set your feet hip-width apart, toes forward, and hold the handles.",
        "Stand up tall under the pads, knees straight but soft.",
    ],
    "Seated Calf Raise": [
        "Sit on the seat with the balls of your feet on the edge of the platform, heels off.",
        "Set the pad on your lower thighs, just above the knees, knees at about 90°.",
        "Hold the handles, rise onto your toes a little and release the safety catch.",
        "Sit tall with your trunk still.",
    ],
    "Leg Press Calf Raise": [
        "Sit with your back flat on the pad and hold the handles beside the seat.",
        "Put the balls of your feet on the lower edge of the platform, hip-width apart, heels off.",
        "Press the sled up until your knees are nearly straight, then release the safety stops.",
        "Keep a slight bend in your knees; if your feet start to slip, re-engage the stops before you reset them.",
    ],
    "Single-Leg Calf Raise": [
        "Stand on a sturdy step beside a support, a dumbbell in the hand on the working side.",
        "Put the ball of the working foot on the edge of the step, heel off.",
        "Hold the support lightly with your free hand for balance.",
        "Bend the other knee to lift that foot behind you and stand tall over the working foot.",
    ],
    "Smith Machine Calf Raise": [
        "Set the bar at upper-chest height with a calf block under it.",
        "Step under the bar, rest it on your upper traps and grip it just outside your shoulders.",
        "Put the balls of your feet on the edge of the block, heels off, hip-width apart.",
        "Stand up tall, turn the bar to unhook it and keep the knees straight but soft.",
    ],
    # Exercises 1-50 redone (2026-09-29)
    "Dumbbell Curl": [
        "Hold a dumbbell in each hand, palms facing forward.",
        "Stand tall, feet hip-width, arms straight by your sides.",
        "Draw your shoulders down and back, elbows by your ribs.",
        "Curl both dumbbells together, palms turned up.",
    ],
    "Incline Dumbbell Curl": [
        "Set the back pad of an incline bench to about 65°.",
        "Sit back, back and shoulders on the pad, feet flat.",
        "Hold a dumbbell in each hand, palms facing forward.",
        "Let your arms hang straight down, behind your body.",
    ],
    "Preacher Curl": [
        "Set the seat so your armpits sit just over the arm pads.",
        "Take an EZ bar underhand on its angled grips, about shoulder-width.",
        "Rest the backs of your upper arms on the pads, arms almost straight.",
        "Sit tall with both feet flat.",
    ],
    "Cable Curl": [
        "Attach a D-handle to the low pulley of each of two columns.",
        "Take a handle in each hand, palms facing forward.",
        "Step back about a metre until both stacks lift.",
        "Stand tall, feet hip-width, arms almost straight, leaning back slightly.",
    ],
    "Bayesian Cable Curl": [
        "Attach a D-handle to the low pulley and stand with your back to it.",
        "Take the handle in one hand, palm facing forward.",
        "Step forward until the arm is drawn back behind you and the stack lifts.",
        "Stand tall, feet hip-width, the free arm at your side.",
    ],
    "Reverse Curl": [
        "Take an EZ bar overhand, hands about shoulder-width apart.",
        "Stand tall, feet about hip-width apart, the bar at your thighs.",
        "Arms almost straight, elbows by your sides, wrists straight.",
    ],
    "Wrist Curl": [
        "Choose a seat that lets your forearms lie level on the pad, elbows at about 90°.",
        "Sit with your feet flat and knees under the pad, and lean in over it.",
        "Hold a dumbbell in each hand, palms up.",
        "Rest your forearms along the pad, wrists just past its front edge.",
    ],
    "Pendlay Row": [
        "Stand with your feet about hip-width apart, the bar on the floor in front of your toes.",
        "Bend your knees well and push your hips back until your back is close to level.",
        "Grip the bar overhand, hands a little wider than your shoulders.",
        "Brace with a flat back and your shoulders held back, arms reaching down to the bar.",
    ],
    "Close-Grip Bench Press": [
        "Lie on a flat bench with your head, upper back and hips on the pad.",
        "Plant your feet flat on the floor, set wider than your shoulders.",
        "Grip the bar overhand with your hands about shoulder-width apart.",
        "Pull your shoulder blades back and down, then hold the bar over your shoulders.",
    ],
    # BEGIN Redone 190-280 (2026-09-30)
    "Machine Preacher Curl": [
        "Set the seat so your elbows sit level with the pivots on each side.",
        "Sit with your chest to the pad and your armpits over its top edge.",
        "Rest the backs of your upper arms on the pad's slope.",
        "Take the straight handle underhand, hands in front of your shoulders.",
        "Start with your arms almost straight.",
    ],
    # END Redone 190-280 (2026-09-30)
    # BEGIN 351-400 (2026-09-30)
    "Single-Leg Romanian Deadlift": [
        "Stand on your left foot, the whole foot flat and the knee slightly bent, as the model does.",
        "Rest the right toes lightly on the floor just behind you.",
        "Let both arms hang straight down, palms facing in.",
        "Brace your trunk, hinge for all your reps, then switch to the right leg.",
    ],
    "Barbell Single-Leg Romanian Deadlift": [
        "Take a light barbell from a rack at hip height, overhand, hands about shoulder-width.",
        "Step back and stand on your left foot, knee slightly bent, as the model does.",
        "Rest the right toes lightly on the floor just behind you, the bar against your thighs.",
        "Brace, hinge for all your reps, then switch to the right leg.",
    ],
    "Dumbbell Single-Leg Romanian Deadlift": [
        "Hold a dumbbell in each hand at your sides, palms facing in.",
        "Stand on your left foot, knee slightly bent, as the model does.",
        "Rest the right toes lightly on the floor just behind you.",
        "Brace, hinge for all your reps, then switch to the right leg.",
    ],
    "B-Stance Romanian Deadlift": [
        "Hold a dumbbell in each hand at your sides, palms facing in.",
        "Stand on your left foot and step the right foot back so its toes are level with your left heel, as the model does.",
        "Lift the right heel and keep most of your weight on the left foot, knee slightly bent.",
        "Brace, do all your reps, then switch the feet.",
    ],
    "Smith Machine Romanian Deadlift": [
        "Set the bar on the hooks just below hip height and the safety stops below the lowest point of your rep.",
        "Stand under the bar, feet hip-width, so it hangs over the middle of your feet.",
        "Grip it overhand just outside your thighs and stand tall with the knees soft.",
        "Brace and twist the bar off the hooks.",
    ],
    "Cable Romanian Deadlift": [
        "Set the pulley at its lowest point and clip on a straight bar.",
        "Face the machine and take the bar overhand, hands just outside your thighs.",
        "Walk back about a metre from the pulley, feet hip-width, until the stack lifts clear.",
        "Stand tall with the knees soft, shoulders back, and brace.",
    ],
    "Kettlebell Romanian Deadlift": [
        "Stand with your feet hip-width, the kettlebell on the floor between them.",
        "Squat down, grip the handle overhand with both hands and stand up with it.",
        "Let the bell hang in front of your thighs, arms long, knees soft.",
        "Brace and pull the shoulders back before the first rep.",
    ],
    "Dumbbell Deadlift": [
        "Stand with your feet about hip-width, toes forward, a dumbbell beside each foot.",
        "Push the hips back, bend the knees and grip the dumbbells with the palms facing in.",
        "Chest up, back flat, shoulders over the dumbbells.",
        "Brace and stand up with them to begin.",
    ],
    "Good Morning": [
        "Set the bar in a rack at about shoulder height.",
        "Step under it and rest it high across your upper traps, hands well outside your shoulders.",
        "Lift it off, step back and set your feet about hip-width, toes nearly straight ahead.",
        "Unlock your knees slightly and brace before the first rep.",
    ],
    "Seated Good Morning": [
        "Set a flat bench lengthwise in a rack, with the bar at a height you can take it from while seated.",
        "Straddle the end of the bench with your feet flat, wider than your shoulders.",
        "Take the bar high across your upper traps, hands wide, and lift it off the hooks.",
        "Sit tall, set a slight arch in your lower back and brace before each rep.",
    ],
    "Smith Machine Good Morning": [
        "Set the Smith bar hooks just below shoulder height and the safety stops just below the lowest point of your rep.",
        "Step under the bar and rest it high across your upper traps, hands well outside your shoulders.",
        "Set your feet hip-width, back under the bar so it sits over the balls of your feet, toes straight ahead.",
        "Unlock your knees, brace and turn the bar off the hooks.",
    ],
    "Nordic Hamstring Curl": [
        "Kneel on a thick pad with your knees about hip-width apart.",
        "Hook your ankles under the padded anchor, or have a partner hold your lower calves down.",
        "Kneel tall with your hips straight and your hands loose in front of your chest.",
        "Squeeze your glutes and brace before each rep.",
    ],
    "Assisted Nordic Curl": [
        "Set the band's anchor behind you, a little higher than your chest when you kneel tall.",
        "Kneel on the pad and hook your ankles under the padded roller.",
        "Loop the band around your chest, high under your armpits.",
        "Kneel tall with your hips straight and your hands loose in front of your chest.",
    ],
    "Glute-Ham Raise": [
        "Set the footplate so your knees sit just behind the pad when your feet are against the plate.",
        "Step onto the plate and lock your ankles between the rollers.",
        "Rest your lower thighs on the pad and kneel up tall, hips straight, hands in front of your chest.",
        "Press the balls of your feet into the plate and brace before each rep.",
    ],
    "Standing Leg Curl": [
        "Set the roller so it sits just above your left heel.",
        "Stand on the platform on your right foot, left knee level with the pivot.",
        "Rest your chest on the pad and your forearms on the arm pads.",
        "Hold the handles and let the left leg hang almost straight.",
    ],
    "Kneeling Leg Curl": [
        "Set the roller low on the left leg, just above the heel.",
        "Kneel with your right knee on the pad and your left knee level with the pivot.",
        "Rest your forearms on the arm pads and hold the handles.",
        "Lean well forward over the pads; the left leg starts almost straight.",
    ],
    "Cable Standing Leg Curl": [
        "Strap the cuff round your left ankle and clip it to the low pulley.",
        "Face the stack and hold the frame handles in front of you.",
        "Stand on your right foot, knee soft, the left foot hanging just behind it.",
        "Start with the left knee a little bent and the cable taut.",
    ],
    "Swiss Ball Leg Curl": [
        "Lie on your back with your heels on top of the ball, hip-width apart.",
        "Lay your arms on the floor a little out from your sides, palms down.",
        "Lift your hips off the floor into a bridge, legs almost straight.",
    ],
    "Sliding Leg Curl": [
        "Lie on your back with both heels on sliders, legs almost straight.",
        "Rest your arms on the floor out to your sides, palms down.",
        "Press your heels down, toes pointing up.",
    ],
    "Single-Leg Sliding Curl": [
        "Lie on your back with your left heel on a slider, leg almost straight.",
        "Lift your right foot off the floor and hold the knee bent, thigh angled up.",
        "Spread your arms wide on the floor, palms down.",
    ],
    "Frog Pump": [
        "Lie on your back on a mat, arms resting on the floor out to your sides, palms down.",
        "Press the soles of your feet together and let your knees fall open to the sides.",
        "Draw your heels in toward your hips, the feet resting on their outer edges.",
        "Flatten your lower back into the mat and tuck your chin slightly before the first rep.",
    ],
    "Weighted Frog Pump": [
        "Lie on your back on a mat and set a dumbbell across your hips, holding it at both ends.",
        "Press the soles of your feet together and let your knees fall open to the sides.",
        "Draw your heels in toward your hips, the feet resting on their outer edges.",
        "Brace with your ribs down and your lower back flat before the first rep.",
    ],
    "Cable Hip Adduction": [
        "Attach an ankle cuff to a low pulley and strap it around the ankle nearest the stack.",
        "Stand side-on to the stack, far enough away that the cable draws the cuffed leg out to the side.",
        "Hold the support post or the machine frame with the hand nearest the stack.",
        "Stand tall on your right leg, knee slightly soft; the left leg, nearest the stack, works in this demo.",
    ],
    "Standing Hip Abduction": [
        "Stand facing two support rails and rest a hand on each handle at lower-chest height.",
        "Stand tall with your feet under your hips, knees and toes pointing forward.",
        "Shift your weight onto your right leg, knee slightly soft; the left leg lifts in this demo.",
        "Level your hips and brace your trunk before the first lift.",
    ],
    "Side-Lying Hip Abduction": [
        "Lie on your right side on a mat, legs straight and stacked in line with your body.",
        "Stack your hips and shoulders one above the other and keep your head in line with your spine.",
        "Rest your hands on the floor in front of your chest for balance.",
        "Point the toes of the top leg forward; the top leg lifts in this demo.",
    ],
    "Banded Hip Abduction": [
        "Loop a mini band around both thighs just above the knees.",
        "Sit tall on a flat bench with your feet flat under your knees, about shoulder-width apart.",
        "Rest your hands on the bench beside your hips.",
        "Let the knees come in until the band is just taut before the first rep.",
    ],
    "Clamshell": [
        "Lie on your right side on a mat with your hips bent to about 45 to 60 degrees and your knees bent.",
        "Stack your feet, knees and hips, the feet in line with your hips.",
        "Fold your lower arm under your head and rest your top hand on the floor in front of you.",
        "Brace your trunk before the first rep; the top knee opens in this demo.",
    ],
    # END 351-400 (2026-09-30)
}
