# Trainer content for the Abs batch (2026-09-24), models 088-099 from
# SourceExports/Abdoment. Same format as spec.py; generate with `spec` swapped
# for this module (see README). The lying, kneeling and hanging lifts are seen
# from the lifter's LEFT, so cues track _L joints; the side plank rests on the
# LEFT forearm and is seen from the front.
#
# Sources:
# - Escamilla RF et al. 2006, Phys Ther 86(5):656-671 — roll-out and hanging
#   knee-up gave the highest rectus abdominis and oblique activity, and also
#   high rectus femoris (hip flexor) activity; lumbar paraspinals stayed low.
# - Escamilla RF et al. 2010, JOSPT 40(5):265-276 — roll-out and pike were the
#   most effective at activating rectus abdominis, obliques and latissimus
#   while keeping rectus femoris and lumbar paraspinals low.
# - ACE-sponsored study (Francis, San Diego State Univ., 2001) — captain's
#   chair ranked 1st for obliques and 2nd for rectus abdominis of 13 exercises;
#   reverse crunch 3rd for obliques.
# - Youdas JW et al. 2008, J Strength Cond Res 22(6):1939-1946 — crunch, side
#   bridge and roll-out type exercises compared for abdominal vs rectus femoris
#   activity.
# - McGill SM et al. 1996, Clin Biomech (quadratus lumborum ~54% MVC in the
#   horizontal side support); McGill 2010, Strength Cond J 32(3):33-46 — the
#   core's job is often to stiffen and resist motion; side bridge as a
#   high-activation, low-spine-load exercise.
# - Youdas JW et al. 2014, Sports Health 6(5):416-421 — side bridge activates
#   the obliques, gluteus medius and trunk extensors.

P, S = "primary", "secondary"
HI, MOD = "HIGH ACTIVATION", "MODERATE ACTIVATION"
A, SOFT = "activation", "activationSoft"

SPEC = []

def ex(**kw):
    SPEC.append(kw)

# Lying, kneeling-prone and seated bodies fill the middle band of the frame,
# so their labels sit above and below it (see spec_legs2.FLAT).
FLAT = [0.15, 0.28, 0.63, 0.75, 0.87]
CORE_GLOWS = [(A, 0.55, 0.12, 0.10, 0.50, 0.50), (SOFT, 0.30, 0.10, 0.08, 0.50, 0.42)]

# ---------------------------------------------------------------- Crunches

ex(name="Crunch", var="crunch", group="core", slots=FLAT,
   annotations=[
       ("curl", "Curl ribs toward the pelvis", "chest"),
       ("neck", "Hands support, don't pull", "hand_L"),
       ("low", "Lower back stays down", "pelvis"),
       ("feet", "Feet flat, knees bent", "foot_L"),
       ("range", "Shoulder blades just off", "scapula_L"),
   ],
   cues={
       "curl": ("Spinal Flexion",
                "A crunch is a curl of the spine, not a sit-up.",
                "The rectus abdominis flexes the trunk by pulling the ribs toward the pelvis, so a short curl works it without handing the job to the hip flexors.",
                "Sitting all the way up, which turns the second half of the rep into a hip-flexor exercise.",
                "Curl the upper back off the floor as if closing the gap between ribs and hips, then lower slowly."),
       "neck": ("Hand Position",
                "The hands only cradle the head.",
                "Pulling on the head flexes the neck instead of the trunk and loads the cervical spine.",
                "Yanking the head forward with the hands, chin jammed into the chest.",
                "Rest the fingertips behind the ears, elbows wide, and keep a fist's space between chin and chest."),
       "low": ("Lower Back",
               "The lower back stays in contact with the floor.",
               "Keeping the pelvis still keeps the movement in the trunk, where the abdominals work.",
               "Arching the lower back or lifting the hips to gain momentum.",
               "Keep the lower back and hips resting on the mat for every rep."),
       "feet": ("Leg Position",
                "Bent knees take the hip flexors out of it.",
                "With the knees bent and feet flat, the hip flexors are slack and cannot pull the trunk up for the abs.",
                "Hooking the feet under something, which lets the hip flexors turn it into a sit-up.",
                "Bend the knees to about 90° with the feet flat and free."),
       "range": ("Range of Motion",
                 "A short range is enough.",
                 "The abdominals do most of their work in the first 30° of trunk flexion; past the point where the shoulder blades leave the floor, the hip flexors take over.",
                 "Chasing a bigger range by swinging the arms or sitting up.",
                 "Lift until the shoulder blades clear the floor, pause, and lower under control."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.80), ("Obliques", S, MOD, 0.45)],
   stabilisers=["transverse abdominis", "neck flexors"],
   comparison=("PULLING ON THE NECK", "Ribs curl toward the hips", "Hands pull the head forward",
               "Curling from the trunk keeps the rectus abdominis doing the lifting.",
               "Pulling the head forward flexes the neck instead of the trunk, so the abs do less and the neck takes the strain."),
   glows=CORE_GLOWS)

ex(name="Reverse Crunch", var="reverseCrunch", group="core", slots=FLAT,
   annotations=[
       ("pelvis", "Curl the hips off the floor", "pelvis"),
       ("knees", "Knees stay bent ~90°", "patella_L"),
       ("control", "Lower slowly, no swing", "foot_L"),
       ("arms", "Arms flat for balance", "hand_L"),
       ("upper", "Upper back stays down", "chest"),
   ],
   cues={
       "pelvis": ("Pelvic Curl",
                  "The work is in rolling the pelvis up, not moving the legs.",
                  "Curling the pelvis toward the ribs flexes the lumbar spine from below, which is how the reverse crunch works the rectus abdominis and obliques.",
                  "Swinging the knees toward the chest without the hips ever leaving the floor.",
                  "Tilt the pelvis back and peel the hips off the mat, as if pouring the knees toward your face."),
       "knees": ("Knee Angle",
                 "Keep the legs as a fixed lever.",
                 "A fixed 90° knee keeps the load short and steady, so the abs, not the hip flexors, set the pace.",
                 "Straightening and bending the legs to kick the hips up.",
                 "Hold the knees bent at about 90° from the first rep to the last."),
       "control": ("Tempo",
                   "The way down counts as much as the way up.",
                   "Lowering slowly keeps tension on the abdominals and stops momentum doing the next rep.",
                   "Dropping the hips and bouncing into the next rep.",
                   "Take about two seconds to lower the hips back to the mat."),
       "arms": ("Arm Position",
                "The arms steady the body.",
                "Arms flat on the floor give a wide base so the pelvis can curl without rolling.",
                "Pushing hard through the hands to throw the hips up.",
                "Rest the arms beside you, palms down, and keep them relaxed."),
       "upper": ("Upper Body",
                 "The upper back stays on the mat.",
                 "Keeping the shoulders down isolates the curl to the lower end of the trunk.",
                 "Lifting the head and shoulders to help the legs up.",
                 "Rest the head and shoulders on the mat for the whole set."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.82), ("Obliques", S, MOD, 0.58), ("Hip Flexors", S, MOD, 0.42)],
   stabilisers=["transverse abdominis"],
   comparison=("SWINGING THE LEGS", "Pelvis curls off the mat", "Legs swing, hips stay down",
               "Curling the pelvis up makes the abdominals flex the spine from below.",
               "Swinging the legs moves them with the hip flexors and momentum while the abs barely work."),
   glows=CORE_GLOWS)

ex(name="Decline Crunch", var="declineCrunch", group="core", slots=FLAT,
   annotations=[
       ("curl", "Curl, don't sit up", "chest"),
       ("feet", "Feet locked under the pads", "foot_L"),
       ("neck", "Hands support the head", "hand_L"),
       ("low", "Lower back stays on the bench", "pelvis"),
       ("control", "Lower slowly", "scapula_L"),
   ],
   cues={
       "curl": ("Spinal Flexion",
                "The decline makes the crunch harder, not longer.",
                "Lying head-down increases the load on the rectus abdominis through the same short curl as a floor crunch.",
                "Coming all the way up to the knees, which turns it into a hip-flexor-driven sit-up.",
                "Curl the ribs toward the hips until the shoulder blades clear the bench, then lower."),
       "feet": ("Anchor",
                "The foot pads hold you on the bench.",
                "Hooked feet keep you from sliding, but pulling with them lets the hip flexors lift the trunk.",
                "Pulling hard against the pads to yank the body up.",
                "Hook the ankles under the pads and keep the legs relaxed."),
       "neck": ("Hand Position",
                "Cradle the head, never pull it.",
                "Pulling on the head flexes the neck instead of the trunk.",
                "Jerking the head forward with the hands.",
                "Fingertips behind the ears or arms crossed on the chest, chin off the chest."),
       "low": ("Lower Back",
               "The curl comes from above the pelvis.",
               "Keeping the lower back on the bench keeps the hips out of the movement.",
               "Lifting the whole back off the bench in one piece.",
               "Keep the lower back pressed to the bench as the upper back curls."),
       "control": ("Tempo",
                   "Gravity pulls harder on a decline.",
                   "Controlling the way down keeps the abdominals loaded and protects the lower back.",
                   "Falling back onto the bench between reps.",
                   "Lower over about two seconds and start the next rep without bouncing."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.84), ("Obliques", S, MOD, 0.48), ("Hip Flexors", S, MOD, 0.40)],
   stabilisers=["transverse abdominis", "quadriceps"],
   comparison=("FULL SIT-UP", "Short curl, back on the bench", "Sitting all the way up",
               "A short curl keeps the extra load of the decline on the abdominals.",
               "Sitting all the way up lets the hip flexors pull the trunk and adds compressive load on the lower back."),
   glows=CORE_GLOWS)

ex(name="Cable Crunch", var="cableCrunch", group="core",
   annotations=[
       ("rope", "Rope fixed beside the head", "hand_L"),
       ("curl", "Curl elbows toward the thighs", "chest"),
       ("hips", "Hips stay high and still", "pelvis"),
       ("knees", "Kneel on a mat", "patella_L"),
       ("feet", "Feet relaxed behind", "foot_L"),
   ],
   cues={
       "rope": ("Rope Position",
                "The arms only hold the rope.",
                "Holding the rope fixed beside the head makes the trunk move the load, not the arms.",
                "Pulling the rope down with the arms and shoulders.",
                "Hold the rope ends beside the ears and keep them there for the whole rep."),
       "curl": ("Spinal Flexion",
                "Round the spine; don't hinge at the hips.",
                "Curling the ribs toward the pelvis loads the rectus abdominis through spinal flexion, the movement it actually produces.",
                "Bowing forward from the hips with a flat back, which only moves the weight with body weight.",
                "Exhale and curl the chest down toward the thighs, rounding the upper and mid back."),
       "hips": ("Hip Position",
                "The hips stay put.",
                "Fixed hips stop you from sitting back onto the heels to drag the weight down.",
                "Sitting the hips back toward the heels as the weight comes down.",
                "Keep the hips stacked over the knees throughout."),
       "knees": ("Kneeling Base",
                 "A stable base lets you load the abs.",
                 "Kneeling on a mat a short distance from the stack keeps the cable pulling straight down through the rope.",
                 "Kneeling so far back that the cable pulls you forward off balance.",
                 "Kneel on a mat about an arm's length from the stack, knees hip-width."),
       "feet": ("Lower Legs",
                "The lower legs just rest.",
                "Relaxed lower legs keep the body still so only the spine moves.",
                "Pushing up onto the toes to lever the body down.",
                "Rest the tops of the feet on the floor behind you."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.86), ("Obliques", S, MOD, 0.52)],
   stabilisers=["latissimus dorsi", "transverse abdominis"],
   comparison=("HINGING AT THE HIPS", "Spine curls, hips still", "Flat back bows from the hips",
               "Rounding the spine against the cable makes the rectus abdominis lift the load.",
               "Hinging with a flat back lets body weight pull the rope down, so the abdominals barely shorten."),
   glows=CORE_GLOWS)

# ---------------------------------------------------------------- Leg raises

ex(name="Hanging Knee Raise", var="hangingKneeRaise", group="core",
   annotations=[
       ("grip", "Dead hang, shoulders active", "hand_L"),
       ("tilt", "Tuck the pelvis at the top", "pelvis"),
       ("knees", "Knees up toward the chest", "patella_L"),
       ("swing", "No swinging", "foot_L"),
       ("torso", "Torso stays still", "chest"),
   ],
   cues={
       "grip": ("Hang",
                "A steady hang is the base of the rep.",
                "Gripping the bar with the shoulders gently pulled down keeps the body from swinging, so the trunk does the work.",
                "Hanging loose from the shoulders and swaying between reps.",
                "Grip just outside shoulder-width and pull the shoulders slightly down away from the ears."),
       "tilt": ("Pelvic Tilt",
                "Lifting the knees is the hip flexors; curling the pelvis is the abs.",
                "The abdominals are worked when the pelvis tilts back and the lower spine curls at the top of the lift.",
                "Raising the knees to hip height with the lower back still arched.",
                "As the knees pass hip height, keep going by curling the pelvis up toward the ribs."),
       "knees": ("Range of Motion",
                 "Knees high, then higher.",
                 "Taking the knees toward the chest gives the pelvis room to curl, which is where the abs do most of the work.",
                 "Stopping with the thighs just below horizontal.",
                 "Draw the knees up toward the chest and pause briefly at the top."),
       "swing": ("Control",
                 "Momentum is the enemy.",
                 "Swinging lets the body's pendulum lift the legs instead of the trunk muscles.",
                 "Kicking the legs back to swing them up.",
                 "Lower the legs slowly and let the body settle before the next rep."),
       "torso": ("Upper Body",
                 "The torso stays under the bar.",
                 "A still torso means the lift comes from the hips and trunk.",
                 "Leaning back or pulling up with the arms to help the legs rise.",
                 "Keep the arms straight and the chest under the bar."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.80), ("Hip Flexors", P, HI, 0.76), ("Obliques", S, HI, 0.64)],
   stabilisers=["forearms", "latissimus dorsi", "shoulders"],
   comparison=("NO PELVIC CURL", "Pelvis curls at the top", "Knees rise, pelvis stays flat",
               "Curling the pelvis at the top brings the abdominals in on top of the hip flexors.",
               "Stopping at hip height leaves the lift almost entirely to the hip flexors."),
   glows=CORE_GLOWS)

ex(name="Hanging Leg Raise", overrides={"grip": (0.14, "leading")}, var="hangingLegRaise", group="core",
   annotations=[
       ("grip", "Dead hang, shoulders active", "hand_L"),
       ("tilt", "Curl the pelvis at the top", "pelvis"),
       ("legs", "Legs straight, lift to level", "patella_L"),
       ("swing", "Lower slowly, no swing", "foot_L"),
       ("torso", "Torso stays under the bar", "chest"),
   ],
   cues={
       "grip": ("Hang",
                "A steady hang keeps the lift honest.",
                "Shoulders pulled slightly down and a firm grip stop the body swinging as the long legs move.",
                "Hanging loose and swaying.",
                "Grip just outside shoulder-width and set the shoulders down away from the ears."),
       "tilt": ("Pelvic Tilt",
                "The abs work when the pelvis curls, not while the legs travel.",
                "The hip flexors lift the straight legs; the abdominals are worked most as the pelvis tilts back at the top.",
                "Lifting the legs with the lower back arched throughout.",
                "As the legs reach level, curl the pelvis up and slightly forward."),
       "legs": ("Leg Position",
                "Straight legs make a long, heavy lever.",
                "Straight legs put the weight of the legs much further from the hip than a knee raise does, so the trunk has to work harder to control the pelvis.",
                "Bending the knees halfway up to make it easier, then calling it a leg raise.",
                "Keep the knees straight and lift the feet at least to hip height."),
       "swing": ("Control",
                 "The way down decides the next rep.",
                 "A slow return stops the legs swinging back and throwing the next rep up with momentum.",
                 "Dropping the legs and swinging into the next rep.",
                 "Lower over two seconds and pause at the bottom."),
       "torso": ("Upper Body",
                 "Stay under the bar.",
                 "A still torso keeps the effort in the hips and trunk.",
                 "Leaning back to counterbalance the legs.",
                 "Arms straight, chest under the bar."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.84), ("Hip Flexors", P, HI, 0.86), ("Obliques", S, HI, 0.62)],
   stabilisers=["forearms", "latissimus dorsi", "quadriceps"],
   comparison=("SWINGING", "Slow, still torso", "Legs swing up with momentum",
               "A controlled lift makes the hip flexors and abdominals move and hold the long legs.",
               "Swinging uses the body as a pendulum, so the trunk muscles do much less of the lift."),
   glows=CORE_GLOWS)

ex(name="Captain's Chair Leg Raise", var="captainsChairLegRaise", group="core",
   annotations=[
       ("back", "Back against the pad", "chest"),
       ("arms", "Forearms on the pads", "hand_L"),
       ("tilt", "Curl the pelvis up", "pelvis"),
       ("legs", "Legs straight to level", "patella_L"),
       ("control", "Lower slowly", "foot_L"),
   ],
   cues={
       "back": ("Back Pad",
                "The pad keeps the body from swinging.",
                "With the back against the pad, momentum is removed and the lift has to come from the trunk and hips.",
                "Leaning away from the pad to swing the legs.",
                "Press the lower and upper back lightly into the pad throughout."),
       "arms": ("Support",
                "The forearms carry the body.",
                "Supporting yourself on the forearms frees the hands and keeps the shoulders stable.",
                "Shrugging the shoulders up toward the ears.",
                "Rest the forearms on the pads, grip the handles and push the shoulders down."),
       "tilt": ("Pelvic Tilt",
                "Finish by curling the pelvis.",
                "In the ACE-sponsored comparison of 13 ab exercises, the captain's chair ranked first for the obliques and second for the rectus abdominis — the pelvic curl at the top is what engages them.",
                "Lifting the legs with the lower back arched off the pad.",
                "As the legs come up, tilt the pelvis back so the lower back flattens into the pad."),
       "legs": ("Leg Position",
                "Straight legs make it harder.",
                "A long lever raises the load on the hip flexors and the abdominals controlling the pelvis; bent knees are the easier version.",
                "Letting the knees bend as fatigue sets in without noticing.",
                "Keep the legs straight and lift them to at least hip height."),
       "control": ("Tempo",
                   "Control the way down.",
                   "Lowering slowly keeps the trunk loaded and stops the legs swinging under the chair.",
                   "Dropping the legs back down.",
                   "Lower over about two seconds and stop before the feet swing back."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.82), ("Hip Flexors", P, HI, 0.80), ("Obliques", S, HI, 0.66)],
   stabilisers=["shoulders", "triceps", "quadriceps"],
   comparison=("LOWER BACK ARCHED", "Pelvis curls, back to the pad", "Back arches off the pad",
               "Flattening the lower back into the pad as the legs rise brings the abdominals into the lift.",
               "With the back arched, the hip flexors lift the legs and pull on the lumbar spine while the abs do little."),
   glows=CORE_GLOWS)

# ---------------------------------------------------------------- Anti-extension

ex(name="Ab Wheel Rollout", var="abWheelRollout", group="core", slots=FLAT,
   annotations=[
       ("hips", "Hips don't sag", "pelvis"),
       ("reach", "Stop before the back arches", "hand_L"),
       ("ribs", "Ribs down, back slightly rounded", "chest"),
       ("knees", "Kneel on a pad", "patella_L"),
       ("return", "Pull back with the abs", "scapula_L"),
   ],
   cues={
       "hips": ("Hip Position",
                "The rollout is a moving plank.",
                "The abdominals work to stop the lower back arching as the wheel travels away; once the hips sag, the load moves onto the spine.",
                "Letting the hips drop toward the floor at the far end.",
                "Keep a slight posterior pelvic tilt so the hips and trunk move as one."),
       "reach": ("Range of Motion",
                 "Go only as far as you can hold the position.",
                 "Rollouts produce some of the highest rectus abdominis and oblique activity measured in EMG studies, so a shorter, controlled reach is still very hard.",
                 "Rolling out to full length on the first rep and collapsing.",
                 "Roll out until you feel the lower back start to arch, then stop and return."),
       "ribs": ("Trunk Position",
                "Keep the ribs pulled toward the pelvis.",
                "Ribs down and a slightly rounded upper back keep the abdominals shortened enough to resist extension.",
                "Looking up and flaring the ribs, which arches the back.",
                "Look at the floor, brace, and keep the ribs tucked throughout."),
       "knees": ("Base",
                 "Kneeling is the standard version.",
                 "A padded kneeling base shortens the lever compared with the standing rollout, which is for advanced lifters.",
                 "Kneeling on a hard floor, which shifts the focus to the knees.",
                 "Kneel on a mat with the knees hip-width and the wheel under the shoulders."),
       "return": ("Return",
                  "Come back with the trunk, not the hips.",
                  "Pulling back by flexing the trunk keeps the abdominals and lats working; pushing the hips back first shortens the lever and skips the hard part.",
                  "Sticking the hips back to drag the wheel home.",
                  "Pull the wheel back toward the knees by curling the trunk, hips following."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.88), ("Obliques", S, HI, 0.68), ("Latissimus Dorsi", S, MOD, 0.48)],
   stabilisers=["triceps", "shoulders", "gluteus maximus"],
   comparison=("HIPS SAGGING", "Hips and trunk in one line", "Lower back arches, hips drop",
               "Holding a slight pelvic tuck makes the abdominals resist the stretch as the wheel rolls out.",
               "When the hips sag, the lumbar spine extends under load and the abs stop protecting it."),
   glows=CORE_GLOWS)

# ---------------------------------------------------------------- Lateral / rotation

ex(name="Side Plank", var="sidePlank", group="core", slots=FLAT,
   annotations=[
       ("elbow", "Elbow under the shoulder", "forearm_L"),
       ("hips", "Hips lifted, no sag", "pelvis"),
       ("line", "Straight line head to feet", "chest"),
       ("feet", "Feet stacked", "foot_L"),
       ("head", "Head in line", "head"),
   ],
   cues={
       "elbow": ("Support Arm",
                 "The shoulder sits over the elbow.",
                 "An elbow directly under the shoulder lets the arm hold the body on bone, so the trunk muscles do the holding.",
                 "Placing the elbow far in front of the shoulder, which strains it.",
                 "Set the forearm flat with the elbow under the shoulder and push the floor away."),
       "hips": ("Hip Height",
                "The bottom obliques hold the hips up.",
                "The side plank loads the obliques and quadratus lumborum — about 54% of maximum in McGill's measurements — with low compressive load on the spine.",
                "Letting the bottom hip sag toward the floor.",
                "Lift the hips until the body is straight and keep pushing them up for the whole hold."),
       "line": ("Body Line",
                "No bending forward or back.",
                "A straight line keeps the load across the side of the trunk instead of letting the body rotate out of it.",
                "Piking the hips back or rolling the chest toward the floor.",
                "Stack the shoulders over each other and keep the hips in line with them."),
       "feet": ("Feet",
                "The feet are the other end of the bridge.",
                "Stacked feet make the hold harder; staggering them front to back is an easier option.",
                "Rolling onto the edge of the bottom foot and losing the line.",
                "Stack the top foot on the bottom one, or stagger them to make it easier."),
       "head": ("Head Position",
                "The neck is part of the line.",
                "A neutral neck keeps the shoulders relaxed and the line honest.",
                "Letting the head drop toward the floor.",
                "Keep the head in line with the spine, eyes forward."),
   },
   activation=[("Obliques", P, HI, 0.78), ("Quadratus Lumborum", S, MOD, 0.54), ("Gluteus Medius", S, MOD, 0.46)],
   stabilisers=["transverse abdominis", "rectus abdominis", "shoulders"],
   comparison=("HIPS SAGGING", "Hips up, body straight", "Bottom hip sinks",
               "Holding the hips up makes the lower obliques and quadratus lumborum support the trunk.",
               "When the hip sags, the body hangs on the spine and shoulder instead of the trunk muscles."),
   glows=CORE_GLOWS)

ex(name="Russian Twist", var="russianTwist", group="core", slots=FLAT,
   annotations=[
       ("rotate", "Rotate from the ribs", "chest"),
       ("ball", "Ball moves with the chest", "hand_L"),
       ("lean", "Lean back, spine long", "head"),
       ("hips", "Hips stay still", "pelvis"),
       ("feet", "Feet on the floor", "foot_L"),
   ],
   cues={
       "rotate": ("Rotation",
                  "Turn the ribcage, not just the arms.",
                  "The obliques rotate the trunk, so the rib cage has to turn over the pelvis for them to work.",
                  "Swinging the ball side to side with the arms while the chest stays facing forward.",
                  "Turn the chest and shoulders together toward each side, following the ball with the eyes."),
       "ball": ("Load Position",
                "Keep the ball close.",
                "A ball held near the chest keeps the load on the trunk rather than the shoulders.",
                "Reaching the ball far away from the body to tap the floor.",
                "Hold the ball at chest height, elbows bent, and move it only as far as the chest turns."),
       "lean": ("Torso Angle",
                "A long spine, leaning back.",
                "Leaning back about 45° makes the abdominals hold the trunk up while the obliques rotate it.",
                "Slumping into a rounded lower back.",
                "Sit tall, then lean back with a straight spine until the abs switch on."),
       "hips": ("Pelvis",
                "The hips are the fixed point.",
                "A still pelvis means the rotation happens in the trunk, where the obliques act.",
                "Rocking the hips and knees side to side with each twist.",
                "Keep the knees together and pointing forward as the chest turns."),
       "feet": ("Feet",
                "Feet down is the base version.",
                "Keeping the feet on the floor stabilises the pelvis and keeps the load on the rotation, not on balance.",
                "Lifting the feet before you can control the twist.",
                "Rest the heels on the floor; lift them only once the twist stays controlled."),
   },
   activation=[("Obliques", P, HI, 0.76), ("Rectus Abdominis", S, MOD, 0.52), ("Hip Flexors", S, MOD, 0.38)],
   stabilisers=["transverse abdominis", "erector spinae"],
   comparison=("ARMS ONLY", "Chest turns with the ball", "Arms swing, chest faces forward",
               "Turning the rib cage over a still pelvis makes the obliques do the rotation.",
               "Swinging the ball with the arms moves the load without rotating the trunk, so the obliques barely work."),
   glows=CORE_GLOWS)

ex(name="Cable Wood Chop", var="cableWoodChop", group="core",
   annotations=[
       ("arms", "Arms long, handle close", "hand_L"),
       ("rotate", "Rotate the trunk", "chest"),
       ("hips", "Hips turn with you", "pelvis"),
       ("pivot", "Pivot the back foot", "foot_R"),
       ("brace", "Brace before you chop", "spine"),
   ],
   cues={
       "arms": ("Arm Position",
                "The arms transfer the force; they don't make it.",
                "With straight arms, the load on the handle can only move if the trunk rotates, which puts the work on the obliques.",
                "Bending the elbows and pulling the handle down with the arms.",
                "Keep the arms long and the handle in front of the chest as it travels."),
       "rotate": ("Rotation",
                  "Turn the chest diagonally, high to low.",
                  "The obliques rotate and flex the trunk together, which is exactly the diagonal path of the chop.",
                  "Bending sideways at the waist instead of turning.",
                  "Turn the chest from the high pulley down toward the opposite hip."),
       "hips": ("Hips",
                "Power starts at the hips.",
                "Letting the hips turn a little spreads the rotation between hips and trunk and protects the lower back from twisting alone.",
                "Locking the hips and wringing all the rotation out of the lumbar spine.",
                "Let the hips turn slightly with the chest, knees soft."),
       "pivot": ("Footwork",
                 "The back foot pivots.",
                 "Pivoting on the back foot lets the hips rotate without twisting the knee.",
                 "Keeping both feet flat so the knee takes the twist.",
                 "Stand wider than the shoulders and let the back heel lift and turn as you chop."),
       "brace": ("Bracing",
                 "Stiffen, then move.",
                 "Bracing the trunk first stiffens the spine so the hips and shoulders move around it, the job McGill describes as the core's main one.",
                 "Chopping loose and fast so the spine whips around.",
                 "Brace the abs, then chop in a smooth, controlled arc and return slowly."),
   },
   activation=[("Obliques", P, HI, 0.78), ("Rectus Abdominis", S, MOD, 0.44), ("Transverse Abdominis", S, MOD, 0.40)],
   stabilisers=["gluteus maximus", "latissimus dorsi", "shoulders"],
   comparison=("PULLING WITH THE ARMS", "Straight arms, trunk rotates", "Elbows bend to pull the handle",
               "Straight arms mean the handle moves only when the trunk rotates, loading the obliques.",
               "Bending the arms turns the chop into a cable pull, and the obliques do little of the work."),
   glows=CORE_GLOWS)
