# Trainer content for the Legs2 batch (2026-09-24): hamstring curls and hinges,
# glute bridges, kickbacks and abduction, plus the re-exported Step-Up,
# Push-Up and Plank. Same format as spec.py; run with `gen.py spec_legs2`.
# The lifter's LEFT side faces the camera in every one of these framings
# (negative yaw), and every single-leg model works the LEFT leg, so the cue
# joints are the _L ones.

P, S = "primary", "secondary"
HI, MOD = "HIGH ACTIVATION", "MODERATE ACTIVATION"
A, SOFT = "activation", "activationSoft"

SPEC = []

def ex(**kw):
    SPEC.append(kw)

HINGE_GLOWS = [(A, 0.55, 0.16, 0.12, 0.52, 0.55), (SOFT, 0.30, 0.12, 0.10, 0.50, 0.45)]
# Lying and prone bodies fill the middle band of the frame, so their labels
# skip the 0.50 row and sit above and below the body instead.
FLAT = [0.15, 0.28, 0.63, 0.75, 0.87]
PRONE_GLOWS = [(A, 0.55, 0.18, 0.08, 0.55, 0.50), (SOFT, 0.30, 0.12, 0.08, 0.45, 0.50)]
HIP_GLOWS = [(A, 0.55, 0.12, 0.10, 0.52, 0.50), (SOFT, 0.30, 0.10, 0.10, 0.48, 0.60)]

# ---------------------------------------------------------------- Hinges

ex(name="Dumbbell Romanian Deadlift", var="dumbbellRomanianDeadlift", group="legs",
   annotations=[
       ("spine", "Neutral spine", "chest"),
       ("hips", "Push the hips back", "pelvis"),
       ("path", "Dumbbells slide down the thighs", "hand_L"),
       ("knee", "Soft, fixed knees", "patella_L"),
       ("feet", "Weight on mid-foot", "foot_L"),
   ],
   cues={
       "spine": ("Spine Position",
                 "The back stays long while the hips do the moving.",
                 "A neutral spine keeps the load on the hamstrings and glutes, which lengthen as the hips travel back, instead of on the lower back.",
                 "Rounding the upper or lower back to get the dumbbells lower.",
                 "Chest proud, shoulders back and the head in line with the torso from the top of the rep to the bottom."),
       "hips": ("Hip Hinge",
                "The rep is a hinge, not a squat.",
                "Sending the hips back stretches the hamstrings under load, which is where this lift does most of its work.",
                "Bending the knees and dropping the hips straight down, which turns it into a squat.",
                "Push the hips back as if closing a door behind you, and stop when the hamstrings are fully stretched or the back starts to round."),
       "path": ("Dumbbell Path",
                "Keep the weights close to the legs.",
                "Dumbbells that stay against the thighs keep the load over mid-foot and shorten the lever on the lower back.",
                "Letting the dumbbells swing out in front of the body as the torso tips forward.",
                "Keep the dumbbells brushing the fronts of the thighs and shins, arms long and lats tight."),
       "knee": ("Knee Angle",
                "The knees bend a little at the start and then stay put.",
                "A fixed, slight bend lets the hips move back without the knees taking over, so the hamstrings stay loaded.",
                "Locking the knees straight, or bending them more and more as you go down.",
                "Unlock the knees slightly before the first rep and keep that same angle for the whole set."),
       "feet": ("Balance",
                "The weight stays over the middle of the foot.",
                "Balance over mid-foot lets the hips shift back without tipping onto the toes or the heels.",
                "Rocking onto the toes at the bottom as the weights drift forward.",
                "Stand hip-width, grip the floor with the whole foot and feel the pressure stay under the laces."),
   },
   activation=[("Hamstrings", P, HI, 0.84), ("Gluteus Maximus", S, HI, 0.66), ("Erector Spinae", S, MOD, 0.52)],
   stabilisers=["forearms", "lats", "core", "adductors"],
   comparison=("ROUNDED BACK", "Long spine, hips back", "Back rounds to reach lower",
               "Hinging with a neutral spine lets the hamstrings and glutes lengthen and drive the dumbbells back up.",
               "Rounding the back to chase depth moves the load from the hamstrings onto the spine and shortens the useful stretch."),
   glows=HINGE_GLOWS)

ex(name="Stiff-Leg Deadlift", var="stiffLegDeadlift", group="legs",
   annotations=[
       ("spine", "Flat back throughout", "chest"),
       ("hips", "Hips back, knees near-straight", "pelvis"),
       ("bar", "Bar close to the legs", "hand_L"),
       ("knee", "Knees barely bent", "patella_L"),
       ("feet", "Feet hip-width, flat", "foot_L"),
   ],
   cues={
       "spine": ("Back Position",
                 "A straighter knee means a longer lever on the back.",
                 "Keeping the back flat lets the hamstrings take the stretch; with the knees nearly straight, any rounding loads the spine quickly.",
                 "Letting the upper back round forward as the bar passes the knees.",
                 "Brace the trunk, keep the shoulders pulled back and hold a flat back from the first rep to the last."),
       "hips": ("Hip Hinge",
                "The hips travel back while the legs stay nearly straight.",
                "With little knee bend, the hamstrings are stretched further than in a Romanian deadlift, which makes this the more hamstring-biased hinge.",
                "Turning the rep into a toe-touch by bending only at the waist.",
                "Push the hips back, let the torso tip forward and stop at the depth your hamstrings allow with a flat back."),
       "bar": ("Bar Path",
               "The bar travels close to the body.",
               "A bar that stays near the legs keeps the load over mid-foot and limits the pull on the lower back.",
               "Letting the bar hang away from the shins at the bottom.",
               "Keep the arms long and the lats tight so the bar stays over the middle of the foot."),
       "knee": ("Knee Angle",
                "Stiff-legged, not locked.",
                "A slight bend protects the back of the knee while still putting the hamstrings in a long position.",
                "Hyperextending the knees, or letting them bend so far the lift becomes a Romanian deadlift.",
                "Keep a small, fixed bend in the knees throughout."),
       "feet": ("Stance",
                "A narrow, flat stance keeps the hinge balanced.",
                "Feet hip-width and flat give a stable base as the hips move back behind the heels.",
                "Rocking back on the heels, or up on the toes, at the bottom.",
                "Stand with the feet hip-width, toes forward, and keep the whole foot planted."),
   },
   activation=[("Hamstrings", P, HI, 0.88), ("Gluteus Maximus", S, MOD, 0.58), ("Erector Spinae", S, MOD, 0.58)],
   stabilisers=["forearms", "lats", "trapezius", "core"],
   comparison=("BACK ROUNDING", "Flat back, hips back", "Upper back rounds over the bar",
               "Holding a flat back puts the whole stretch through the hamstrings, which is the point of keeping the legs straight.",
               "When the back rounds, the depth comes from the spine instead of the hips, and the lumbar discs take the load."),
   glows=HINGE_GLOWS)

# ---------------------------------------------------------------- Leg curls

ex(name="Lying Leg Curl", slots=FLAT, var="lyingLegCurl", group="legs",
   annotations=[
       ("hips", "Hips pressed into the pad", "pelvis"),
       ("pad", "Pad just above the heels", "foot_L"),
       ("curl", "Curl heels to the glutes", "shin_L"),
       ("knee", "Knees just off the pad", "patella_L"),
       ("grip", "Hold the handles", "hand_L"),
   ],
   cues={
       "hips": ("Hip Position",
                "The hips stay down for the whole set.",
                "Keeping the hips on the pad stops the lower back and glutes from helping, so the hamstrings do the curling.",
                "Lifting the hips off the pad to finish the curl.",
                "Press the hips into the pad and keep them there, even on the last reps."),
       "pad": ("Pad Position",
               "Set the roller before the first rep.",
               "A roller just above the heels gives the hamstrings a long lever to work against without pressing on the Achilles tendon.",
               "Setting the pad high on the calves, which shortens the lever and lets the weight feel easier than it is.",
               "Adjust the roller so it sits on the back of the lower legs, just above the heels."),
       "curl": ("Range of Motion",
                "Curl all the way in, lower all the way out.",
                "Taking the knee from nearly straight to fully bent works the hamstrings through their full range.",
                "Stopping short at the top, or dropping the weight fast on the way down.",
                "Curl the heels toward the glutes, pause, then lower under control until the legs are almost straight."),
       "knee": ("Knee Alignment",
                "The knee joint lines up with the machine's pivot.",
                "When the knee sits over the axis, the machine's arc matches the knee's own, so the load stays smooth through the rep.",
                "Lying too far up or down the bench so the pad slides along the leg as you curl.",
                "Lie so your knees sit just off the end of the pad, in line with the pivot point."),
       "grip": ("Upper Body",
                "The hands anchor the body, they do not pull.",
                "Holding the handles lightly keeps the torso still so the curl comes only from the knees.",
                "Yanking on the handles to heave the weight up.",
                "Hold the handles, rest the chest on the bench and keep the upper body relaxed."),
   },
   activation=[("Hamstrings", P, HI, 0.90), ("Gastrocnemius", S, MOD, 0.46)],
   stabilisers=["gluteus maximus", "core"],
   comparison=("HIPS LIFTING", "Hips down, curl from the knees", "Hips rise to finish the rep",
               "With the hips pinned, only the knee bends, so the hamstrings take the full load through the full range.",
               "Lifting the hips shortens the hamstrings at the hip and lets momentum finish the rep, taking tension off the target."),
   glows=PRONE_GLOWS)

ex(name="Seated Leg Curl", var="seatedLegCurl", group="legs",
   annotations=[
       ("back", "Back against the pad", "chest"),
       ("thigh", "Thigh pad locked down", "thigh_L"),
       ("knee", "Knees in line with the pivot", "patella_L"),
       ("curl", "Curl heels under the seat", "shin_L"),
       ("grip", "Hold the handles", "hand_L"),
   ],
   cues={
       "back": ("Seat Position",
                "Sit back into the pad.",
                "Sitting upright with the hips flexed stretches the hamstrings at the hip, which lets them work harder at long lengths than when lying down.",
                "Slouching forward or lifting off the back pad during the curl.",
                "Sit all the way back and keep the torso against the pad for the whole set."),
       "thigh": ("Thigh Pad",
                 "The thigh pad keeps the hips still.",
                 "A snug pad above the knees stops the thighs lifting, so the knee is the only joint moving.",
                 "Leaving the pad loose, so the thighs rise as you curl.",
                 "Lower the thigh pad until it presses firmly just above the knees."),
       "knee": ("Knee Alignment",
                "Line the knees up with the machine's axis.",
                "When the knee sits on the pivot, the pad stays in one place on the leg and the resistance is smooth.",
                "Sitting too far forward or back so the ankle pad slides up and down the calves.",
                "Adjust the back pad so your knees line up with the pivot marked on the machine."),
       "curl": ("Range of Motion",
                "Full curl, slow return.",
                "The seated position already loads the hamstrings long, so a full range makes the most of it.",
                "Short, bouncing reps that never straighten the legs.",
                "Curl until the heels pass under the seat, then let the legs straighten slowly."),
       "grip": ("Upper Body",
                "Hold on to stay seated.",
                "Gripping the handles keeps the hips down as the load increases.",
                "Pulling on the handles or rocking the torso to help the curl.",
                "Hold the handles firmly with relaxed shoulders and let the legs do the work."),
   },
   activation=[("Hamstrings", P, HI, 0.92), ("Gastrocnemius", S, MOD, 0.40)],
   stabilisers=["hip flexors", "core"],
   comparison=("PARTIAL REPS", "Full curl, legs straighten", "Legs never straighten",
               "Using the full range while seated trains the hamstrings at the long lengths this machine is best at.",
               "Cutting the return short skips the stretched position, which is where the seated curl has its advantage."),
   glows=HIP_GLOWS)

ex(name="Single-Leg Curl", slots=FLAT, var="singleLegCurl", group="legs",
   annotations=[
       ("hips", "Hips square on the pad", "pelvis"),
       ("pad", "Pad just above the heel", "foot_L"),
       ("curl", "Curl to full bend", "shin_L"),
       ("knee", "Knee off the end of the pad", "patella_L"),
       ("still", "Other leg stays relaxed", "patella_R"),
   ],
   cues={
       "hips": ("Hip Position",
                "One leg working makes the hips want to twist.",
                "Keeping both hips pressed down stops the pelvis rotating, so the working hamstring cannot borrow help from the lower back.",
                "Rolling the hip of the working leg up off the pad as it curls.",
                "Press both hips into the pad and keep them level for every rep."),
       "pad": ("Pad Position",
               "Set the roller for one leg.",
               "A roller just above the heel gives the hamstring the longest lever without pressing on the Achilles tendon.",
               "Sliding the pad onto the calf.",
               "Place the roller on the back of the lower leg, just above the heel."),
       "curl": ("Range of Motion",
                "Curl fully, then lower slowly.",
                "Working one leg at a time lets each hamstring go through its full range without the stronger side taking over.",
                "Stopping halfway, or dropping the weight back down.",
                "Curl the heel toward the glute, pause, and lower until the leg is nearly straight."),
       "knee": ("Knee Alignment",
                "The knee sits over the pivot.",
                "Lining the knee up with the machine's axis keeps the resistance smooth through the arc.",
                "Lying too far up the bench, so the knee rests on the pad.",
                "Position yourself so the knee is just off the end of the pad, level with the pivot."),
       "still": ("Resting Leg",
                 "The other leg stays out of it.",
                 "A relaxed, still resting leg keeps the pelvis quiet and the work on one side.",
                 "Pressing the resting leg into the bench to lever the working leg up.",
                 "Let the resting leg lie straight and relaxed on the bench."),
   },
   activation=[("Hamstrings", P, HI, 0.90), ("Gastrocnemius", S, MOD, 0.46)],
   stabilisers=["gluteus maximus", "core", "obliques"],
   comparison=("HIP ROTATING", "Hips level on the pad", "Working hip lifts and twists",
               "Level hips keep the curl at the knee, so one hamstring does all the work.",
               "When the hip rolls up, the pelvis joins in and the hamstring does less of each rep."),
   glows=PRONE_GLOWS)

# ---------------------------------------------------------------- Bridges

ex(name="Glute Bridge", slots=FLAT, var="gluteBridge", group="legs",
   annotations=[
       ("hips", "Drive the hips up", "pelvis"),
       ("ribs", "Ribs down, no arch", "chest"),
       ("feet", "Heels close to the glutes", "foot_L"),
       ("knee", "Knees over the feet", "patella_L"),
       ("arms", "Arms flat on the floor", "hand_L"),
   ],
   cues={
       "hips": ("Hip Extension",
                "The glutes lift the hips; the lower back does not.",
                "Finishing with the hips fully extended is where the gluteus maximus works hardest in a bridge.",
                "Stopping short of full extension, or pushing higher by arching the back.",
                "Squeeze the glutes to lift until knees, hips and shoulders form a straight line, then pause."),
       "ribs": ("Rib Position",
                "Keep the ribs down at the top.",
                "A posterior-tilted pelvis with ribs down keeps the extension at the hip, not in the lumbar spine.",
                "Flaring the ribs and arching the lower back to look higher.",
                "Tuck the pelvis slightly and keep the ribs pulled down as the hips rise."),
       "feet": ("Foot Position",
                "Foot distance decides which muscles work.",
                "With the heels close to the glutes, the shins are near vertical at the top, which favours the glutes over the hamstrings.",
                "Placing the feet far away, which shifts the work to the hamstrings and can cramp them.",
                "Set the heels about a hand's length from the glutes, feet hip-width and flat."),
       "knee": ("Knee Alignment",
                "Knees stay in line with the feet.",
                "Knees tracking over the feet keep the hips square and let both glutes share the load.",
                "Letting the knees fall inward as the hips rise.",
                "Push the knees gently out so they stay over the middle of the feet."),
       "arms": ("Arm Position",
                "The arms steady the body, not push it.",
                "Flat arms give a wide base so the hips can lift without rocking.",
                "Pressing hard through the hands to help lift the hips.",
                "Rest the arms flat on the floor beside you, palms down and relaxed."),
   },
   activation=[("Gluteus Maximus", P, HI, 0.82), ("Hamstrings", S, MOD, 0.52), ("Erector Spinae", S, MOD, 0.36)],
   stabilisers=["gluteus medius", "adductors", "core"],
   comparison=("LOWER BACK ARCHING", "Hips up, ribs down", "Lower back arches at the top",
               "Finishing with a straight line from knees to shoulders keeps the lift at the hips, where the glutes work.",
               "Arching the lower back adds height without adding hip extension, so the glutes do less and the spine does more."),
   glows=HIP_GLOWS)

ex(name="Single-Leg Glute Bridge", slots=FLAT, var="singleLegGluteBridge", group="legs",
   annotations=[
       ("hips", "Hips stay level", "pelvis"),
       ("drive", "Drive through the heel", "foot_L"),
       ("knee", "Knee over the foot", "patella_L"),
       ("free", "Free leg lifted, still", "foot_R"),
       ("ribs", "Ribs down at the top", "chest"),
   ],
   cues={
       "hips": ("Pelvis Level",
                "One leg on the floor makes the hips want to drop.",
                "Keeping the pelvis level makes the working-side glutes resist rotation as well as extend, which is what makes this harder than the two-leg bridge.",
                "Letting the hip on the lifted side sag or twist on the way up.",
                "Keep both hip bones at the same height through the whole rep."),
       "drive": ("Foot Drive",
                 "Push through the heel of the planted foot.",
                 "Driving through the heel keeps the work in the glutes and hamstrings rather than the quads.",
                 "Pushing through the toes, which shifts the load forward onto the thigh.",
                 "Plant the working foot close to the glutes and press the heel into the floor."),
       "knee": ("Knee Alignment",
                "The working knee follows the foot.",
                "A knee kept over the foot stops the hip rolling inward.",
                "The knee drifting in toward the other leg.",
                "Keep the working knee over the middle of the foot from bottom to top."),
       "free": ("Free Leg",
                "The raised leg only goes along for the ride.",
                "A still free leg keeps momentum out of the lift, so the planted side does all the work.",
                "Kicking the free leg up to help the hips rise.",
                "Hold the free leg up and steady, knee bent or straight, as the hips move."),
       "ribs": ("Rib Position",
                "Finish with the hips, not the back.",
                "Ribs down means the height comes from hip extension, where the glutes work.",
                "Arching the lower back at the top.",
                "Keep the ribs down and stop when hip, knee and shoulder line up."),
   },
   activation=[("Gluteus Maximus", P, HI, 0.86), ("Hamstrings", S, MOD, 0.56), ("Gluteus Medius", S, MOD, 0.50)],
   stabilisers=["adductors", "obliques", "erector spinae"],
   comparison=("HIP DROPPING", "Pelvis level at the top", "Free-leg side of the hips sags",
               "A level pelvis makes the working glutes both lift and stabilise the hips.",
               "When the hips twist or sag, the load leaks away from the working side and the lower back takes over."),
   glows=HIP_GLOWS)

# ---------------------------------------------------------------- Cable glutes

ex(name="Cable Glute Kickback", var="cableGluteKickback", group="legs",
   annotations=[
       ("torso", "Hinge forward, spine long", "chest"),
       ("hips", "Hips square to the stack", "pelvis"),
       ("kick", "Kick back from the hip", "patella_L"),
       ("cuff", "Cuff on the working ankle", "foot_L"),
       ("grip", "Hands on the frame", "hand_L"),
   ],
   cues={
       "torso": ("Torso Angle",
                 "A slight forward lean gives the leg room to travel.",
                 "Hinging forward lets the hip extend fully without the lower back arching to make up the range.",
                 "Standing bolt upright and arching the back to get the leg behind the body.",
                 "Hold the frame, hinge forward a little from the hips and keep the spine long."),
       "hips": ("Hip Position",
                "The hips stay facing the stack.",
                "Square hips keep the movement in the sagittal plane, so the gluteus maximus extends the hip instead of the pelvis rotating.",
                "Opening the hip outward as the leg kicks back.",
                "Keep both hip bones pointing at the machine for every rep."),
       "kick": ("Range of Motion",
                "The movement ends where the hip does.",
                "Kicking back only as far as the hip extends keeps the tension in the glute rather than the lumbar spine.",
                "Swinging the leg high with momentum and arching the back at the top.",
                "Drive the heel back and slightly up, squeeze the glute at the end and return under control."),
       "cuff": ("Attachment",
                "The cable pulls from the ankle.",
                "An ankle cuff on a low pulley keeps the resistance in line with the kick.",
                "Letting the cable slacken at the start so the load only appears at the end.",
                "Strap the cuff around the working ankle and step back until there is tension at the start."),
       "grip": ("Support",
                "The frame steadies you.",
                "Holding the frame takes balance out of the lift, so the working glute can be loaded properly.",
                "Pulling on the frame to twist the body into the kick.",
                "Hold the frame with both hands, arms relaxed, standing leg slightly bent."),
   },
   activation=[("Gluteus Maximus", P, HI, 0.84), ("Hamstrings", S, MOD, 0.50), ("Gluteus Medius", S, MOD, 0.40)],
   stabilisers=["standing-leg glutes", "core", "erector spinae"],
   comparison=("BACK ARCHING", "Hip extends, spine still", "Lower back arches to lift the leg",
               "Keeping the spine still ends the kick at full hip extension, which is where the glute is working hardest.",
               "Arching the back lifts the leg higher but the extra range comes from the spine, not the glute."),
   glows=HIP_GLOWS)

ex(name="Cable Side Kick", var="cableSideKick", group="legs",
   annotations=[
       ("torso", "Stand tall, no lean", "chest"),
       ("hips", "Hips face forward", "pelvis"),
       ("kick", "Sweep the leg out to the side", "patella_L"),
       ("foot", "Toes point forward", "foot_L"),
       ("grip", "Hold the rail lightly", "hand_R"),
   ],
   cues={
       "torso": ("Torso Position",
                 "The torso stays upright while the leg moves.",
                 "Leaning away from the working leg shortens the range at the hip and lets the trunk muscles take over from the gluteus medius.",
                 "Tipping the torso away to lift the leg higher.",
                 "Stand tall, shoulders over the hips, and let only the leg move."),
       "hips": ("Hip Position",
                "Keep the hips square to the front.",
                "Facing forward keeps the leg moving straight out to the side, which is the gluteus medius's line of pull.",
                "Turning the hips and toes up, which swaps in the hip flexors.",
                "Point both hip bones forward for the whole set."),
       "kick": ("Range of Motion",
                "From across the body to out wide.",
                "Starting with the leg crossed in front lengthens the abductors, so the side glute works through its full range.",
                "Short, fast kicks that never cross the midline.",
                "Let the leg cross slightly in front, then sweep it out to the side under control and return slowly."),
       "foot": ("Foot Position",
                "The toes lead forward, not up.",
                "Toes forward or slightly down keep the gluteus medius in charge; rotating the foot up hands the work to the hip flexors.",
                "Turning the toes toward the ceiling as the leg rises.",
                "Keep the toes pointing forward throughout the kick."),
       "grip": ("Support",
                "Hold on just enough to balance.",
                "A light hand on the rail removes the balance demand so you can load the moving side.",
                "Pulling on the rail to lean the body.",
                "Hold the rail with the near hand and keep the standing knee soft."),
   },
   activation=[("Gluteus Medius", P, HI, 0.82), ("Gluteus Maximus", S, MOD, 0.48)],
   stabilisers=["standing-leg gluteus medius", "obliques", "adductors"],
   comparison=("TORSO LEANING", "Upright torso, leg sweeps out", "Torso tips to lift the leg",
               "Staying upright makes the side glute lift the leg through the full range.",
               "Leaning away lifts the foot higher but the extra range comes from the trunk, not the hip."),
   glows=HIP_GLOWS)

ex(name="Cable Hip Abduction", var="cableHipAbduction", group="legs",
   annotations=[
       ("torso", "Stay upright", "chest"),
       ("hips", "Pelvis level", "pelvis"),
       ("lift", "Lift the leg out, not up", "patella_L"),
       ("foot", "Toes forward", "foot_L"),
       ("grip", "Hand on the post", "hand_R"),
   ],
   cues={
       "torso": ("Torso Position",
                 "Only the leg moves.",
                 "An upright torso keeps the movement at the hip, so the gluteus medius lifts the leg.",
                 "Leaning the upper body away from the moving leg.",
                 "Stand tall with the shoulders stacked over the hips."),
       "hips": ("Pelvis",
                "Keep the pelvis still and level.",
                "Hiking the hip on the working side lets the side trunk muscles lift the leg instead of the glute.",
                "Shrugging the working hip up toward the ribs.",
                "Keep both hip bones level and move the leg from the hip joint."),
       "lift": ("Range of Motion",
                "A modest, controlled range.",
                "The hip abducts about 30–45°; past that the pelvis tips and the glute stops doing the work.",
                "Swinging the leg as high as possible.",
                "Lift the leg out to the side until the pelvis wants to move, pause, and lower slowly."),
       "foot": ("Foot Position",
                "Lead with the heel, toes forward.",
                "Keeping the foot facing forward keeps the gluteus medius in its line of pull.",
                "Rotating the toes up toward the ceiling.",
                "Keep the toes forward, or slightly down, as the leg moves."),
       "grip": ("Support",
                "The post is for balance.",
                "Light support lets you focus on the working hip without the standing leg wobbling.",
                "Leaning on the post to move the body.",
                "Rest the near hand on the post, standing knee soft."),
   },
   activation=[("Gluteus Medius", P, HI, 0.80), ("Gluteus Maximus", S, MOD, 0.42)],
   stabilisers=["standing-leg gluteus medius", "obliques", "core"],
   comparison=("HIP HIKING", "Pelvis level, leg moves out", "Hip hikes to lift the leg",
               "With a level pelvis the gluteus medius lifts the leg by itself.",
               "Hiking the hip moves the leg with the trunk muscles, so it looks like more range but the glute does less."),
   glows=HIP_GLOWS)

# ---------------------------------------------------------------- Abduction machine

ex(name="Hip Abduction Machine", overrides={"grip": (0.50, "trailing"), "push": (0.68, "trailing")}, var="hipAbductionMachine", group="legs",
   annotations=[
       ("back", "Back against the pad", "chest"),
       ("push", "Push knees out", "patella_L"),
       ("hips", "Hips stay in the seat", "pelvis"),
       ("feet", "Feet on the footrests", "foot_L"),
       ("grip", "Hold the handles", "hand_L"),
   ],
   cues={
       "back": ("Seat Position",
                "Sit upright against the back pad.",
                "An upright torso keeps the hips at about 90°, which biases the gluteus medius and the upper fibres of the gluteus maximus.",
                "Slouching or rocking the torso forward to push the pads apart.",
                "Sit all the way back and keep the torso still against the pad."),
       "push": ("Knee Drive",
                "Push through the outsides of the knees.",
                "Driving the pads apart with the knees abducts the hips, the main job of the gluteus medius.",
                "Letting the pads snap back together between reps.",
                "Press the knees out as far as the hips allow, pause, then let them return slowly."),
       "hips": ("Hip Position",
                "The hips stay planted.",
                "A still pelvis keeps the effort at the hip joint instead of shifting in the seat.",
                "Lifting the hips off the seat to force the last reps.",
                "Keep the glutes pressed into the seat for the whole set."),
       "feet": ("Foot Position",
                "Feet rest, they do not push.",
                "Relaxed feet on the rests keep the movement coming from the hips.",
                "Pushing the feet into the rests, which turns the lift into a leg press.",
                "Place the feet flat on the footrests and keep them relaxed."),
       "grip": ("Handles",
                "Hold on to stay put.",
                "Holding the handles keeps the torso still as the load increases.",
                "Pulling on the handles to rock the body.",
                "Grip the handles lightly with relaxed shoulders."),
   },
   activation=[("Gluteus Medius", P, HI, 0.82), ("Gluteus Maximus", S, MOD, 0.52)],
   stabilisers=["core", "hip flexors"],
   comparison=("PADS SLAMMING", "Controlled return", "Knees snap back together",
               "A slow return keeps the gluteus medius working on the way in as well as the way out.",
               "Letting the weight stack slam the pads together throws away half of every rep."),
   glows=HIP_GLOWS)

ex(name="Hip Abduction Machine (Lean)", overrides={"grip": (0.50, "trailing"), "push": (0.68, "trailing")}, var="hipAbductionMachineLean", group="legs",
   annotations=[
       ("lean", "Lean forward from the hips", "chest"),
       ("push", "Push knees out", "patella_L"),
       ("hips", "Hips stay in the seat", "pelvis"),
       ("feet", "Feet on the footrests", "foot_L"),
       ("grip", "Hold the handles", "hand_L"),
   ],
   cues={
       "lean": ("Torso Lean",
                "Leaning forward changes which glute fibres work.",
                "With the hips flexed further, the upper fibres of the gluteus maximus act more as hip abductors, so the lean shifts more of the work onto the glute max.",
                "Rounding the back to lean instead of hinging at the hips.",
                "Keep the spine long and tip the torso forward from the hips, then hold that angle for the set."),
       "push": ("Knee Drive",
                "Push through the outsides of the knees.",
                "Driving the pads apart from a flexed-hip position trains the glutes at a longer length.",
                "Short reps that stop well before the end of the range.",
                "Press the knees out as far as the hips allow, pause, then return slowly."),
       "hips": ("Hip Position",
                "The hips stay planted as you lean.",
                "Keeping the glutes on the seat makes the lean come from the hips rather than sliding forward.",
                "Sliding forward on the seat to lean further.",
                "Stay seated right back, then hinge forward over the thighs."),
       "feet": ("Foot Position",
                "Feet rest, they do not push.",
                "Relaxed feet keep the effort at the hips.",
                "Pressing the feet into the rests to help the pads apart.",
                "Keep the feet flat and relaxed on the footrests."),
       "grip": ("Handles",
                "Hold on to keep the lean steady.",
                "Holding the handles supports the forward lean so the torso does not bob with each rep.",
                "Pulling on the handles to rock forward and back.",
                "Hold the handles and keep the torso angle fixed."),
   },
   activation=[("Gluteus Medius", P, HI, 0.78), ("Gluteus Maximus", S, HI, 0.66)],
   stabilisers=["erector spinae", "core"],
   comparison=("ROUNDED BACK", "Hinge from the hips", "Back rounds to lean",
               "Hinging from the hips puts the glutes in a flexed position, where the upper glute max helps abduct.",
               "Rounding the back leans the shoulders without flexing the hips, so the glutes gain nothing from the lean."),
   glows=HIP_GLOWS)

# ---------------------------------------------------------------- Re-exports

ex(name="Step-Up", var="stepUp", group="legs",
   annotations=[
       ("torso", "Chest up, slight lean", "chest"),
       ("drive", "Drive through the top foot", "foot_L"),
       ("knee", "Knee tracks the toes", "patella_L"),
       ("hips", "Hips level", "pelvis"),
       ("grip", "Dumbbells at your sides", "hand_L"),
   ],
   cues={
       "torso": ("Torso Position",
                 "Stay tall with a slight forward lean.",
                 "A small lean over the top foot keeps your balance over the working leg so it does the lifting.",
                 "Folding forward to heave the body up, or leaning back at the top.",
                 "Keep the chest up and shoulders slightly in front of the hips as you rise."),
       "drive": ("Working Leg",
                 "The top leg does the work.",
                 "Driving through the whole foot on the box works the quadriceps and glutes of that leg.",
                 "Pushing off the floor with the back foot, which turns it into a jump.",
                 "Plant the whole foot on the box and push through it until you stand tall; keep the back leg passive."),
       "knee": ("Knee Tracking",
                "The working knee follows the foot.",
                "Knee over the middle toes keeps the knee aligned under load.",
                "The knee caving inward as you drive up.",
                "Keep the knee in line with the middle of the foot from bottom to top."),
       "hips": ("Pelvis",
                "Keep the hips level on the way up and down.",
                "A level pelvis makes the working-side glutes stabilise the hip as well as extend it.",
                "The hip of the free leg dropping as you step.",
                "Keep both hip bones level and step down slowly under control."),
       "grip": ("Load Position",
                "The dumbbells hang straight down.",
                "Weights at arm's length keep the load under the shoulders, so balance stays over the working leg.",
                "Letting the dumbbells swing forward or curl up.",
                "Hold a dumbbell in each hand, arms long and shoulders down."),
   },
   activation=[("Quadriceps", P, HI, 0.82), ("Gluteus Maximus", S, HI, 0.64), ("Gluteus Medius", S, MOD, 0.44)],
   stabilisers=["hamstrings", "adductors", "forearms", "core"],
   comparison=("BACK FOOT PUSHING", "Top leg lifts you", "Back foot bounces off the floor",
               "Letting the top leg do all the lifting keeps the work in that leg's quads and glutes.",
               "A push from the back foot makes the step easier by moving the work to the leg that is not meant to be training."),
   glows=[(A, 0.55, 0.14, 0.12, 0.50, 0.55), (SOFT, 0.30, 0.10, 0.10, 0.50, 0.45)])

ex(name="Push-Up", slots=FLAT, var="pushUp", group="chest",
   annotations=[
       ("body", "Body in one straight line", "pelvis"),
       ("hands", "Hands under the shoulders", "hand_L"),
       ("elbow", "Elbows ~45° from the body", "forearm_L"),
       ("depth", "Chest to just above the floor", "chest"),
       ("feet", "Feet together, toes tucked", "foot_L"),
   ],
   cues={
       "body": ("Body Line",
                "A push-up is a moving plank.",
                "A straight line from head to heels keeps the load on the chest and triceps and makes the abs work to hold the trunk.",
                "Letting the hips sag toward the floor, or piking them up.",
                "Squeeze the glutes and brace the abs so the body moves as one piece."),
       "hands": ("Hand Position",
                 "Hands a little wider than the shoulders.",
                 "Hands under or just outside the shoulders keep the forearms vertical at the bottom, the strongest pressing position.",
                 "Placing the hands far forward, toward the head, which loads the shoulders.",
                 "Set the hands slightly wider than shoulder-width, level with the chest, fingers forward."),
       "elbow": ("Elbow Angle",
                 "Tuck the elbows about 45°.",
                 "At roughly 45° from the torso the chest stays in its strongest line of pull and the shoulder joint stays supported.",
                 "Flaring the elbows straight out to the sides.",
                 "Let the elbows travel back at about 45° as you lower."),
       "depth": ("Depth",
                 "Lower all the way.",
                 "Taking the chest close to the floor works the chest through its full range.",
                 "Short reps that only bend the elbows a little.",
                 "Lower until the chest is just above the floor, then press back up to straight arms."),
       "feet": ("Base",
                "The toes are the back of the plank.",
                "Feet together make the trunk resist more rotation; wider feet are easier to balance.",
                "Letting the feet slide or the heels drop to one side.",
                "Tuck the toes, keep the feet together or hip-width, and push back through the heels."),
   },
   activation=[("Pectoralis Major", P, HI, 0.84), ("Triceps Brachii", S, MOD, 0.60), ("Anterior Deltoid", S, MOD, 0.52)],
   stabilisers=["serratus anterior", "rectus abdominis", "gluteus maximus"],
   comparison=("HIPS SAGGING", "Straight line head to heels", "Hips drop toward the floor",
               "A rigid body line makes the chest and triceps lift the whole body in one piece.",
               "When the hips sag, the lower back arches and part of each rep is lost to the trunk bending instead of the chest pressing."),
   glows=[(A, 0.55, 0.16, 0.08, 0.45, 0.50), (SOFT, 0.30, 0.10, 0.08, 0.40, 0.50)])

ex(name="Plank", slots=FLAT, var="plank", group="core",
   annotations=[
       ("body", "Straight line, head to heels", "pelvis"),
       ("elbow", "Elbows under the shoulders", "forearm_L"),
       ("ribs", "Ribs down, abs braced", "chest"),
       ("head", "Neck neutral, eyes down", "head"),
       ("feet", "Push back through the heels", "foot_L"),
   ],
   cues={
       "body": ("Body Line",
                "The hold is only useful while the line is straight.",
                "A straight body makes the abdominals resist gravity pulling the hips down, which is the whole point of the plank.",
                "Hips sagging toward the floor, or piked up to rest.",
                "Line up ears, shoulders, hips and ankles and hold it there."),
       "elbow": ("Elbow Position",
                 "Stack the shoulders over the elbows.",
                 "Elbows under the shoulders let the upper body rest on bone, so the effort stays in the trunk.",
                 "Elbows far in front of the shoulders, or the shoulder blades collapsing together.",
                 "Place the elbows under the shoulders and push the floor away to spread the shoulder blades."),
       "ribs": ("Bracing",
                "Brace as if about to be poked in the stomach.",
                "Pulling the ribs toward the pelvis tilts it slightly back, which increases abdominal activity compared with a relaxed plank.",
                "Holding the breath with the lower back arched.",
                "Tuck the pelvis slightly, squeeze the glutes, pull the ribs down and keep breathing."),
       "head": ("Head Position",
                "The neck is part of the line.",
                "A neutral neck keeps the shoulders from shrugging and the line honest.",
                "Dropping the head or craning it up to look forward.",
                "Look at the floor just in front of the hands."),
       "feet": ("Feet",
                "The feet anchor the back of the plank.",
                "Pressing back through the heels tightens the legs and glutes, which helps hold the pelvis in place.",
                "Legs relaxed, with the weight sinking into the hips.",
                "Feet hip-width, toes tucked, legs straight and pressing back."),
   },
   activation=[("Rectus Abdominis", P, HI, 0.78), ("Obliques", S, MOD, 0.56), ("Gluteus Maximus", S, MOD, 0.36)],
   stabilisers=["transverse abdominis", "serratus anterior", "quadriceps", "shoulders"],
   comparison=("HIPS SAGGING", "Body straight, ribs down", "Hips sink toward the floor",
               "With the ribs down and glutes tight, the abs hold the trunk straight against gravity.",
               "Sagging hips hand the hold to the lower back's ligaments and the abs stop working."),
   glows=[(A, 0.55, 0.14, 0.07, 0.50, 0.52), (SOFT, 0.30, 0.10, 0.07, 0.45, 0.52)])
