# Trainer content for the Shoulder, Arm and remaining Leg exercises.
# Each entry: annotations (cueID, label, joint) in the order the cues are
# listed; cues keyed by cueID -> (title, intro, why, mistake, correct).

P, S = "primary", "secondary"
HI, MOD = "HIGH ACTIVATION", "MODERATE ACTIVATION"
A, SOFT = "activation", "activationSoft"

SPEC = []

def ex(**kw):
    SPEC.append(kw)

# ---------------------------------------------------------------- Shoulders

ex(name="Barbell Overhead Press", var="barbellOverheadPress", group="shoulders",
   annotations=[
       ("grip", "Wrists over elbows", "forearm_L"),
       ("barpath", "Bar travels straight up", "hand_L"),
       ("head", "Head through at lockout", "head"),
       ("brace", "Glutes tight, ribs down", "spine"),
       ("feet", "Legs locked, no dip", "foot_L"),
   ],
   cues={
       "grip": ("Grip & Forearms",
                "The press starts from the rack position, and the forearms set its line.",
                "With the wrists stacked over vertical forearms, force travels straight up into the bar instead of bending the wrists back.",
                "A grip so wide or a wrist so cocked that the bar rolls onto the fingers and drifts forward.",
                "Grip just outside the shoulders with the bar low in the palm, forearms vertical and elbows slightly in front of the bar."),
       "barpath": ("Bar Path",
                   "The bar should rise in a straight vertical line over the middle of the foot.",
                   "A vertical path keeps the load balanced over the base; a bar that loops forward lengthens the lever on the shoulders and lower back.",
                   "Pressing the bar out and around the face so it finishes in front of the head.",
                   "Pull the chin back to clear a straight path, press the bar close to the face and finish directly over mid-foot."),
       "head": ("Head Position",
                "The head moves out of the way on the way up and back in at the top.",
                "Bringing the head through under the bar at lockout stacks bar, shoulders and hips, so the deltoids and triceps finish the rep without the lower back compensating.",
                "Leaving the head back at lockout, which parks the bar in front of the body.",
                "Once the bar passes the forehead, push the head forward under it and finish with the arms beside the ears."),
       "brace": ("Trunk Bracing",
                 "Standing overhead work is only as stable as the trunk under it.",
                 "Squeezing the glutes and keeping the ribs down stops the lower back arching, which would turn the lift into a steep incline press.",
                 "Leaning back to press, over-arching the lumbar spine to get the bar up.",
                 "Brace the abs, squeeze the glutes and keep the ribs stacked over the pelvis on every rep."),
       "feet": ("Base",
                "A strict press gets no help from the legs.",
                "Locked knees and a hip-width stance keep the effort on the shoulders and triceps and give a stable base to press from.",
                "Dipping the knees to bounce the bar up, which turns the press into a push press.",
                "Stand with the feet about hip-width, knees locked and weight balanced over mid-foot for the whole set."),
   },
   activation=[("Anterior Deltoid", P, HI, 0.86), ("Lateral Deltoid", P, HI, 0.74), ("Triceps Brachii", S, MOD, 0.58)],
   stabilisers=["serratus anterior", "rotator cuff", "core", "glutes"],
   comparison=("LEANING BACK", "Ribs down, bar over mid-foot", "Lower back arches to press",
               "Keeping the ribs down and the glutes tight holds the trunk vertical, so the deltoids and triceps drive the bar straight up.",
               "Leaning back turns the press into a steep incline press and loads the lumbar spine in extension — the most common overhead-press fault."),
   glows=[(A, 0.55, 0.20, 0.08, 0.50, 0.30), (SOFT, 0.30, 0.10, 0.10, 0.50, 0.40)])

ex(name="Dumbbell Shoulder Press", var="dumbbellShoulderPress", group="shoulders",
   annotations=[
       ("elbow", "Elbows slightly forward", "forearm_L"),
       ("path", "Press up and slightly in", "hand_L"),
       ("depth", "Lower to ear level", "upper_arm_L"),
       ("back", "Back against the pad", "spine"),
       ("feet", "Feet flat, wide base", "foot_L"),
   ],
   cues={
       "elbow": ("Elbow Position",
                 "Where the elbows sit decides how the shoulder joint takes the load.",
                 "Keeping the elbows slightly in front of the torso lets the anterior and lateral deltoids press without jamming the front of the shoulder.",
                 "Elbows flared straight out to the sides and pulled behind the body at the bottom.",
                 "Start with the elbows a little forward of the shoulders and the forearms vertical under the dumbbells."),
       "path": ("Press Path",
                "The dumbbells travel in a slight arc, not straight out to the sides.",
                "Pressing up and slightly inward keeps the forearms vertical, so the load stays over the joints the deltoids are moving.",
                "Letting the dumbbells drift wide, or clanging them together at the top and losing tension.",
                "Press up and slightly in until the arms are straight, stopping with the dumbbells just short of touching."),
       "depth": ("Range of Motion",
                 "How low the dumbbells go decides how much of the deltoid's range is trained.",
                 "Lowering to about ear level loads the deltoids through a long range while keeping stress on the front of the shoulder manageable.",
                 "Cutting reps short a few inches from lockout, or dropping the elbows far below the shoulders.",
                 "Lower under control until the dumbbells are roughly level with the ears, then press back to straight arms."),
       "back": ("Back Support",
                "The seat back is there to keep the torso out of the lift.",
                "Keeping the back against the pad removes momentum and lumbar arching, so the shoulders do the pressing.",
                "Sliding down the pad and arching the lower back to push heavier dumbbells.",
                "Sit tall with the hips back and the upper back against the pad for the whole set."),
       "feet": ("Foot Position",
                "The feet anchor the seated body.",
                "Flat feet set wide give a stable base, so balancing the dumbbells doesn't pull the torso around.",
                "Feet tucked under the bench or up on the toes, so the hips shift with every rep.",
                "Plant both feet flat, a little wider than the hips, and keep them still throughout the set."),
   },
   activation=[("Anterior Deltoid", P, HI, 0.84), ("Lateral Deltoid", P, HI, 0.72), ("Triceps Brachii", S, MOD, 0.52)],
   stabilisers=["rotator cuff", "serratus anterior", "biceps brachii"],
   comparison=("ELBOWS FLARED BACK", "Elbows slightly forward", "Elbows flared behind the torso",
               "Pressing with the elbows a little in front of the body keeps the shoulder in the scapular plane, where the deltoids are strong and the joint is well supported.",
               "Flaring the elbows out and back at the bottom pinches the front of the shoulder and shifts load onto the rotator cuff."),
   glows=[(A, 0.55, 0.20, 0.08, 0.50, 0.30), (SOFT, 0.30, 0.10, 0.10, 0.50, 0.40)])

ex(name="Arnold Press", var="arnoldPress", group="shoulders",
   annotations=[
       ("rotation", "Rotate while you press", "forearm_L"),
       ("start", "Start palms in, at chin", "hand_L"),
       ("finish", "Finish over the shoulders", "upper_arm_L"),
       ("back", "Back against the pad", "spine"),
       ("feet", "Feet flat, wide base", "foot_L"),
   ],
   cues={
       "rotation": ("Rotation",
                    "The turn of the palms is what makes this press distinctive.",
                    "Rotating the palms outward as the elbows open brings the lateral deltoid into the press while the anterior deltoid keeps working.",
                    "Rotating first and pressing afterwards, or whipping through the turn with momentum.",
                    "Open the elbows and turn the palms out smoothly as you press, so the rotation finishes as the arms straighten."),
       "start": ("Start Position",
                 "The Arnold press begins where a curl finishes.",
                 "Starting with the palms facing you at chin height puts the front deltoids on stretch and under load before the press begins.",
                 "Starting with the elbows flared and palms already forward, which makes it an ordinary shoulder press.",
                 "Hold the dumbbells in front of the chin, palms toward the face and elbows tucked in front of the body."),
       "finish": ("Lockout",
                  "Every rep finishes in the same place.",
                  "Ending with the palms forward and the dumbbells stacked over the shoulders keeps the load on the deltoids rather than the elbows.",
                  "Finishing with bent arms or the dumbbells drifting in front of the face.",
                  "Press until the arms are straight with the palms forward, then reverse the rotation on the way down."),
       "back": ("Back Support",
                "The seat back keeps the torso out of the lift.",
                "With the back on the pad, the rotation comes from the shoulders instead of a twisting, arching torso.",
                "Arching away from the pad as the dumbbells rotate overhead.",
                "Sit tall with the hips back and the upper back against the pad for the whole set."),
       "feet": ("Foot Position",
                "The feet anchor the seated body.",
                "A wide, flat base keeps the hips still while the arms rotate and press.",
                "Feet tucked under the bench or up on the toes.",
                "Plant both feet flat, a little wider than the hips, and keep them still."),
   },
   activation=[("Anterior Deltoid", P, HI, 0.86), ("Lateral Deltoid", S, MOD, 0.64), ("Triceps Brachii", S, MOD, 0.50)],
   stabilisers=["rotator cuff", "serratus anterior", "biceps brachii"],
   comparison=("ROTATING TOO EARLY", "Rotate and press together", "Palms turned before the press",
               "Turning the palms while pressing blends the anterior and lateral deltoids into one continuous movement.",
               "Rotating before pressing skips the stretched start position and reduces the lift to a regular shoulder press with extra wrist twisting."),
   glows=[(A, 0.55, 0.20, 0.08, 0.50, 0.30), (SOFT, 0.30, 0.12, 0.08, 0.50, 0.36)])

ex(name="Machine Shoulder Press", var="machineShoulderPress", group="shoulders",
   annotations=[
       ("seat", "Handles at shoulder height", "upper_arm_L"),
       ("elbow", "Elbows under the handles", "forearm_L"),
       ("lockout", "Press to a soft lockout", "hand_L"),
       ("back", "Back flat on the pad", "spine"),
       ("feet", "Feet flat on the floor", "foot_L"),
   ],
   cues={
       "seat": ("Seat Height",
                "A machine only fits you once the seat is set.",
                "With the handles level with the shoulders the press starts where the deltoids are strong and the machine's arc matches the shoulder joint.",
                "A seat so low the handles start above the head, or so high the elbows drop far below the shoulders.",
                "Adjust the seat so the handles line up with the tops of the shoulders before loading the stack."),
       "elbow": ("Elbow Position",
                 "The forearms should push straight up into the handles.",
                 "Forearms stacked under the handles send the load straight through the arm; flared elbows twist the shoulder.",
                 "Elbows flared wide behind the handles.",
                 "Keep the elbows slightly forward and directly under the handles for the whole rep."),
       "lockout": ("Range of Motion",
                   "Use the full path the machine allows.",
                   "Pressing to near-straight arms and lowering back to shoulder level trains the deltoids through their whole range.",
                   "Short, bouncing reps that never come back below the forehead.",
                   "Press to a soft lockout, pause, then lower under control until the handles return to shoulder height."),
       "back": ("Back Support",
                "The pad takes the trunk out of the lift, which is the point of a machine press.",
                "A flat back on the pad means the deltoids and triceps move the stack, not a lumbar arch.",
                "Arching away from the pad to move more weight.",
                "Keep the hips back and the back flat on the pad; don't let the chest lift away as you press."),
       "feet": ("Foot Position",
                "The feet keep the hips planted in the seat.",
                "Flat feet stop the hips sliding forward as the load gets heavy.",
                "Feet dangling or pushing off the toes.",
                "Plant both feet flat on the floor, about hip-width apart."),
   },
   activation=[("Anterior Deltoid", P, HI, 0.80), ("Lateral Deltoid", P, HI, 0.76), ("Triceps Brachii", S, MOD, 0.50)],
   stabilisers=["rotator cuff", "serratus anterior"],
   comparison=("BACK OFF THE PAD", "Back flat on the pad", "Lower back arches off the pad",
               "With the back flat on the pad, the machine's fixed path lets the deltoids press with nothing else joining in.",
               "Arching off the pad changes the pressing angle toward an incline press and loads the lower back the machine is meant to protect."),
   glows=[(A, 0.55, 0.20, 0.08, 0.50, 0.30), (SOFT, 0.30, 0.10, 0.10, 0.50, 0.40)])

ex(name="Dumbbell Lateral Raise", var="dumbbellLateralRaise", group="shoulders",
   annotations=[
       ("traps", "Shoulders down, no shrug", "support_TrapeziusUpper_L"),
       ("plane", "Arms slightly forward", "upper_arm_L"),
       ("elbow", "Soft, fixed elbows", "forearm_L"),
       ("height", "Stop at shoulder height", "hand_L"),
       ("torso", "Torso still, no swing", "spine"),
   ],
   cues={
       "traps": ("Shoulder Position",
                 "A lateral raise is a deltoid exercise, not a shrug.",
                 "Keeping the shoulders down stops the upper trapezius taking over the top of the lift.",
                 "Shrugging the shoulders toward the ears as the dumbbells rise.",
                 "Keep the shoulder blades down and the neck long, and lead the movement with the elbows rather than the hands."),
       "plane": ("Arm Path",
                 "The arms rise slightly in front of the body, not straight out to the side.",
                 "Raising the arms about 20–30° forward lines the lift up with the shoulder blade and keeps the joint comfortable.",
                 "Pulling the arms back behind the body at the top, which pinches the shoulder.",
                 "Keep the dumbbells slightly in front of the hips on the way up, with the hands level — neither thumbs nor pinkies tipped up."),
       "elbow": ("Elbow Bend",
                 "The arm is a fixed lever for the whole raise.",
                 "A slight, constant elbow bend keeps the load on the lateral deltoid; bending further as you lift shortens the lever and hands the work to the traps.",
                 "Bending the elbows more as the dumbbells rise, turning the raise into an upright row.",
                 "Set a soft bend in the elbows at the bottom and hold exactly that angle up and down."),
       "height": ("Range of Motion",
                  "The lateral deltoid does its work between the side of the body and shoulder height.",
                  "Raising to about shoulder height loads the lateral deltoid fully; going higher shifts the effort onto the upper trapezius.",
                  "Swinging the dumbbells up past the head, or stopping well short of shoulder level.",
                  "Raise until the arms are roughly parallel to the floor, pause briefly, then lower under control."),
       "torso": ("Torso Control",
                 "Momentum is the most common way to cheat this lift.",
                 "A still torso makes the lateral deltoid lift the weight from a dead stop instead of borrowing speed from the hips.",
                 "Rocking the torso to swing heavy dumbbells up.",
                 "Stand tall with soft knees, brace the core and raise the dumbbells without any body swing."),
   },
   activation=[("Lateral Deltoid", P, HI, 0.88), ("Posterior Deltoid", S, MOD, 0.50), ("Upper Trapezius", S, MOD, 0.45)],
   stabilisers=["rotator cuff", "serratus anterior", "core"],
   comparison=("SHRUGGING UP", "Shoulders down, arms to 90°", "Traps shrug the weight up",
               "With the shoulders held down, the lateral deltoid lifts the arm all the way to shoulder height.",
               "Shrugging hands the top of the raise to the upper trapezius — which is why the traps often feel lateral raises more than the shoulders do."),
   glows=[(A, 0.55, 0.12, 0.08, 0.32, 0.31), (A, 0.55, 0.12, 0.08, 0.68, 0.31)])

ex(name="Cable Lateral Raise", var="cableLateralRaise", group="shoulders",
   annotations=[
       ("traps", "Shoulder down, no shrug", "support_TrapeziusUpper_L"),
       ("elbow", "Soft, fixed elbow", "forearm_L"),
       ("height", "Stop at shoulder height", "hand_L"),
       ("torso", "Stay upright, no lean", "spine"),
       ("setup", "Side-on to the stack", "foot_L"),
   ],
   cues={
       "traps": ("Shoulder Position",
                 "The working shoulder stays down throughout.",
                 "Keeping the shoulder blade down keeps the lateral deltoid, not the upper trapezius, lifting the arm.",
                 "Hiking the shoulder toward the ear as the handle rises.",
                 "Keep the working shoulder down and the neck long, leading with the elbow."),
       "elbow": ("Elbow Bend",
                 "The arm is a fixed lever for the whole raise.",
                 "A slight, constant elbow bend keeps the cable's pull on the lateral deltoid and off the elbow joint.",
                 "Bending the elbow as the handle rises, turning the raise into a pull.",
                 "Set a soft bend in the elbow at the bottom and hold it there on every rep."),
       "height": ("Range of Motion",
                  "The cable loads the whole arc, so use all of it.",
                  "Unlike a dumbbell, the cable keeps tension on the lateral deltoid at the bottom of the rep, where a free weight loads it least.",
                  "Stopping short at the bottom to rest, or yanking the handle above the head.",
                  "Let the handle travel in front of the body at the bottom, then raise until the arm is about parallel to the floor."),
       "torso": ("Torso Control",
                 "The body stays upright while the arm moves.",
                 "An upright torso means the deltoid moves the load instead of body weight leaning away from the stack.",
                 "Leaning away from the stack to swing the handle up.",
                 "Hold the frame lightly with the free hand, stand tall and brace so nothing moves but the arm."),
       "setup": ("Setup",
                 "Where you stand sets the line of pull.",
                 "Standing side-on with the pulley low means the cable pulls straight down across the body, which is the direction the lateral deltoid resists.",
                 "Facing the stack, or standing so close that the cable pulls the arm forward instead of down.",
                 "Set the pulley at its lowest point and stand side-on, a step away, holding the handle in the hand farthest from the stack."),
   },
   activation=[("Lateral Deltoid", P, HI, 0.86), ("Posterior Deltoid", S, MOD, 0.46), ("Upper Trapezius", S, MOD, 0.42)],
   stabilisers=["rotator cuff", "obliques", "core"],
   comparison=("LEANING AWAY", "Upright torso, arm to 90°", "Torso leans away from the stack",
               "Standing tall keeps the cable's pull on the lateral deltoid through the whole arc.",
               "Leaning away shortens the arc and lets body weight swing the handle up, taking load off the lateral deltoid."),
   glows=[(A, 0.55, 0.12, 0.08, 0.66, 0.31), (SOFT, 0.30, 0.10, 0.06, 0.60, 0.26)])

ex(name="Machine Lateral Raise", var="machineLateralRaise", group="shoulders",
   annotations=[
       ("traps", "No shrugging", "support_TrapeziusUpper_L"),
       ("pivot", "Shoulders level with pivot", "upper_arm_L"),
       ("pads", "Push through the elbows", "forearm_L"),
       ("height", "Lift to shoulder height", "hand_L"),
       ("back", "Sit tall, chest up", "spine"),
   ],
   cues={
       "traps": ("Shoulder Position",
                 "The shoulders stay down while the arms rise.",
                 "Shrugging lets the upper trapezius lift the pads; keeping the shoulders down keeps the lateral deltoid in charge.",
                 "Shoulders creeping up toward the ears near the top.",
                 "Keep the shoulder blades down and the neck long through every rep."),
       "pivot": ("Seat Setup",
                 "A machine raise only works if its pivot lines up with the shoulder.",
                 "With the shoulder joint level with the pivot, the pads travel the same arc as the arm and the lateral deltoid stays loaded throughout.",
                 "A seat too low or too high, so the pads slide along the arms and the shoulders shrug to compensate.",
                 "Adjust the seat so the tops of the shoulders line up with the machine's pivot points."),
       "pads": ("Contact Point",
                "Drive the movement from the elbows, not the hands.",
                "Pushing through the outsides of the arms keeps the lateral deltoid as the prime mover instead of the forearms pulling on the handles.",
                "Gripping the handles hard and pulling with the hands.",
                "Hold the handles lightly and press the outsides of the arms into the pads as you raise."),
       "height": ("Range of Motion",
                  "Lift to shoulder height and no higher.",
                  "The lateral deltoid does its work up to about 90° of abduction; above that the upper trapezius takes over.",
                  "Driving the pads above shoulder height, or cutting reps short at the bottom.",
                  "Raise until the arms are level with the shoulders, pause, and lower under control."),
       "back": ("Posture",
                "The torso stays still against the machine.",
                "A tall, still torso stops momentum from the hips starting each rep.",
                "Rocking back or slumping to heave the pads up.",
                "Sit tall with the chest up and keep the torso still for the whole set."),
   },
   activation=[("Lateral Deltoid", P, HI, 0.84), ("Upper Trapezius", S, MOD, 0.40), ("Anterior Deltoid", S, MOD, 0.38)],
   stabilisers=["rotator cuff", "serratus anterior"],
   comparison=("SHRUGGING UP", "Shoulders down, arms to 90°", "Traps shrug the pads up",
               "Keeping the shoulders down lets the lateral deltoid lift the pads through the machine's full arc.",
               "Shrugging hands the top of each rep to the upper trapezius and takes tension off the lateral deltoid."),
   glows=[(A, 0.55, 0.12, 0.08, 0.32, 0.31), (A, 0.55, 0.12, 0.08, 0.68, 0.31)])

ex(name="Dumbbell Front Raise", var="dumbbellFrontRaise", group="shoulders",
   annotations=[
       ("height", "Stop at shoulder height", "hand_L"),
       ("shoulder", "Shoulders down and back", "upper_arm_L"),
       ("elbow", "Soft, fixed elbows", "forearm_L"),
       ("torso", "No backward lean", "spine"),
       ("stance", "Knees soft, feet hip-width", "foot_L"),
   ],
   cues={
       "height": ("Range of Motion",
                  "The anterior deltoid lifts the arm forward to about shoulder height.",
                  "Raising to shoulder level trains the front deltoid through its working range; above that the upper trapezius and serratus take over.",
                  "Swinging the dumbbells up to overhead height.",
                  "Lift until the arms are about parallel to the floor, pause, and lower slowly."),
       "shoulder": ("Shoulder Position",
                    "The shoulders stay set while the arms move.",
                    "Keeping the shoulder blades down and back stops the shoulders rolling forward and the traps shrugging the weight up.",
                    "Shoulders hunching forward and up as the dumbbells rise.",
                    "Set the shoulders down and back before the first rep and keep them there."),
       "elbow": ("Arm Position",
                 "A long arm makes a long lever for the front deltoid.",
                 "A soft, fixed elbow keeps the lever long and the stress off the elbow joint.",
                 "Bending the elbows as the dumbbells rise, which shortens the lever and invites a swing.",
                 "Keep a slight bend in the elbows and hold it constant through the rep."),
       "torso": ("Torso Control",
                 "Only the arms should move.",
                 "Leaning back uses body weight to start the lift and arches the lower back.",
                 "Rocking the torso back to swing the dumbbells up.",
                 "Brace the core, squeeze the glutes and keep the torso vertical from the first rep to the last."),
       "stance": ("Base",
                  "A stable base makes a strict raise possible.",
                  "Soft knees and hip-width feet absorb nothing and give the arms a still platform to lift from.",
                  "Locked knees and a narrow stance that tips the body back as the weights come up.",
                  "Stand with the feet hip-width apart and the knees slightly bent."),
   },
   activation=[("Anterior Deltoid", P, HI, 0.88), ("Upper Pectoralis", S, MOD, 0.50), ("Lateral Deltoid", S, MOD, 0.38)],
   stabilisers=["serratus anterior", "rotator cuff", "core"],
   comparison=("SWINGING THE WEIGHT", "Controlled lift to shoulder height", "Hips swing the dumbbells up",
               "A controlled raise to shoulder height keeps the front deltoid lifting the full weight.",
               "Swinging with the hips and lower back moves the dumbbells with momentum and leaves the front deltoid doing little of the work."),
   glows=[(A, 0.55, 0.14, 0.08, 0.40, 0.31), (A, 0.55, 0.14, 0.08, 0.60, 0.31)])

ex(name="Reverse Dumbbell Fly", var="reverseDumbbellFly", group="shoulders",
   annotations=[
       ("neck", "Neck neutral, chin tucked", "head"),
       ("elbow", "Soft, fixed elbows", "forearm_L"),
       ("path", "Arms out wide, not back", "hand_L"),
       ("hinge", "Hinge to near parallel", "pelvis"),
       ("feet", "Knees soft, weight mid-foot", "foot_L"),
   ],
   cues={
       "neck": ("Head Position",
                "The head stays in line with a bent-over spine.",
                "A neutral neck keeps the whole spine in line while the torso is bent over.",
                "Craning the head up to watch the mirror.",
                "Keep the chin tucked and look at the floor a little ahead of the feet."),
       "elbow": ("Elbow Bend",
                 "A fly keeps the arms long; a row bends them.",
                 "A slight, locked elbow bend keeps a long lever on the rear deltoid; bending further turns the fly into a row for the lats and mid-back.",
                 "Bending the elbows and pulling the dumbbells back like a row.",
                 "Hold a soft bend in the elbows and keep it constant through the rep."),
       "path": ("Arm Path",
                "The arms travel out to the sides in a wide arc.",
                "Moving the arms out, perpendicular to the torso, is exactly what the posterior deltoid does; sweeping them back toward the hips hands the work to the lats.",
                "Sweeping the dumbbells back toward the hips.",
                "Raise the dumbbells straight out to the sides until the upper arms are level with the torso."),
       "hinge": ("Torso Angle",
                 "The rear deltoids only work against gravity if the torso is bent over far enough.",
                 "Hinging until the torso is close to parallel lines the arms' path up with the posterior deltoid's line of pull.",
                 "Standing too upright, so the raise becomes a lateral raise for the side delts.",
                 "Push the hips back with soft knees and a flat back until the torso is roughly parallel to the floor."),
       "feet": ("Base",
                "The legs hold the hinge so the back doesn't have to.",
                "Soft knees and weight over mid-foot let the hips hold the position without the lower back tiring first.",
                "Locked knees and the weight rocking onto the toes.",
                "Stand hip-width with the knees slightly bent and the weight balanced over mid-foot."),
   },
   activation=[("Posterior Deltoid", P, HI, 0.86), ("Middle Trapezius", S, MOD, 0.58), ("Lateral Deltoid", S, MOD, 0.40)],
   stabilisers=["erector spinae", "hamstrings", "forearms"],
   comparison=("ROWING THE WEIGHT", "Arms sweep out wide", "Elbows bend into a row",
               "Long arms sweeping straight out to the sides keep the rear deltoid as the prime mover.",
               "Bending the elbows and pulling back turns the fly into a row, shifting the work to the lats and mid-back."),
   glows=[(A, 0.55, 0.14, 0.08, 0.34, 0.30), (A, 0.55, 0.14, 0.08, 0.66, 0.30)])

ex(name="Reverse Pec Deck", var="reversePecDeck", group="shoulders",
   annotations=[
       ("traps", "Shoulders down", "support_TrapeziusUpper_L"),
       ("seat", "Handles at shoulder height", "upper_arm_L"),
       ("elbow", "Soft, fixed elbows", "forearm_L"),
       ("path", "Sweep out, not back", "hand_L"),
       ("chest", "Chest on the pad", "chest"),
   ],
   cues={
       "traps": ("Shoulder Position",
                 "The rear deltoids should move the handles, not the traps.",
                 "Keeping the shoulders down limits the upper trapezius and keeps the effort on the posterior deltoid.",
                 "Shrugging the shoulders up and back to finish each rep.",
                 "Keep the shoulder blades down and the neck long through the whole set."),
       "seat": ("Seat Height",
                "The seat decides the angle of pull.",
                "With the handles at shoulder height the arms move in the horizontal plane where the posterior deltoid is the prime mover.",
                "A seat so high the arms pull downward, turning the movement into a row.",
                "Set the seat so the handles line up with the shoulders when you hold them."),
       "elbow": ("Elbow Bend",
                 "The arms stay long throughout.",
                 "A slight, fixed elbow bend keeps the lever long on the rear deltoid.",
                 "Bending the elbows to pull the handles back.",
                 "Hold the handles with a soft bend in the elbows and keep that angle on every rep."),
       "path": ("Arm Path",
                "The handles travel out to the sides in a wide arc.",
                "Moving the arms out to the sides at shoulder height is horizontal abduction, the posterior deltoid's main job; pulling back toward the hips shifts work to the lats.",
                "Driving the elbows down and back.",
                "Sweep the arms out until they line up with the torso, pause, and return under control."),
       "chest": ("Body Position",
                 "The pad keeps the torso out of the lift.",
                 "With the chest on the pad, momentum can't start the rep and the rear deltoids work from a dead stop.",
                 "Leaning back off the pad to heave the handles.",
                 "Keep the chest against the pad and the back still for the whole set."),
   },
   activation=[("Posterior Deltoid", P, HI, 0.88), ("Middle Trapezius", S, MOD, 0.56), ("Lateral Deltoid", S, MOD, 0.40)],
   stabilisers=["rotator cuff", "lower trapezius", "forearms"],
   comparison=("SHRUGGING BACK", "Shoulders down, arms sweep wide", "Traps shrug the handles back",
               "Keeping the shoulders down lets the rear deltoids sweep the handles through the machine's full arc.",
               "Shrugging and squeezing the shoulder blades hard turns the movement into a trap exercise and cuts the rear deltoid's range."),
   glows=[(A, 0.55, 0.14, 0.08, 0.34, 0.30), (A, 0.55, 0.14, 0.08, 0.66, 0.30)])

ex(name="Face Pull", var="facePull", group="shoulders",
   annotations=[
       ("target", "Pull to the face", "head"),
       ("rotate", "Rotate hands back", "hand_L"),
       ("elbow", "Elbows high and wide", "forearm_L"),
       ("scapula", "Squeeze the blades", "scapula_L"),
       ("stance", "Staggered, braced stance", "foot_L"),
   ],
   cues={
       "target": ("Pull Target",
                  "The rope comes to the face, not the chest.",
                  "Pulling toward the eyes keeps the upper arms up and out, so the rear deltoids and external rotators do the work.",
                  "Rowing the rope down to the chest, which turns it into a cable row for the lats.",
                  "Set the pulley at about upper-chest to face height and pull the middle of the rope toward the eyes."),
       "rotate": ("External Rotation",
                  "A face pull finishes with an outward rotation of the shoulders.",
                  "Pulling the rope ends apart and turning the knuckles back trains the infraspinatus and teres minor, the rotator cuff muscles that balance heavy pressing.",
                  "Stopping with the hands in front of the face and the forearms pointing forward.",
                  "Split the rope as it nears the face and finish with the hands beside the ears, knuckles pointing back."),
       "elbow": ("Elbow Height",
                 "The elbows stay at or above shoulder height.",
                 "High, wide elbows keep the pull horizontal for the posterior deltoid; low elbows turn it into a row.",
                 "Elbows dropping below the hands and tucking into the sides.",
                 "Lead with the elbows, keeping them level with or slightly above the shoulders."),
       "scapula": ("Shoulder Blades",
                   "Let the shoulder blades move, under control.",
                   "Drawing the shoulder blades together at the finish brings in the middle trapezius alongside the rear deltoids.",
                   "Shoulders rounding forward throughout, or the rope yanked in with a jerk.",
                   "Squeeze the shoulder blades together at the end of each rep, then let them glide forward as the rope returns."),
       "stance": ("Stance",
                  "The body stays still while the arms pull.",
                  "A staggered stance and braced trunk stop you leaning back and using body weight to move the stack.",
                  "Leaning back further on every rep to keep the weight moving.",
                  "Stand with one foot slightly ahead, brace the core and keep the torso still."),
   },
   activation=[("Posterior Deltoid", P, HI, 0.82), ("Middle Trapezius", S, MOD, 0.62), ("Rotator Cuff", S, MOD, 0.50)],
   stabilisers=["lower trapezius", "biceps brachii", "core"],
   comparison=("ROWING TO THE CHEST", "Rope to the face, elbows high", "Elbows drop, rope rows to the chest",
               "Pulling high to the face with the elbows up keeps the rear deltoids and rotator cuff doing the work.",
               "Letting the elbows drop and rowing to the chest turns the face pull into a row, so the lats take over from the rear deltoids."),
   glows=[(A, 0.55, 0.14, 0.08, 0.34, 0.30), (A, 0.55, 0.14, 0.08, 0.66, 0.30)])

ex(name="Cable Rear Delt Fly", var="cableRearDeltFly", group="shoulders",
   annotations=[
       ("traps", "Shoulders down", "support_TrapeziusUpper_L"),
       ("height", "Pull at shoulder height", "upper_arm_L"),
       ("elbow", "Arms long, soft elbows", "forearm_L"),
       ("path", "Sweep out, not down", "hand_L"),
       ("stance", "Stand tall, feet planted", "foot_L"),
   ],
   cues={
       "traps": ("Shoulder Position",
                 "The shoulders stay down as the arms open.",
                 "Keeping the shoulders down stops the upper trapezius taking the load off the rear deltoids.",
                 "Shrugging up and back at the end of every rep.",
                 "Keep the shoulder blades down and the neck long throughout."),
       "height": ("Setup",
                  "The pulleys set the plane of the movement.",
                  "With the pulleys at shoulder height and the cables crossed, the rear deltoids are loaded from a stretched start all the way to the finish.",
                  "Pulleys set low, so the arms pull downward like a straight-arm pulldown.",
                  "Set both pulleys at shoulder height, take the left handle in the right hand and the right in the left, and step back to the middle."),
       "elbow": ("Elbow Bend",
                 "The arms stay long; bending them makes it a row.",
                 "A slight, fixed elbow bend keeps the lever long on the posterior deltoid.",
                 "Bending the elbows to pull the handles in.",
                 "Hold a soft bend in the elbows and keep it constant through each rep."),
       "path": ("Arm Path",
                "The hands travel out to the sides at shoulder height.",
                "Horizontal abduction at shoulder height is the posterior deltoid's main job; letting the hands drop turns the pull toward the lats.",
                "Hands dipping down toward the hips as the cables open.",
                "Sweep the arms out wide until they line up with the torso, pause, and return slowly."),
       "stance": ("Stance",
                  "Only the arms should move.",
                  "A tall, braced stance stops you leaning back to move the stack.",
                  "Rocking the torso back to finish each rep.",
                  "Stand tall with the feet planted about hip-width apart and the core braced."),
   },
   activation=[("Posterior Deltoid", P, HI, 0.86), ("Middle Trapezius", S, MOD, 0.54), ("Lateral Deltoid", S, MOD, 0.40)],
   stabilisers=["rotator cuff", "lower trapezius", "core"],
   comparison=("SHRUGGING BACK", "Arms sweep out at shoulder height", "Shoulders shrug the cables back",
               "Long arms sweeping out at shoulder height keep the rear deltoids doing the work.",
               "Shrugging and pulling the handles down and back hands the movement to the traps and lats."),
   glows=[(A, 0.55, 0.14, 0.08, 0.34, 0.30), (A, 0.55, 0.14, 0.08, 0.66, 0.30)])

# --------------------------------------------------------------------- Arms

ex(name="Barbell Curl", var="barbellCurl", group="arms",
   annotations=[
       ("shoulder", "Shoulders stay back", "upper_arm_L"),
       ("elbow", "Elbows pinned to sides", "forearm_L"),
       ("grip", "Shoulder-width grip", "hand_L"),
       ("torso", "No hip swing", "pelvis"),
       ("range", "Lower all the way down", "hand_R"),
   ],
   cues={
       "shoulder": ("Shoulder Position",
                    "The shoulders stay back and still.",
                    "Rolling the shoulders forward to finish the curl brings the front deltoid in and takes tension off the biceps.",
                    "Shoulders rounding forward and the bar drifting away from the body at the top.",
                    "Keep the chest up and the shoulders back, and stop the curl before the elbows start to travel forward."),
       "elbow": ("Elbow Position",
                 "The elbows are the hinge of a curl, and a hinge doesn't move.",
                 "Keeping the elbows by the sides makes elbow flexion the only motion, so the biceps and brachialis lift the bar instead of the front deltoids.",
                 "Elbows drifting forward as the bar rises, which shortens the range and hands the top of the rep to the shoulders.",
                 "Pin the elbows lightly against the ribs and keep them there from the bottom of the rep to the top."),
       "grip": ("Grip",
                "Hand position changes how hard the biceps work.",
                "A shoulder-width underhand grip keeps the forearms fully supinated, the position in which the biceps brachii is strongest.",
                "A grip so narrow or wide that the wrists bend and the forearms fatigue first.",
                "Hold the bar palms-up with the hands about shoulder-width apart and the wrists straight."),
       "torso": ("Body Swing",
                 "The legs and back have no part in a strict curl.",
                 "Swinging the hips uses momentum from the legs and lower back and loads the spine.",
                 "Rocking the hips forward and the torso back to heave the bar up.",
                 "Stand tall with soft knees, brace the core and keep the torso still for every rep."),
       "range": ("Range of Motion",
                 "Each rep starts from straight arms.",
                 "Lowering to fully straight arms trains the biceps through its whole length, and a slow lowering phase adds time under tension.",
                 "Half reps that never let the elbows straighten.",
                 "Lower over two to three seconds until the arms are straight, then curl again without bouncing."),
   },
   activation=[("Biceps Brachii", P, HI, 0.90), ("Brachialis", S, MOD, 0.66), ("Brachioradialis", S, MOD, 0.52)],
   stabilisers=["anterior deltoid", "forearm flexors", "core"],
   comparison=("SWINGING THE BAR", "Elbows fixed, torso still", "Hips and back swing the bar up",
               "With the elbows fixed and the torso still, the biceps lift the bar through the whole range.",
               "Swinging uses the hips and lower back to start the rep, so the biceps skip the hardest part of the lift and the spine takes the strain."),
   glows=[(A, 0.55, 0.10, 0.08, 0.30, 0.40), (A, 0.55, 0.10, 0.08, 0.70, 0.40)])

pushdown_cues = {
    "elbow": ("Elbow Position",
              "The elbows are pinned; only the forearms move.",
              "Pinned elbows make elbow extension the only motion, so the triceps move the load; elbows that drift forward bring the lats, chest and shoulders in.",
              "Elbows lifting and flaring forward as the handle comes up.",
              "Tuck the elbows against the sides of the torso and keep them there for the whole set."),
    "lockout": ("Lockout",
                "Every rep finishes with straight arms.",
                "The triceps reach full contraction at full elbow extension, so cutting reps short skips the hardest part of the lift.",
                "Stopping each rep with the elbows still bent.",
                "Push down until the arms are fully straight, pause briefly, then let the handle rise under control."),
    "shoulder": ("Shoulder Position",
                 "The shoulders stay set so the arms can do the work.",
                 "Rolling the shoulders forward and leaning over the handle lets body weight push it down.",
                 "Hunching over the handle and shrugging the shoulders up.",
                 "Keep the chest up and the shoulders down and back."),
    "torso": ("Torso Angle",
              "A slight lean gives the cable a clear path.",
              "Hinging a little forward from the hips lets the handle travel straight down past the body without catching on the torso.",
              "Leaning further on every rep to push the stack with body weight.",
              "Hinge slightly forward, brace the core and hold that angle for the whole set."),
    "feet": ("Base",
             "A still base keeps the body out of the lift.",
             "A hip-width stance with soft knees gives a stable platform, so the triceps work against the full load.",
             "Standing so close to the stack that the body sways with each rep.",
             "Stand hip-width, about a foot from the stack, with the knees slightly bent."),
}

ex(name="Triceps Pushdown", var="tricepsPushdown", group="arms",
   annotations=[
       ("shoulder", "Shoulders down and back", "upper_arm_L"),
       ("elbow", "Elbows pinned to sides", "forearm_L"),
       ("lockout", "Full lockout at the bottom", "hand_L"),
       ("torso", "Slight forward lean", "spine"),
       ("feet", "Hip-width, knees soft", "foot_L"),
   ],
   cues=pushdown_cues,
   activation=[("Triceps Brachii", P, HI, 0.86)],
   stabilisers=["latissimus dorsi", "forearms", "core"],
   comparison=("ELBOWS FLARING", "Elbows fixed at the sides", "Elbows lift and flare forward",
               "With the elbows pinned, the triceps extend the elbow against the whole stack.",
               "Letting the elbows drift forward brings the lats and chest into the push and takes load off the triceps."),
   glows=[(A, 0.55, 0.09, 0.10, 0.30, 0.38), (A, 0.55, 0.09, 0.10, 0.70, 0.38)])

rope_cues = dict(pushdown_cues)
rope_cues["split"] = ("Rope Split",
                      "The rope lets the hands finish wider than a bar.",
                      "Pulling the rope ends apart at the bottom lets the hands pass the thighs, so the elbows reach full extension.",
                      "Keeping the hands together so the rope stops against the thighs short of lockout.",
                      "As the hands pass the waist, spread the rope ends apart and finish with the arms fully straight.")

ex(name="Rope Pushdown", var="ropePushdown", group="arms",
   annotations=[
       ("shoulder", "Shoulders down and back", "upper_arm_L"),
       ("elbow", "Elbows pinned to sides", "forearm_L"),
       ("split", "Spread the rope at the bottom", "hand_L"),
       ("torso", "Slight forward lean", "spine"),
       ("feet", "Hip-width, knees soft", "foot_L"),
   ],
   cues=rope_cues,
   activation=[("Triceps Brachii", P, HI, 0.88)],
   stabilisers=["latissimus dorsi", "forearms", "core"],
   comparison=("CUTTING THE LOCKOUT", "Rope split, arms straight", "Hands stop at the thighs",
               "Splitting the rope at the bottom lets the elbows straighten fully, where the triceps contract hardest.",
               "Stopping with the rope against the thighs leaves the elbows bent and skips the triceps' strongest contraction."),
   glows=[(A, 0.55, 0.09, 0.10, 0.30, 0.38), (A, 0.55, 0.09, 0.10, 0.70, 0.38)])

single_cues = dict(pushdown_cues)
single_cues["hips"] = ("Hips & Torso",
                       "Working one arm at a time invites a twist.",
                       "Keeping the hips and shoulders square stops the torso rotating to push the handle down, so one triceps does all the work.",
                       "Twisting the torso toward the working side to finish each rep.",
                       "Face the stack squarely, brace the core and keep the free hand on the hip or the frame.")

ex(name="Single-Arm Cable Pushdown", var="singleArmCablePushdown", group="arms",
   annotations=[
       ("shoulder", "Shoulder stays down", "upper_arm_L"),
       ("elbow", "Elbow pinned to the side", "forearm_L"),
       ("lockout", "Full lockout at the bottom", "hand_L"),
       ("hips", "Hips square, no twist", "pelvis"),
       ("feet", "Hip-width, knees soft", "foot_L"),
   ],
   cues=single_cues,
   activation=[("Triceps Brachii", P, HI, 0.86)],
   stabilisers=["obliques", "latissimus dorsi", "forearms"],
   comparison=("TWISTING THE TORSO", "Hips square, elbow pinned", "Torso twists to push the handle",
               "Staying square to the stack keeps the working triceps moving the whole load on its own.",
               "Twisting the torso uses body rotation to push the handle and hides a strength difference between arms."),
   glows=[(A, 0.55, 0.09, 0.10, 0.70, 0.38), (SOFT, 0.25, 0.08, 0.08, 0.30, 0.38)])

overhead_cues = {
    "elbow": ("Elbow Position",
              "The elbows point forward, not out.",
              "Keeping the elbows close to the head and pointing forward holds the upper arm still, so only the elbow bends; flared elbows shift the load to the shoulders.",
              "Elbows splaying out to the sides as the weight lowers.",
              "Keep the elbows about shoulder-width, pointing forward, from the bottom of the rep to the top."),
    "stretch": ("Stretch Position",
                "The overhead position is what sets this lift apart.",
                "With the arms overhead, the long head of the triceps — which crosses the shoulder — is stretched, and training at that length has been shown to grow the triceps more than pushdowns.",
                "Shortening the range so the hands never drop behind the head.",
                "Lower the hands behind the head until the elbows are fully bent, then extend back to straight arms."),
    "upperarm": ("Upper Arm Position",
                 "The upper arms stay fixed beside the head.",
                 "Still upper arms keep the work on elbow extension; letting them swing forward turns the lift into a pullover.",
                 "Upper arms dropping forward as the weight comes up.",
                 "Keep the upper arms close to the ears and let only the forearms move."),
    "brace": ("Trunk Control",
              "Reaching overhead tempts the lower back to arch.",
              "Keeping the ribs down and the core braced stops the lower back arching to make room for the weight.",
              "Arching the lower back and flaring the ribs to get the arms overhead.",
              "Brace the abs, squeeze the glutes and keep the ribs stacked over the pelvis."),
    "stance": ("Stance",
               "A stable stance keeps the body out of the lift.",
               "A split or hip-width stance with soft knees gives the arms a still base to extend from.",
               "Locked knees and a narrow stance that sways with each rep.",
               "Stand with the feet hip-width or one foot forward, knees soft, and hold that position."),
    "grip": ("Grip",
             "Two hands hold one dumbbell.",
             "Cupping the top plate with both palms keeps the dumbbell secure and the wrists straight overhead.",
             "Gripping the handle loosely with the fingers, so the dumbbell tips as it lowers.",
             "Hold the dumbbell vertically by its top plate, palms flat against it and thumbs wrapped around the handle."),
}

ex(name="Overhead Cable Triceps Extension", var="overheadCableTricepsExtension", group="arms",
   annotations=[
       ("stretch", "Deep stretch behind the head", "hand_L"),
       ("elbow", "Elbows point forward", "forearm_L"),
       ("upperarm", "Upper arms by the ears", "upper_arm_L"),
       ("brace", "Ribs down, no arch", "spine"),
       ("stance", "Staggered stance", "foot_L"),
   ],
   cues=overhead_cues,
   activation=[("Triceps Brachii", P, HI, 0.88)],
   stabilisers=["core", "rotator cuff", "serratus anterior"],
   comparison=("ELBOWS FLARED", "Elbows forward, upper arms fixed", "Elbows splay out to the sides",
               "With the elbows forward and the upper arms still, the triceps extend the elbow from a full stretch.",
               "Flared elbows shorten the triceps' stretch and shift load onto the shoulders."),
   glows=[(A, 0.55, 0.09, 0.10, 0.36, 0.26), (A, 0.55, 0.09, 0.10, 0.64, 0.26)])

ex(name="Dumbbell Overhead Triceps Extension", var="dumbbellOverheadTricepsExtension", group="arms",
   annotations=[
       ("grip", "Cup the top plate", "hand_L"),
       ("elbow", "Elbows point forward", "forearm_L"),
       ("upperarm", "Upper arms by the ears", "upper_arm_L"),
       ("brace", "Ribs down, no arch", "spine"),
       ("stance", "Feet hip-width, knees soft", "foot_L"),
   ],
   cues=overhead_cues,
   activation=[("Triceps Brachii", P, HI, 0.88)],
   stabilisers=["core", "rotator cuff", "forearms"],
   comparison=("ARCHING THE BACK", "Ribs down, upper arms fixed", "Lower back arches overhead",
               "A braced trunk lets the arms stay overhead while only the elbows move.",
               "Arching the lower back to reach overhead shortens the triceps' stretch and loads the lumbar spine."),
   glows=[(A, 0.55, 0.09, 0.10, 0.36, 0.26), (A, 0.55, 0.09, 0.10, 0.64, 0.26)])

ex(name="Skull Crusher", var="skullCrusher", group="arms",
   # Lying flat, the pelvis, shoulder and feet all sit on one horizontal
   # line, so the rows are set by hand to keep every dot clear of a label.
   overrides={"bar": (0.14, "trailing"), "elbow": (0.32, "leading"), "back": (0.50, "leading"),
              "upperarm": (0.68, "trailing"), "feet": (0.86, "leading")},
   annotations=[
       ("elbow", "Elbows fixed, pointing up", "forearm_L"),
       ("bar", "Bar to the forehead", "hand_L"),
       ("upperarm", "Upper arms tilted back", "upper_arm_L"),
       ("back", "Hips on bench", "pelvis"),
       ("feet", "Feet flat on the floor", "foot_L"),
   ],
   cues={
       "elbow": ("Elbow Position",
                 "Only the elbows bend.",
                 "Fixed upper arms make elbow extension the only motion, so the triceps do the work instead of the lats and chest.",
                 "Elbows flaring wide as the bar lowers, or the upper arms swinging to help press it back up.",
                 "Keep the elbows about shoulder-width and pointing at the ceiling for every rep."),
       "bar": ("Bar Path",
               "The bar travels in an arc toward the head.",
               "Lowering the bar to the forehead or just behind it takes the triceps through a long range while keeping the path controlled.",
               "Dropping the bar quickly toward the face.",
               "Lower the bar slowly to the forehead or just behind the head, then extend the elbows to bring it back."),
       "upperarm": ("Arm Angle",
                    "The upper arms lean slightly back toward the head.",
                    "Tilting the upper arms back keeps tension on the triceps at the top, where vertical arms let the bones take the load.",
                    "Upper arms vertical at lockout, so the triceps rest between reps.",
                    "Start with the arms angled slightly back from vertical and keep that angle throughout."),
       "back": ("Body Position",
                "The body stays flat and still on the bench.",
                "Keeping the hips and upper back on the bench prevents arching and keeps the triceps working against the whole load.",
                "Lifting the hips or arching the back as the reps get hard.",
                "Keep the head, upper back and hips in contact with the bench throughout."),
       "feet": ("Base",
                "The feet anchor the body to the floor.",
                "Flat feet give a stable base so the body doesn't shift as the bar moves overhead.",
                "Feet up on the bench edge or on the toes.",
                "Plant both feet flat on the floor, about hip-width apart."),
   },
   activation=[("Triceps Brachii", P, HI, 0.86)],
   stabilisers=["latissimus dorsi", "forearms", "rotator cuff"],
   comparison=("ELBOWS FLARING OUT", "Elbows narrow and fixed", "Elbows splay wide as the bar lowers",
               "Narrow, fixed elbows keep the triceps extending the elbow in a clean arc.",
               "Flared elbows turn the lift into a press, shifting the load onto the chest and shoulders."),
   glows=[(A, 0.55, 0.09, 0.10, 0.50, 0.30)])

ex(name="Bench Dip", var="benchDip", group="arms",
   annotations=[
       ("elbow", "Elbows point straight back", "forearm_L"),
       ("depth", "Stop at 90° elbow bend", "upper_arm_L"),
       ("hips", "Hips close to the bench", "pelvis"),
       ("hands", "Hands by the hips", "hand_L"),
       ("feet", "Legs out, heels down", "foot_L"),
   ],
   cues={
       "elbow": ("Elbow Position",
                 "The elbows track straight back, not out.",
                 "Elbows pointing back keep the triceps extending the elbow in line and spare the shoulder a twisting load.",
                 "Elbows flaring out to the sides as the body lowers.",
                 "Keep the elbows pointing straight behind you and close to the body throughout."),
       "depth": ("Depth",
                 "The bench dip takes the shoulder close to the end of its range.",
                 "Bench dips extend the shoulder further than bar dips, so stopping with the upper arms about parallel to the floor keeps the front of the shoulder out of a vulnerable stretch.",
                 "Dropping as low as possible, rolling the shoulders forward at the bottom.",
                 "Lower until the elbows reach about 90°, then press back up to straight arms."),
       "hips": ("Body Position",
                "The body lowers straight down, close to the bench.",
                "Keeping the hips close to the bench keeps the load on the triceps rather than turning the dip into a shoulder stretch.",
                "Letting the hips drift away from the bench as you lower.",
                "Slide the hips off the bench just enough to clear it and keep the back close to it throughout."),
       "hands": ("Hand Position",
                 "The hands set the shoulder position.",
                 "Hands beside the hips with the fingers forward keep the shoulders in a stable, neutral position.",
                 "Hands set wide or turned out, which rotates the shoulders.",
                 "Place the hands shoulder-width on the bench edge, beside the hips, fingers pointing forward."),
       "feet": ("Leg Position",
                "The legs control how much body weight the arms lift.",
                "Straighter legs put more load on the triceps; bent knees make the dip easier.",
                "Pushing off the heels to help the arms up.",
                "Set the legs out with the heels down, bending the knees more if you need it easier, and keep them passive."),
   },
   activation=[("Triceps Brachii", P, HI, 0.86), ("Anterior Deltoid", S, MOD, 0.46)],
   stabilisers=["pectoralis major", "serratus anterior", "core"],
   comparison=("DIPPING TOO DEEP", "Stop at a 90° elbow bend", "Shoulders roll forward past 90°",
               "Stopping with the upper arms parallel to the floor loads the triceps through a full, safe range.",
               "Dipping past 90° forces the shoulder into extreme extension and rolls it forward, straining the front of the joint."),
   glows=[(A, 0.55, 0.09, 0.10, 0.34, 0.36), (A, 0.55, 0.09, 0.10, 0.66, 0.36)])

ex(name="Assisted Dip", var="assistedDip", group="arms",
   annotations=[
       ("torso", "Torso upright", "chest"),
       ("depth", "Lower to a 90° elbow bend", "upper_arm_R"),
       ("elbow", "Elbows tucked back", "forearm_R"),
       ("lockout", "Press to full lockout", "hand_R"),
       ("knees", "Knees centred on the pad", "patella_R"),
   ],
   cues={
       "torso": ("Torso Angle",
                 "How far you lean decides which muscle leads.",
                 "An upright torso keeps the triceps as the prime mover; leaning forward shifts more of the work to the chest.",
                 "Pitching forward over the handles on every rep.",
                 "Keep the chest up and the torso close to vertical as you lower and press."),
       "depth": ("Depth",
                 "Go deep enough to load the triceps, not the shoulder joint.",
                 "Lowering until the upper arms are about parallel to the floor trains the triceps through a full range without over-stretching the front of the shoulder.",
                 "Sinking far below 90° with the shoulders rolling forward.",
                 "Lower until the elbows reach about 90°, then press back up."),
       "elbow": ("Elbow Position",
                 "The elbows travel straight back.",
                 "Elbows tucked close to the body keep the triceps working in line and the shoulders stable.",
                 "Elbows flaring out to the sides at the bottom.",
                 "Keep the elbows pointing back and close to the torso throughout."),
       "lockout": ("Lockout",
                   "Each rep finishes with straight arms.",
                   "Full elbow extension at the top is where the triceps contract hardest.",
                   "Stopping short of lockout and bouncing out of the bottom.",
                   "Press until the arms are straight and the shoulders are down, then lower under control."),
       "knees": ("Machine Setup",
                 "The assistance pad takes some of your body weight.",
                 "More counterweight makes the dip easier, so you can pick an amount that allows clean reps through the full range.",
                 "Using so little assistance that form breaks down, or kneeling off-centre so the pad tips.",
                 "Kneel centred on the pad, choose an assistance weight that lets you reach 90° with control, and reduce it as you get stronger."),
   },
   activation=[("Triceps Brachii", P, HI, 0.84), ("Pectoralis Major", S, MOD, 0.56), ("Anterior Deltoid", S, MOD, 0.48)],
   stabilisers=["serratus anterior", "latissimus dorsi", "rotator cuff"],
   comparison=("SHOULDERS ROLL FORWARD", "Chest up, shoulders back", "Shoulders roll forward at the bottom",
               "Keeping the chest up and shoulders back lets the triceps press through a full, controlled range.",
               "Letting the shoulders roll forward at the bottom stretches the front of the joint and shifts the effort away from the triceps."),
   glows=[(A, 0.55, 0.09, 0.10, 0.34, 0.36), (SOFT, 0.30, 0.16, 0.08, 0.50, 0.30)])

# --------------------------------------------------------------------- Legs

ex(name="Bulgarian Split Squat", var="bulgarianSplitSquat", group="legs",
   overrides={"depth": (0.50, "leading"), "knee": (0.68, "trailing")},
   annotations=[
       ("torso", "Torso upright", "chest"),
       ("grip", "Dumbbells at your sides", "hand_L"),
       ("knee", "Front knee tracks the toes", "patella_L"),
       ("depth", "Back knee toward the floor", "patella_R"),
       ("front", "Front foot flat, mid-foot", "foot_L"),
   ],
   cues={
       "torso": ("Torso Position",
                 "An upright torso makes this a quad-dominant split squat.",
                 "Keeping the torso vertical keeps the load over the front knee, where the quadriceps do most of the work.",
                 "Folding forward at the bottom without meaning to, or arching the lower back.",
                 "Keep the chest up and the shoulders over the hips as you lower and drive up."),
       "grip": ("Load Position",
                "Where the dumbbells hang decides how upright you can stay.",
                "With the weights at arm's length by the sides, the load sits under the shoulders, so the torso stays vertical and the front leg does the work.",
                "Letting the dumbbells drift forward or shrugging them up, which pulls the chest down.",
                "Hold the dumbbells at arm's length by your sides, shoulders down, and let them travel straight down and up with you."),
       "knee": ("Knee Tracking",
                "The front knee follows the line of the foot.",
                "Tracking over the middle toes keeps the knee aligned while the quadriceps take the load.",
                "The front knee caving inward on the way up.",
                "Keep the front knee in line with the middle of the foot throughout the rep."),
       "depth": ("Depth",
                 "Drop straight down, not forward.",
                 "Lowering until the back knee nearly touches the floor takes the front leg through its full range, where most of the work happens.",
                 "Stopping halfway or letting the body drift forward instead of down.",
                 "Lower the back knee toward the floor until the front thigh is about parallel, then drive up through the front foot."),
       "front": ("Foot Setup",
                 "Set both feet before the first rep.",
                 "A front foot far enough from the bench stays flat with the shin near vertical, and resting the rear laces on the bench keeps the back leg passive so the front leg does the work.",
                 "Standing so close to the bench that the front heel lifts, or balancing on the rear toes and pushing off with them.",
                 "Rest the laces of the rear foot on a knee-height bench and place the front foot far enough forward that it stays flat at the bottom."),
   },
   activation=[("Quadriceps", P, HI, 0.86), ("Gluteus Maximus", S, MOD, 0.58), ("Gluteus Medius", S, MOD, 0.44)],
   stabilisers=["adductors", "hamstrings", "forearms", "core"],
   comparison=("FRONT HEEL LIFTING", "Whole front foot planted", "Front heel lifts, knee shoots forward",
               "A flat front foot with the shin near vertical keeps the load on the front leg's quads and glutes.",
               "When the front heel lifts, balance shifts onto the toes and the knee takes a sharp, unstable load."),
   glows=[(A, 0.55, 0.14, 0.12, 0.58, 0.62), (SOFT, 0.30, 0.12, 0.08, 0.54, 0.50)])

ex(name="Bulgarian Split Squat (Lean)", var="bulgarianSplitSquatLean", group="legs",
   overrides={"front": (0.86, "trailing")},
   annotations=[
       ("lean", "Lean ~40° from the hips", "chest"),
       ("hips", "Hips back, not just down", "pelvis"),
       ("knee", "Front knee tracks the toes", "patella_R"),
       ("rear", "Back knee drops straight down", "patella_L"),
       ("front", "Drive through the front heel", "foot_R"),
   ],
   cues={
       "lean": ("Torso Lean",
                "Leaning forward is what makes this variation glute-biased.",
                "A forward lean of about 40° increases gluteus maximus and hamstring activity compared with an upright split squat, while the quadriceps still work hard.",
                "Rounding the back to get the chest down instead of hinging at the hips.",
                "Keep the spine long and tilt the torso forward from the hips to roughly 40° before you descend."),
       "hips": ("Hip Hinge",
                "The hips travel back as well as down.",
                "Sending the hips back lengthens the glutes and hamstrings of the front leg, so they drive the ascent.",
                "Dropping straight down with the lean held only at the shoulders.",
                "Push the hips back as you lower, keeping the torso angle fixed throughout the rep."),
       "knee": ("Knee Tracking",
                "The front knee follows the line of the foot.",
                "Tracking over the middle toes keeps the knee aligned while the hip does more of the work.",
                "The front knee caving inward on the way up.",
                "Keep the front knee in line with the middle of the foot throughout the rep."),
       "rear": ("Rear Leg",
                "The back leg stays passive while its knee drops.",
                "Resting the rear laces on the bench keeps that leg relaxed, so as the back knee drops toward the floor nearly all the load stays on the front leg.",
                "Pushing off the rear toes to help the front leg up.",
                "Rest the rear laces on a knee-height bench, let that leg relax, and lower until the back knee is just above the floor."),
       "front": ("Front Foot",
                 "Drive through the heel and mid-foot.",
                 "Pushing through the heel keeps the load on the posterior chain the lean is meant to target.",
                 "Rising onto the ball of the front foot, which shifts the work back to the quads.",
                 "Keep the whole front foot planted and push the floor away through the heel as you stand."),
   },
   activation=[("Quadriceps", P, HI, 0.80), ("Gluteus Maximus", P, HI, 0.74), ("Hamstrings", S, MOD, 0.48)],
   stabilisers=["gluteus medius", "adductors", "erector spinae", "core"],
   comparison=("ROUNDED LOWER BACK", "Lean from the hips, spine long", "Back rounds instead of hinging",
               "Hinging from the hips with a long spine lets the lean load the glutes and hamstrings of the front leg.",
               "Rounding the back to fake the lean puts the load on the lumbar spine and leaves the glutes no more involved than an upright split squat."),
   glows=[(A, 0.55, 0.14, 0.12, 0.42, 0.60), (SOFT, 0.35, 0.14, 0.10, 0.46, 0.50)])
